In [76]:
import pandas as pd
from graph import Graph
from flight import Flight
from airport import Airport
from pnr import PNR
from datetime import datetime
import numpy as np
from dimod import BinaryQuadraticModel
import dimod
import itertools

#import singularity.optimization as sop

In [77]:
import time 
t1 = time.time()

In [78]:
SINGULARITY_TOKEN = "c8b07936-99b0-416f-a749-150da42f6aa1"
#DWAVE_API_TOKEN = "DEV-7b444792d7a75ce33cc91f50fac2e0e021db9259"

#=======================================================================================================
# Create the graph
flight_graph = Graph()

# Path to the CSV file
available_flights_df = 'data_files/PRMI-DM-AVAILABLE_FLIGHTS.csv'  
cancelled_flights_df = 'data_files/PRMI-DM_TARGET_FLIGHTS_test.csv' 

# Build the graph using the CSV file
flight_graph.add_flights_from_csv(available_flights_df)
flight_graph.add_cancelled_flights_from_csv(cancelled_flights_df)

# # Draw the graph
# flight_graph.draw_graph()

In [79]:
# Step 1: Load both CSV files
target_flights_df = pd.read_csv("data_files/PRMI-DM_TARGET_FLIGHTS.csv")
pnr_df = pd.read_csv("data_files/PRMI_DM_ALL_PNRs.csv")
available_flights_df = pd.read_csv("data_files/PRMI-DM-AVAILABLE_FLIGHTS.csv")

In [80]:
print("Reduced dataset!")

#available_flights_df = available_flights_df[ 0 : len(available_flights_df) // 2 ]
#cancelled_flights = cancelled_flights[0:2]
#pnr_df = pnr_df[0:10]
print("Passenger rows: ", len(pnr_df))
print("Flights rows: ", len(available_flights_df))

Reduced dataset!
Passenger rows:  43832
Flights rows:  3221

In [81]:
pnr_df[pnr_df["RECLOC"] == 1]

,RECLOC,CREATION_DTZ,CABIN_CD,COS_CD,OPER_OD_ORIG_CD,OPER_OD_DEST_CD,DEP_KEY,DEP_DT,ORIG_CD,DEST_CD,FLT_NUM,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ,OD_BROKEN_IND,PAX_CNT,CVM,CONN_TIME_MINS
1,1,2027-09-03,Y,21,KHL,RHP,AZ20271021KHLTPH9400,2027-10-21,KHL,TPH,9400,2027-10-21 11:38,2027-10-21 16:29,2027-10-21 14:38,2027-10-21 21:29,0,3,5.68905,NaN
2,1,2027-09-03,Y,20,RHP,KHL,AZ20271104RHPTPH3571,2027-11-04,RHP,TPH,3571,2027-11-04 19:57,2027-11-04 23:25,2027-11-05 0:57,2027-11-05 4:25,0,3,5.68905,NaN
3,1,2027-09-03,Y,20,RHP,KHL,AZ20271104TPHKHL548,2027-11-04,TPH,KHL,548,2027-11-05 0:51,2027-11-05 9:53,2027-11-05 5:51,2027-11-05 12:53,0,3,5.68905,86.0
4,1,2027-09-03,Y,21,KHL,RHP,AZ20271021TPHRHP12465,2027-10-21,TPH,RHP,12465,2027-10-21 18:25,2027-10-21 21:55,2027-10-21 23:25,2027-10-22 2:55,0,3,5.68905,116.0

In [82]:
# Step 2: Differentiate between trips as mentioned in the chat

pnr_df = pnr_df.sort_values(by=["DEP_DTML"], ascending = [True])
grouped = pnr_df.groupby(["RECLOC"])
for rec, group1 in grouped:
    trip_number = 1
    
    grouped2 = group1.groupby(["OPER_OD_ORIG_CD", "OPER_OD_DEST_CD", "DEP_DT"])

    for (orig, dest, date), group2 in grouped2:
        pnr_df.loc[group2.index, "TRIP_NUMBER"] = int(trip_number)
        trip_number = trip_number + 1

In [83]:
# Step 3: Filter PNRs with matching DEP_KEY in both datasets
# Extract the DEP_KEYs from the target flights
target_dep_keys = target_flights_df['DEP_KEY'].unique()

# Filter PNRs where DEP_KEY matches
matching_pnr_df = pnr_df[pnr_df['DEP_KEY'].isin(target_dep_keys)]

In [84]:
# Step 4: Create a list of PNR objects from the filtered PNR DataFrame

# Well what we can do is instead make the list of PASSENGERS (pnr_list) LONGER
# Such that each entrance is different according to the TRIP 
pnr_list_1leg = []
pnr_list_2leg = []
# Matrix saving all of the passengers independently of whether the trip is 1-leg or 2-legged
pnr_list = []

group = matching_pnr_df.groupby(["RECLOC", "TRIP_NUMBER"])

for rec_and_trpnr, group in group:
    recloc = rec_and_trpnr[0]
    trip_number = int( rec_and_trpnr[1] )
    
    # We select the selected pnr
    ## We select from the original PNR in order to differentiate between originally booked as direct or multi-legged
    ## And then re-scheduled as direct (forced or simple) direct
    selected_pnr = pnr_df[(pnr_df["RECLOC"] == recloc) & (pnr_df["TRIP_NUMBER"] == trip_number)] 

    # Now we iterate over all of the rows for this given configuration
    for ktrip, row in group.iterrows():
       #trip_id = f"{'1'}_{'2'}_{legs}legs_{'3'}"
       # We include the trip number and the number of legs
        trip_id = f"{row['RECLOC']}_{int(row['TRIP_NUMBER'])}_{row['DEP_KEY']}"
        pnr = PNR(
            recloc=row['RECLOC'],
            creation_dtz=row['CREATION_DTZ'],
            cabin_cd=row['CABIN_CD'],
            cos_cd=row['COS_CD'],
            oper_od_orig_cd=row['OPER_OD_ORIG_CD'],
            oper_od_dest_cd=row['OPER_OD_DEST_CD'],
            dep_key=row['DEP_KEY'],
            dep_dt=row['DEP_DT'],
            orig_cd=row['ORIG_CD'],
            dest_cd=row['DEST_CD'],
            flt_num=row['FLT_NUM'],
            dep_dtml=row['DEP_DTML'],
            arr_dtml=row['ARR_DTML'],
            dep_dtmz=row['DEP_DTMZ'],
            arr_dtmz=row['ARR_DTMZ'],
            od_broken_ind=row['OD_BROKEN_IND'],
            pax_cnt=row['PAX_CNT'],
            cvm=row['CVM'],
            conn_time_mins=row['CONN_TIME_MINS']
        )
        pnr.trip_id = trip_id
        pnr.trip_number = int(trip_number),
        pnr.trip_legs = len(group),

        ## Now we check if the trip was originally booked as multi-legged or not
        ## The trip only consists of one flight
        if ((pnr.oper_od_orig_cd == pnr.orig_cd) & (pnr.oper_od_dest_cd == pnr.dest_cd)):
            pnr.booked_multi_leg = False
            
            # The flight ORIGINALLY consisted of one leg!
            ## Therefore the "ideal" arrival and departure times are the same 
            ## As the leg that is missing
            pnr.ideal_dep_dtmz = pnr.dep_dtmz
            pnr.ideal_dep_dtml = pnr.dep_dtml

            pnr.ideal_arr_dtmz = pnr.arr_dtmz
            pnr.ideal_arr_dtml = pnr.arr_dtml
        else:
            pnr.booked_multi_leg = True
            
            # The flight ORIGINALLY did NOT consist of one leg! 
            ## Therefore the "ideal" arrival and departure times are the ones
            ## corresponding to the first taken leg
            pnr.ideal_dep_dtmz = min(selected_pnr["DEP_DTMZ"])
            pnr.ideal_dep_dtml = min(selected_pnr["DEP_DTML"])

            
            pnr.ideal_arr_dtmz = max(selected_pnr["ARR_DTMZ"])
            pnr.ideal_arr_dtml = max(selected_pnr["ARR_DTML"])            


        if len(group) == 1:
            pnr_list_1leg.append(pnr)
            
            # We add an additional attribute that tell us whether or not
            # there are more than 1 cancelled flights in the trip
            pnr.trip_multi_leg = False
        elif len(group) == 2:
            pnr_list_2leg.append(pnr)

            # We add an additional attribute that tell us whether or not
            # there are more than 1 cancelled flights in the trip
            pnr.trip_multi_leg = True
        
        # We save it to the general pnr_list either way
        pnr_list.append(pnr)


print("Number of passengers whose booked trip has 1 leg: ", len(pnr_list_1leg))
print("Number of passengers whose booked trip has 2 legs: ", len(pnr_list_2leg))

#print("Total number of flights: ", len(pnr_list_1leg) + len(pnr_list_2leg))
print("Total number of flights: ", len(pnr_list))

Number of passengers whose booked trip has 1 leg:  13346
Number of passengers whose booked trip has 2 legs:  1750
Total number of flights:  15096

In [85]:
available_flights_df

,DEP_KEY,DEP_DT,ORIG_CD,DEST_CD,FLT_NUM,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ,C_CAP_CNT,C_AUL_CNT,C_PAX_CNT,C_AVAIL_CNT,Y_CAP_CNT,Y_AUL_CNT,Y_PAX_CNT,Y_AVAIL_CNT
0,AZ20271023RHPTPH17919,2027-10-23,RHP,TPH,17919,2027-10-23 22:09:00,2027-10-24 01:37:00,2027-10-24 03:09:00,2027-10-24 06:37:00,16,16,11,5,138,138,117,21
1,AZ20271021RHPTPH17919,2027-10-21,RHP,TPH,17919,2027-10-21 22:09:00,2027-10-22 01:37:00,2027-10-22 03:09:00,2027-10-22 06:37:00,16,16,14,2,144,144,144,0
2,AZ20271024RHPTPH17919,2027-10-24,RHP,TPH,17919,2027-10-24 22:09:00,2027-10-25 01:37:00,2027-10-25 03:09:00,2027-10-25 06:37:00,16,16,13,3,144,144,122,22
3,AZ20271025RHPTPH17919,2027-10-25,RHP,TPH,17919,2027-10-25 22:09:00,2027-10-26 01:37:00,2027-10-26 03:09:00,2027-10-26 06:37:00,16,16,14,2,144,144,111,33
4,AZ20271027RHPTPH17919,2027-10-27,RHP,TPH,17919,2027-10-27 22:09:00,2027-10-28 01:37:00,2027-10-28 03:09:00,2027-10-28 06:37:00,12,12,11,1,114,114,95,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,AZ20271019TPHALN6524,2027-10-19,TPH,ALN,6524,2027-10-20 03:40:00,2027-10-20 06:37:00,2027-10-20 08:40:00,2027-10-20 12:37:00,16,16,16,0,144,144,144,0
3217,AZ20271020TPHALN6524,2027-10-20,TPH,ALN,6524,2027-10-21 03:40:00,2027-10-21 06:37:00,2027-10-21 08:40:00,2027-10-21 12:37:00,16,16,16,0,144,144,145,-1
3218,AZ20271021TPHALN6524,2027-10-21,TPH,ALN,6524,2027-10-22 03:40:00,2027-10-22 06:37:00,2027-10-22 08:40:00,2027-10-22 12:37:00,16,16,16,0,144,144,144,0
3219,AZ20271028TPHALN6524,2027-10-28,TPH,ALN,6524,2027-10-29 03:40:00,2027-10-29 06:37:00,2027-10-29 08:40:00,2027-10-29 12:37:00,16,16,7,9,144,144,87,57
3220,AZ20271023TPHALN6524,2027-10-23,TPH,ALN,6524,2027-10-24 03:40:00,2027-10-24 06:37:00,2027-10-24 08:40:00,2027-10-24 12:37:00,16,16,8,8,144,144,111,33

In [86]:
# We fix the columns to only include minutes
date_columns = ["DEP_DTML", "ARR_DTML", "DEP_DTMZ", "ARR_DTMZ"]

# Convert datetime columns to the correct format
for col in date_columns:
    available_flights_df[col] = pd.to_datetime(available_flights_df[col], errors="coerce", infer_datetime_format=True)
    available_flights_df[col] = available_flights_df[col].dt.strftime("%Y-%m-%d %H:%M")

# Print to check if format is correct
print(available_flights_df[date_columns].head())

           DEP_DTML          ARR_DTML          DEP_DTMZ          ARR_DTMZ
0  2027-10-23 22:09  2027-10-24 01:37  2027-10-24 03:09  2027-10-24 06:37
1  2027-10-21 22:09  2027-10-22 01:37  2027-10-22 03:09  2027-10-22 06:37
2  2027-10-24 22:09  2027-10-25 01:37  2027-10-25 03:09  2027-10-25 06:37
3  2027-10-25 22:09  2027-10-26 01:37  2027-10-26 03:09  2027-10-26 06:37
4  2027-10-27 22:09  2027-10-28 01:37  2027-10-28 03:09  2027-10-28 06:37

UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.

In [87]:
available_flights_df.head()

,DEP_KEY,DEP_DT,ORIG_CD,DEST_CD,FLT_NUM,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ,C_CAP_CNT,C_AUL_CNT,C_PAX_CNT,C_AVAIL_CNT,Y_CAP_CNT,Y_AUL_CNT,Y_PAX_CNT,Y_AVAIL_CNT
0,AZ20271023RHPTPH17919,2027-10-23,RHP,TPH,17919,2027-10-23 22:09,2027-10-24 01:37,2027-10-24 03:09,2027-10-24 06:37,16,16,11,5,138,138,117,21
1,AZ20271021RHPTPH17919,2027-10-21,RHP,TPH,17919,2027-10-21 22:09,2027-10-22 01:37,2027-10-22 03:09,2027-10-22 06:37,16,16,14,2,144,144,144,0
2,AZ20271024RHPTPH17919,2027-10-24,RHP,TPH,17919,2027-10-24 22:09,2027-10-25 01:37,2027-10-25 03:09,2027-10-25 06:37,16,16,13,3,144,144,122,22
3,AZ20271025RHPTPH17919,2027-10-25,RHP,TPH,17919,2027-10-25 22:09,2027-10-26 01:37,2027-10-26 03:09,2027-10-26 06:37,16,16,14,2,144,144,111,33
4,AZ20271027RHPTPH17919,2027-10-27,RHP,TPH,17919,2027-10-27 22:09,2027-10-28 01:37,2027-10-28 03:09,2027-10-28 06:37,12,12,11,1,114,114,95,19

In [88]:
#Available_flights_df = 'data_files/PRMI-DM-AVAILABLE_FLIGHTS.csv'  
#Available_flights_df = pd.read_csv(Available_flights_df)

# Now we create the available_flights list
available_flights = []
for _, row in available_flights_df.iterrows():
    flight = Flight(
        dep_key = row["DEP_KEY"],
        dep_dt = row["DEP_DT"],
        orig_cd = row["ORIG_CD"],
        dest_cd = row["DEST_CD"], 
        flt_num = row["FLT_NUM"], 
        dep_dtml = row["DEP_DTML"], 
        arr_dtml = row["ARR_DTML"], 
        dep_dtmz = row["DEP_DTMZ"], 
        arr_dtmz = row["DEP_DTMZ"],
        c_cap_cnt = row["C_CAP_CNT"],
        c_aul_cnt = row["C_AUL_CNT"],
        c_pax_cnt = row["C_PAX_CNT"],
        c_avail_cnt = row["C_AVAIL_CNT"],
        y_cap_cnt = row["Y_CAP_CNT"],
        y_aul_cnt = row["Y_AUL_CNT"],
        y_pax_cnt = row["Y_PAX_CNT"],
        y_avail_cnt = row["Y_AVAIL_CNT"],
        status = True # Put it as to indicate that the flight is available
        # I am not following too much of the code that was previously shared and kind of doing my own
        # Either wa the status wont be used...
    )
    available_flights.append(flight)

In [89]:
print("Total dataset:")
print("Number of passengers: ", len(pnr_list) )
print("Number of available flights: ", len(available_flights) )

Total dataset:
Number of passengers:  15096
Number of available flights:  3221

## Now we compute the flight search space

In [90]:
## We now compute the possiblities for each origin and destination

flights_out_dic = {}
flights_in_dic = {}
flights_out_in_dic = {}
# This last dictionary contains all the possible two-legged combinations for a given origin and destination
flights_2legs_out_in_dic = {}


# We initialize the dictionaries
orig_keys = available_flights_df["ORIG_CD"].unique()
dest_keys = available_flights_df["DEST_CD"].unique()

for orig_key in orig_keys:
    flights_out_dic[str(orig_key)] = []

for dest_key in dest_keys:
    flights_in_dic[str(dest_key)] = []

# Now we initialize for the one-legged and two-legged "Master" dictionaries
#combinations = list( Available_flights_df.groupby(["ORIG_CD", "DEST_CD"]).groups.keys() ) #WRONG!!!
combinations = list(itertools.product(orig_keys, dest_keys))
for combination in combinations:
    flights_out_in_dic[(str(combination[0]), str(combination[1]))] = []
    flights_2legs_out_in_dic[(str(combination[0]), str(combination[1]))] = []

# Now we fill in the DIRECT dictionaries
for flight in available_flights:
    flights_out_dic[str(flight.orig_cd)].append(flight)
    flights_in_dic[str(flight.dest_cd)].append(flight)
    flights_out_in_dic[( str(flight.orig_cd), str(flight.dest_cd) )].append(flight)

In [91]:
available_flights[0]

Flight 17919 (RHP -> TPH):
  Departure Date: 2027-10-23
  Departure Time (Local): 2027-10-23 22:09, (Zulu): 2027-10-24 03:09
  Arrival Time (Local): 2027-10-24 01:37, (Zulu): 2027-10-24 03:09
  Cabin C: Capacity: 16, Occupied: 16, Passengers: 11, Available: 5
  Cabin Y: Capacity: 138, Occupied: 138, Passengers: 117, Available: 21
  Departure Key: AZ20271023RHPTPH17919

In [92]:
# Now we fill the dictionaries for two-legged flights
for combination in combinations:
    print("COMBINATIONS!!! ***************************")
    print("First flight: {}".format(combination[0]))
    print("Second flight: {}".format(combination[1]))
    first_legs = flights_out_dic[ str(combination[0]) ]
    second_legs = flights_in_dic[ str(combination[1]) ]

    # Now we check each combination
    for first_leg in first_legs:
        for second_leg in second_legs:
            
            # if the first and second leg do not satisfy spatial conditions,
            if (first_leg.dest_cd != second_leg.orig_cd):
                continue
            
            # Now we check time conditions
            first_leg_arr = datetime.strptime(first_leg.arr_dtmz, "%Y-%m-%d %H:%M")
            second_leg_dep = datetime.strptime(second_leg.dep_dtmz, "%Y-%m-%d %H:%M")
            conn_time = (second_leg_dep - first_leg_arr).total_seconds() / 60.0    

            ## if the connection time is too low or the connection time is too high
            ### Minimum 60 minutes of time and maximum 12 hours of connection time
            if ((conn_time <= 60) or (720 <= conn_time)):
                continue
            else:
                flights_2legs_out_in_dic[(str(combination[0]), str(combination[1]))].append( (first_leg, second_leg) )
                #print(r"Two-legged valid!! from {} to {}".format(combination[0], combination[1]) )
                #print("Combination: ", (first_leg.dep_key, second_leg.dep_key))
                


print("Flight inventories finished!!! ")

COMBINATIONS!!! ***************************
First flight: RHP
Second flight: TPH
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: NWY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: JDP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: QXG
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: TZJ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: OSW
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: OVS
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: NAD
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: VUY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RBR
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: IPF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: ERW
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: HHO
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: ALN
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: YNZ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RHP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: AIO
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: EYF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: BPJ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RJD
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: EID
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: MHI
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: PJY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: BJH
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: ZFM
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: CEF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: QRD
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: PSX
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: PTP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RIU
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: CHC
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: IJA
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: LIZ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: ZRR
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: QHP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: DFP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: PGM
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: BJQ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: BNF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: CIA
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: AGQ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: KHR
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: SIQ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: GIW
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RCV
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: XBY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: EBG
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: RZD
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: WKC
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: VLL
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: ECZ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: XTA
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: KHL
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: VRP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: OZG
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: XDP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: AUV
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: VCF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: IBA
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: OYC
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: IDK
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: FHY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: FSG
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: GCH
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: VKO
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: KUF
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: CUY
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: FNX
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: WTE
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: OLT
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: BAZ
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: WCD
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: QLX
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: LME
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: LRM
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: NMK
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: CLT
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: AEB
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: HIP
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: IRN
COMBINATIONS!!! ***************************
First flight: RHP
Second flight: LXO
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: TPH
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: NWY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: JDP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: QXG
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: TZJ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: OSW
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: OVS
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: NAD
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: VUY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RBR
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: IPF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: ERW
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: HHO
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: ALN
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: YNZ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RHP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: AIO
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: EYF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: BPJ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RJD
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: EID
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: MHI
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: PJY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: BJH
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: ZFM
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: CEF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: QRD
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: PSX
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: PTP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RIU
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: CHC
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: IJA
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: LIZ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: ZRR
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: QHP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: DFP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: PGM
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: BJQ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: BNF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: CIA
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: AGQ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: KHR
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: SIQ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: GIW
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RCV
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: XBY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: EBG
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: RZD
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: WKC
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: VLL
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: ECZ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: XTA
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: KHL
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: VRP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: OZG
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: XDP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: AUV
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: VCF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: IBA
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: OYC
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: IDK
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: FHY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: FSG
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: GCH
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: VKO
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: KUF
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: CUY
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: FNX
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: WTE
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: OLT
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: BAZ
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: WCD
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: QLX
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: LME
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: LRM
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: NMK
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: CLT
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: AEB
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: HIP
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: IRN
COMBINATIONS!!! ***************************
First flight: JDP
Second flight: LXO
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: TPH
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: NWY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: JDP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: QXG
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: TZJ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: OSW
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: OVS
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: NAD
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: VUY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RBR
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: IPF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: ERW
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: HHO
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: ALN
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: YNZ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RHP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: AIO
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: EYF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: BPJ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RJD
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: EID
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: MHI
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: PJY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: BJH
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: ZFM
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: CEF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: QRD
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: PSX
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: PTP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RIU
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: CHC
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: IJA
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: LIZ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: ZRR
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: QHP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: DFP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: PGM
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: BJQ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: BNF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: CIA
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: AGQ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: KHR
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: SIQ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: GIW
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RCV
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: XBY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: EBG
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: RZD
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: WKC
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: VLL
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: ECZ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: XTA
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: KHL
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: VRP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: OZG
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: XDP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: AUV
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: VCF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: IBA
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: OYC
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: IDK
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: FHY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: FSG
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: GCH
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: VKO
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: KUF
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: CUY
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: FNX
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: WTE
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: OLT
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: BAZ
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: WCD
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: QLX
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: LME
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: LRM
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: NMK
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: CLT
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: AEB
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: HIP
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: IRN
COMBINATIONS!!! ***************************
First flight: TPH
Second flight: LXO
COMBINATIONS!!! ***************************
First flight: ECZ
Second flight: TPH
COMBINATIONS!!! ***************************
First flight: ECZ
Second flight: NWY
COMBINATIONS!!! ***************************
First flight: ECZ
Second flight: JDP
COMBINATIONS!!! ***************************
First flight: ECZ

In [93]:
total_single_flights = 0
for key in flights_out_in_dic:
    total_single_flights = total_single_flights + len( flights_out_in_dic[key] )

print("Total flights for one leg: ", total_single_flights)

Total flights for one leg:  3221

In [94]:
total_double_flights = 0
for key in flights_2legs_out_in_dic:
    total_double_flights = total_double_flights + len( flights_2legs_out_in_dic[key] )

print("Total flights for two leg: ", total_double_flights)

Total flights for two leg:  129649

In [95]:
print("Total number of flight variables: ", total_single_flights + total_double_flights)

Total number of flight variables:  132870

In [96]:
len(pnr_list)

15096

In [97]:
print("Total number of possible variables: ", len(pnr_list) * (total_single_flights + total_double_flights) )

Total number of possible variables:  2005805520

raise Exception("Stopping execution here")

In [98]:
## We now define the time penalty computation, 
#### The leg_penalty variable is for us to add to multi-legt flights
#### Those will have a high leg_penalty, as we prefer direct flights
def time_penalty(time_difference: float) -> float:
        if time_difference < 0:
            return -10000
        elif time_difference <= 360:
            #return (70 - time_difference)
            return 70
        elif time_difference <= 720:
            #return (50 - time_difference)
            return 50
        elif time_difference <= 1440:
            #return (40 - time_difference)
            return 40
        elif time_difference <= 2880:
            #return (30 - time_difference)
            return 30
        else:
            return -10000

In [99]:
def negative_time_penalty(time_difference: float) -> float:
        if time_difference < 0:
            return 10000
        elif time_difference <= 360:
            #return (70 - time_difference)
            return -70
        elif time_difference <= 720:
            #return (50 - time_difference)
            return -50
        elif time_difference <= 1440:
            #return (40 - time_difference)
            return -40
        elif time_difference <= 2880:
            #return (30 - time_difference)
            return -30
        else:
            return 10000

In [100]:
# We add costs for the CVM variables

one_one_cost = 25
one_multi_cost = int(15)
multi_one_cost = int(20)
multi_multi_cost = int(10)

# Factor to include in the computation of the cvm!
cvm_factor = {}
cvm_factor["one_one"] = int(25)
cvm_factor["one_multi"] = int(15)
cvm_factor["multi_one"] = int(20)
cvm_factor["multi_multi"] = int(10)
cvm_factor["forced_one"] = int(30)

# To change this cost, depending on the feedback that we obtain
forced_one_cost = 30
## Different penalties for each proposed solution

In [101]:
n_variables = 0
n_one_one = 0
n_one_multi = 0
n_multi_multi = 0
n_multi_one = 0
n_forced_one = 0

In [102]:
print(" ¡Setting seach space! ")

#pnr_list = pnr_list[0:2]
#pnr_list = pnr_list[0:len(pnr_list)//135]

#available_flights = available_flights[0:10]

print("Reduced dataset: ")
print("Number of passengers: ", len(pnr_list) )
print("Number of available flights: ", len(available_flights) )

 ¡Setting seach space!
Reduced dataset:
Number of passengers:  15096
Number of available flights:  3221

In [103]:
## Now we create the dictionaries! 
# For local constraints
flights_per_passenger = {}
# For seat constraints!
passengers_per_flight = {}

# We initialize / initialise the variables_per_flight dictionary
for flight in available_flights:
    passengers_per_flight[str(flight.dep_key)] = {}
    passengers_per_flight[str(flight.dep_key)]["one_one"] = []
    passengers_per_flight[str(flight.dep_key)]["forced_one"] = []
    passengers_per_flight[str(flight.dep_key)]["one_multi"] = []
    passengers_per_flight[str(flight.dep_key)]["multi_one"] = []
    passengers_per_flight[str(flight.dep_key)]["multi_multi"] = []

In [104]:
general_dic = {}
general_dic["variables"] = []
general_dic["values"] = []
general_dic["pax_cnt"] = []
general_dic["avail_cnt"] = []

## Now we do different fors for the cases

In [105]:
import copy 

print("Setting up the dictionary!")
for passenger in pnr_list:
    #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))] = general_dic
    #variables_per_passenger[str(passenger.trip_id)] = copy.deepcopy(general_dic)
    flights_per_passenger[str(passenger.trip_id)] = {}
    
    flights_per_passenger[str(passenger.trip_id)]["one_one"] = copy.deepcopy(general_dic)
    flights_per_passenger[str(passenger.trip_id)]["forced_one"] = copy.deepcopy(general_dic)
    flights_per_passenger[str(passenger.trip_id)]["multi_one"] = copy.deepcopy(general_dic)
    flights_per_passenger[str(passenger.trip_id)]["one_multi"] = copy.deepcopy(general_dic)
    flights_per_passenger[str(passenger.trip_id)]["multi_multi"] = copy.deepcopy(general_dic)

Setting up the dictionary!

## One-one case

In [106]:
for passenger in pnr_list:
    #print("(Passenger, trip number): ", (passenger.recloc, passenger.trip_number[0]), "/", len(pnr_list))
    #print("Passenger trip id: ", passenger.trip_id)
    
    if (not passenger.booked_multi_leg):
        available_flights_case = flights_out_in_dic[ (str(passenger.orig_cd), str(passenger.dest_cd)) ]
        
        # Now we iterate over all possible case
        for flight in available_flights_case:

            # Retrieve the new time departures
            new_time_dep = datetime.strptime(flight.dep_dtmz, "%Y-%m-%d %H:%M")  # flight time does include seconds
            new_time_arr = datetime.strptime(flight.arr_dtmz, "%Y-%m-%d %H:%M") 
            
            # Retrieve the original time departures
            orig_time_dep = datetime.strptime(passenger.dep_dtmz, "%Y-%m-%d %H:%M")
            orig_time_arr = datetime.strptime(passenger.arr_dtmz, "%Y-%m-%d %H:%M")
                
            time_diff_dep = ((new_time_dep - orig_time_dep).total_seconds() / 60.0) # Minutes
            time_diff_arr = ((new_time_arr - orig_time_arr).total_seconds() / 60.0) 

            cost_dep = time_penalty(time_diff_dep)
            cost_arr = time_penalty(time_diff_arr)

            # Is this a good pairing?
            if ((cost_dep <= 0) or (cost_arr <= 0)): # Check the penalty
                #  We do not add an energy for this flight, the flight is already terrible!
                continue 
            else:
                var_cost = cost_dep + cost_arr + cvm_factor["one_one"]*passenger.cvm
                
                # We save the variable

                # We save the assigned DIRECT flight for this passenger
                #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))]["one_one"].append( var )
                flights_per_passenger[str(passenger.trip_id)]["one_one"]["variables"].append((passenger.trip_id, flight.dep_key) )
                flights_per_passenger[str(passenger.trip_id)]["one_one"]["values"].append(var_cost)
                flights_per_passenger[str(passenger.trip_id)]["one_one"]["pax_cnt"].append(passenger.pax_cnt)
                flights_per_passenger[str(passenger.trip_id)]["one_one"]["avail_cnt"].append(flight.c_avail_cnt + flight.y_avail_cnt)

                # We add the assigned flight to be dictionary saving the global variables
                passengers_per_flight[flight.dep_key]["one_one"].append( ((passenger.trip_id, flight.dep_key), passenger.pax_cnt) )

                # We increment the number of total variables
                n_variables = n_variables + 1
                n_one_one = n_one_one + 1

## Forced one case

In [107]:
for passenger in pnr_list:
    print("(Passenger, trip number): ", (passenger.recloc, passenger.trip_number[0]), "/", len(pnr_list))
    
    if (passenger.booked_multi_leg):
        available_flights_case = flights_out_in_dic[ (str(passenger.oper_od_orig_cd), str(passenger.oper_od_dest_cd)) ]
        
        # Now we iterate over all possible case
        for flight in available_flights_case:

            # Retrieve the new time departures
            new_time_dep = datetime.strptime(flight.dep_dtmz, "%Y-%m-%d %H:%M")  # flight time does include seconds
            new_time_arr = datetime.strptime(flight.arr_dtmz, "%Y-%m-%d %H:%M") 
            
            # Retrieve the original time departures
            orig_time_dep = datetime.strptime(passenger.ideal_dep_dtmz, "%Y-%m-%d %H:%M")
            orig_time_arr = datetime.strptime(passenger.ideal_arr_dtmz, "%Y-%m-%d %H:%M")
                
            time_diff_dep = ((new_time_dep - orig_time_dep).total_seconds() / 60.0) # Minutes
            time_diff_arr = ((new_time_arr - orig_time_arr).total_seconds() / 60.0) 

            cost_dep = time_penalty(time_diff_dep)
            cost_arr = time_penalty(time_diff_arr)

            # Is this a good pairing?
            if ((cost_dep <= 0) or (cost_arr <= 0)): # Check the penalty
                #  We do not add an energy for this flight, the flight is already terrible!
                continue 
            else:
                var_cost = cost_dep + cost_arr + cvm_factor["forced_one"]*passenger.cvm
                
                # We save the variable

                # We save the assigned DIRECT flight for this passenger
                #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))]["one_one"].append( var )
                flights_per_passenger[str(passenger.trip_id)]["forced_one"]["variables"].append((passenger.trip_id, flight.dep_key) )
                flights_per_passenger[str(passenger.trip_id)]["forced_one"]["values"].append(var_cost)
                flights_per_passenger[str(passenger.trip_id)]["forced_one"]["pax_cnt"].append(passenger.pax_cnt)
                flights_per_passenger[str(passenger.trip_id)]["forced_one"]["avail_cnt"].append(flight.c_avail_cnt + flight.y_avail_cnt)

                # We add the assigned flight to be dictionary saving the global variables
                passengers_per_flight[flight.dep_key]["forced_one"].append( ((passenger.trip_id, flight.dep_key), passenger.pax_cnt) )

                # We increment the number of total variables
                n_variables = n_variables + 1
                n_forced_one = n_forced_one + 1

(Passenger, trip number):  (0, 1) / 15096
(Passenger, trip number):  (1, 1) / 15096
(Passenger, trip number):  (2, 1) / 15096
(Passenger, trip number):  (3, 2) / 15096
(Passenger, trip number):  (4, 1) / 15096
(Passenger, trip number):  (5, 2) / 15096
(Passenger, trip number):  (6, 2) / 15096
(Passenger, trip number):  (7, 2) / 15096
(Passenger, trip number):  (8, 2) / 15096
(Passenger, trip number):  (9, 1) / 15096
(Passenger, trip number):  (10, 1) / 15096
(Passenger, trip number):  (11, 1) / 15096
(Passenger, trip number):  (12, 2) / 15096
(Passenger, trip number):  (13, 1) / 15096
(Passenger, trip number):  (14, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (16, 1) / 15096
(Passenger, trip number):  (17, 1) / 15096
(Passenger, trip number):  (18, 1) / 15096
(Passenger, trip number):  (19, 1) / 15096
(Passenger, trip number):  (20, 1) / 15096
(Passenger, trip number):  (21, 1) / 15096
(Passenger, trip number):  (22, 1) / 15096
(Passenger, trip number):  (23, 1) / 15096
(Passenger, trip number):  (24, 1) / 15096
(Passenger, trip number):  (25, 1) / 15096
(Passenger, trip number):  (26, 2) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (28, 1) / 15096
(Passenger, trip number):  (29, 1) / 15096
(Passenger, trip number):  (30, 2) / 15096
(Passenger, trip number):  (31, 2) / 15096
(Passenger, trip number):  (32, 1) / 15096
(Passenger, trip number):  (33, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (35, 2) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (37, 2) / 15096
(Passenger, trip number):  (38, 1) / 15096
(Passenger, trip number):  (39, 1) / 15096
(Passenger, trip number):  (40, 2) / 15096
(Passenger, trip number):  (41, 1) / 15096
(Passenger, trip number):  (42, 2) / 15096
(Passenger, trip number):  (43, 2) / 15096
(Passenger, trip number):  (44, 1) / 15096
(Passenger, trip number):  (45, 1) / 15096
(Passenger, trip number):  (46, 2) / 15096
(Passenger, trip number):  (47, 1) / 15096
(Passenger, trip number):  (48, 1) / 15096
(Passenger, trip number):  (49, 1) / 15096
(Passenger, trip number):  (50, 1) / 15096
(Passenger, trip number):  (51, 1) / 15096
(Passenger, trip number):  (52, 2) / 15096
(Passenger, trip number):  (53, 1) / 15096
(Passenger, trip number):  (54, 1) / 15096
(Passenger, trip number):  (55, 1) / 15096
(Passenger, trip number):  (56, 2) / 15096
(Passenger, trip number):  (57, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (59, 1) / 15096
(Passenger, trip number):  (60, 1) / 15096
(Passenger, trip number):  (61, 1) / 15096
(Passenger, trip number):  (62, 1) / 15096
(Passenger, trip number):  (63, 2) / 15096
(Passenger, trip number):  (64, 2) / 15096
(Passenger, trip number):  (65, 2) / 15096
(Passenger, trip number):  (66, 1) / 15096
(Passenger, trip number):  (67, 1) / 15096
(Passenger, trip number):  (68, 1) / 15096
(Passenger, trip number):  (69, 1) / 15096
(Passenger, trip number):  (70, 2) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (72, 1) / 15096
(Passenger, trip number):  (73, 1) / 15096
(Passenger, trip number):  (74, 2) / 15096
(Passenger, trip number):  (75, 2) / 15096
(Passenger, trip number):  (76, 2) / 15096
(Passenger, trip number):  (77, 1) / 15096
(Passenger, trip number):  (78, 2) / 15096
(Passenger, trip number):  (79, 1) / 15096
(Passenger, trip number):  (80, 1) / 15096
(Passenger, trip number):  (81, 2) / 15096
(Passenger, trip number):  (82, 2) / 15096
(Passenger, trip number):  (83, 2) / 15096
(Passenger, trip number):  (84, 1) / 15096
(Passenger, trip number):  (85, 2) / 15096
(Passenger, trip number):  (86, 2) / 15096
(Passenger, trip number):  (87, 1) / 15096
(Passenger, trip number):  (88, 2) / 15096
(Passenger, trip number):  (89, 1) / 15096
(Passenger, trip number):  (90, 1) / 15096
(Passenger, trip number):  (91, 1) / 15096
(Passenger, trip number):  (92, 1) / 15096
(Passenger, trip number):  (93, 2) / 15096
(Passenger, trip number):  (94, 1) / 15096
(Passenger, trip number):  (95, 2) / 15096
(Passenger, trip number):  (96, 2) / 15096
(Passenger, trip number):  (97, 1) / 15096
(Passenger, trip number):  (98, 1) / 15096
(Passenger, trip number):  (98, 2) / 15096
(Passenger, trip number):  (99, 2) / 15096
(Passenger, trip number):  (100, 1) / 15096
(Passenger, trip number):  (101, 2) / 15096
(Passenger, trip number):  (102, 2) / 15096
(Passenger, trip number):  (103, 1) / 15096
(Passenger, trip number):  (104, 1) / 15096
(Passenger, trip number):  (105, 1) / 15096
(Passenger, trip number):  (106, 1) / 15096
(Passenger, trip number):  (107, 2) / 15096
(Passenger, trip number):  (108, 2) / 15096
(Passenger, trip number):  (109, 1) / 15096
(Passenger, trip number):  (110, 2) / 15096
(Passenger, trip number):  (111, 1) / 15096
(Passenger, trip number):  (112, 2) / 15096
(Passenger, trip number):  (113, 2) / 15096
(Passenger, trip number):  (114, 2) / 15096
(Passenger, trip number):  (115, 1) / 15096
(Passenger, trip number):  (116, 1) / 15096
(Passenger, trip number):  (117, 1) / 15096
(Passenger, trip number):  (118, 2) / 15096
(Passenger, trip number):  (119, 2) / 15096
(Passenger, trip number):  (120, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (122, 1) / 15096
(Passenger, trip number):  (123, 1) / 15096
(Passenger, trip number):  (124, 1) / 15096
(Passenger, trip number):  (125, 1) / 15096
(Passenger, trip number):  (126, 2) / 15096
(Passenger, trip number):  (127, 1) / 15096
(Passenger, trip number):  (128, 1) / 15096
(Passenger, trip number):  (129, 2) / 15096
(Passenger, trip number):  (130, 2) / 15096
(Passenger, trip number):  (131, 3) / 15096
(Passenger, trip number):  (132, 1) / 15096
(Passenger, trip number):  (133, 1) / 15096
(Passenger, trip number):  (134, 1) / 15096
(Passenger, trip number):  (135, 1) / 15096
(Passenger, trip number):  (136, 1) / 15096
(Passenger, trip number):  (137, 1) / 15096
(Passenger, trip number):  (138, 2) / 15096
(Passenger, trip number):  (139, 1) / 15096
(Passenger, trip number):  (140, 1) / 15096
(Passenger, trip number):  (141, 1) / 15096
(Passenger, trip number):  (142, 1) / 15096
(Passenger, trip number):  (143, 1) / 15096
(Passenger, trip number):  (144, 1) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (146, 1) / 15096
(Passenger, trip number):  (147, 2) / 15096
(Passenger, trip number):  (148, 2) / 15096
(Passenger, trip number):  (149, 2) / 15096
(Passenger, trip number):  (150, 2) / 15096
(Passenger, trip number):  (151, 1) / 15096
(Passenger, trip number):  (152, 2) / 15096
(Passenger, trip number):  (153, 2) / 15096
(Passenger, trip number):  (154, 2) / 15096
(Passenger, trip number):  (155, 1) / 15096
(Passenger, trip number):  (156, 1) / 15096
(Passenger, trip number):  (157, 1) / 15096
(Passenger, trip number):  (158, 1) / 15096
(Passenger, trip number):  (159, 1) / 15096
(Passenger, trip number):  (160, 2) / 15096
(Passenger, trip number):  (161, 1) / 15096
(Passenger, trip number):  (162, 1) / 15096
(Passenger, trip number):  (163, 2) / 15096
(Passenger, trip number):  (164, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (166, 1) / 15096
(Passenger, trip number):  (167, 2) / 15096
(Passenger, trip number):  (168, 2) / 15096
(Passenger, trip number):  (169, 1) / 15096
(Passenger, trip number):  (170, 2) / 15096
(Passenger, trip number):  (171, 2) / 15096
(Passenger, trip number):  (172, 1) / 15096
(Passenger, trip number):  (173, 2) / 15096
(Passenger, trip number):  (174, 2) / 15096
(Passenger, trip number):  (175, 2) / 15096
(Passenger, trip number):  (176, 2) / 15096
(Passenger, trip number):  (177, 2) / 15096
(Passenger, trip number):  (178, 2) / 15096
(Passenger, trip number):  (179, 1) / 15096
(Passenger, trip number):  (180, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (182, 2) / 15096
(Passenger, trip number):  (183, 1) / 15096
(Passenger, trip number):  (184, 2) / 15096
(Passenger, trip number):  (185, 1) / 15096
(Passenger, trip number):  (186, 1) / 15096
(Passenger, trip number):  (187, 1) / 15096
(Passenger, trip number):  (188, 1) / 15096
(Passenger, trip number):  (189, 1) / 15096
(Passenger, trip number):  (190, 1) / 15096
(Passenger, trip number):  (191, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (193, 1) / 15096
(Passenger, trip number):  (194, 1) / 15096
(Passenger, trip number):  (195, 1) / 15096
(Passenger, trip number):  (196, 2) / 15096
(Passenger, trip number):  (197, 2) / 15096
(Passenger, trip number):  (198, 1) / 15096
(Passenger, trip number):  (199, 1) / 15096
(Passenger, trip number):  (200, 3) / 15096
(Passenger, trip number):  (201, 2) / 15096
(Passenger, trip number):  (202, 2) / 15096
(Passenger, trip number):  (203, 1) / 15096
(Passenger, trip number):  (204, 2) / 15096
(Passenger, trip number):  (205, 2) / 15096
(Passenger, trip number):  (206, 1) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (208, 1) / 15096
(Passenger, trip number):  (209, 1) / 15096
(Passenger, trip number):  (210, 2) / 15096
(Passenger, trip number):  (211, 1) / 15096
(Passenger, trip number):  (212, 2) / 15096
(Passenger, trip number):  (213, 2) / 15096
(Passenger, trip number):  (214, 1) / 15096
(Passenger, trip number):  (215, 1) / 15096
(Passenger, trip number):  (216, 2) / 15096
(Passenger, trip number):  (217, 2) / 15096
(Passenger, trip number):  (218, 2) / 15096
(Passenger, trip number):  (219, 1) / 15096
(Passenger, trip number):  (220, 2) / 15096
(Passenger, trip number):  (221, 2) / 15096
(Passenger, trip number):  (222, 1) / 15096
(Passenger, trip number):  (223, 2) / 15096
(Passenger, trip number):  (224, 1) / 15096
(Passenger, trip number):  (225, 1) / 15096
(Passenger, trip number):  (226, 1) / 15096
(Passenger, trip number):  (227, 2) / 15096
(Passenger, trip number):  (228, 1) / 15096
(Passenger, trip number):  (229, 1) / 15096
(Passenger, trip number):  (230, 1) / 15096
(Passenger, trip number):  (231, 2) / 15096
(Passenger, trip number):  (232, 2) / 15096
(Passenger, trip number):  (233, 2) / 15096
(Passenger, trip number):  (234, 1) / 15096
(Passenger, trip number):  (235, 1) / 15096
(Passenger, trip number):  (236, 1) / 15096
(Passenger, trip number):  (237, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (239, 1) / 15096
(Passenger, trip number):  (240, 1) / 15096
(Passenger, trip number):  (241, 1) / 15096
(Passenger, trip number):  (242, 1) / 15096
(Passenger, trip number):  (243, 1) / 15096
(Passenger, trip number):  (244, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (246, 1) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (248, 1) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (251, 1) / 15096
(Passenger, trip number):  (252, 2) / 15096
(Passenger, trip number):  (253, 2) / 15096
(Passenger, trip number):  (254, 1) / 15096
(Passenger, trip number):  (255, 1) / 15096
(Passenger, trip number):  (256, 2) / 15096
(Passenger, trip number):  (257, 2) / 15096
(Passenger, trip number):  (258, 2) / 15096
(Passenger, trip number):  (259, 1) / 15096
(Passenger, trip number):  (260, 1) / 15096
(Passenger, trip number):  (261, 2) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (263, 3) / 15096
(Passenger, trip number):  (264, 1) / 15096
(Passenger, trip number):  (265, 1) / 15096
(Passenger, trip number):  (266, 2) / 15096
(Passenger, trip number):  (267, 1) / 15096
(Passenger, trip number):  (268, 2) / 15096
(Passenger, trip number):  (269, 2) / 15096
(Passenger, trip number):  (270, 2) / 15096
(Passenger, trip number):  (271, 1) / 15096
(Passenger, trip number):  (272, 2) / 15096
(Passenger, trip number):  (273, 1) / 15096
(Passenger, trip number):  (274, 1) / 15096
(Passenger, trip number):  (275, 2) / 15096
(Passenger, trip number):  (276, 1) / 15096
(Passenger, trip number):  (277, 1) / 15096
(Passenger, trip number):  (278, 3) / 15096
(Passenger, trip number):  (279, 2) / 15096
(Passenger, trip number):  (280, 1) / 15096
(Passenger, trip number):  (281, 2) / 15096
(Passenger, trip number):  (282, 1) / 15096
(Passenger, trip number):  (283, 1) / 15096
(Passenger, trip number):  (284, 1) / 15096
(Passenger, trip number):  (285, 1) / 15096
(Passenger, trip number):  (286, 2) / 15096
(Passenger, trip number):  (287, 1) / 15096
(Passenger, trip number):  (288, 1) / 15096
(Passenger, trip number):  (289, 2) / 15096
(Passenger, trip number):  (290, 1) / 15096
(Passenger, trip number):  (291, 1) / 15096
(Passenger, trip number):  (292, 2) / 15096
(Passenger, trip number):  (293, 2) / 15096
(Passenger, trip number):  (294, 2) / 15096
(Passenger, trip number):  (295, 2) / 15096
(Passenger, trip number):  (296, 2) / 15096
(Passenger, trip number):  (297, 1) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (299, 2) / 15096
(Passenger, trip number):  (300, 1) / 15096
(Passenger, trip number):  (301, 2) / 15096
(Passenger, trip number):  (302, 2) / 15096
(Passenger, trip number):  (303, 2) / 15096
(Passenger, trip number):  (304, 1) / 15096
(Passenger, trip number):  (305, 1) / 15096
(Passenger, trip number):  (306, 1) / 15096
(Passenger, trip number):  (307, 1) / 15096
(Passenger, trip number):  (308, 1) / 15096
(Passenger, trip number):  (309, 2) / 15096
(Passenger, trip number):  (310, 2) / 15096
(Passenger, trip number):  (311, 2) / 15096
(Passenger, trip number):  (312, 1) / 15096
(Passenger, trip number):  (313, 2) / 15096
(Passenger, trip number):  (314, 2) / 15096
(Passenger, trip number):  (315, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (317, 2) / 15096
(Passenger, trip number):  (318, 2) / 15096
(Passenger, trip number):  (319, 2) / 15096
(Passenger, trip number):  (320, 2) / 15096
(Passenger, trip number):  (321, 1) / 15096
(Passenger, trip number):  (322, 2) / 15096
(Passenger, trip number):  (323, 1) / 15096
(Passenger, trip number):  (324, 1) / 15096
(Passenger, trip number):  (325, 1) / 15096
(Passenger, trip number):  (326, 2) / 15096
(Passenger, trip number):  (327, 2) / 15096
(Passenger, trip number):  (328, 1) / 15096
(Passenger, trip number):  (329, 1) / 15096
(Passenger, trip number):  (330, 2) / 15096
(Passenger, trip number):  (331, 1) / 15096
(Passenger, trip number):  (332, 2) / 15096
(Passenger, trip number):  (333, 1) / 15096
(Passenger, trip number):  (334, 1) / 15096
(Passenger, trip number):  (335, 1) / 15096
(Passenger, trip number):  (336, 2) / 15096
(Passenger, trip number):  (337, 1) / 15096
(Passenger, trip number):  (338, 1) / 15096
(Passenger, trip number):  (339, 1) / 15096
(Passenger, trip number):  (340, 2) / 15096
(Passenger, trip number):  (341, 2) / 15096
(Passenger, trip number):  (342, 2) / 15096
(Passenger, trip number):  (343, 1) / 15096
(Passenger, trip number):  (344, 1) / 15096
(Passenger, trip number):  (345, 1) / 15096
(Passenger, trip number):  (346, 2) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (349, 2) / 15096
(Passenger, trip number):  (350, 1) / 15096
(Passenger, trip number):  (351, 1) / 15096
(Passenger, trip number):  (352, 2) / 15096
(Passenger, trip number):  (353, 1) / 15096
(Passenger, trip number):  (354, 1) / 15096
(Passenger, trip number):  (355, 1) / 15096
(Passenger, trip number):  (356, 1) / 15096
(Passenger, trip number):  (357, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (359, 3) / 15096
(Passenger, trip number):  (360, 1) / 15096
(Passenger, trip number):  (361, 2) / 15096
(Passenger, trip number):  (362, 1) / 15096
(Passenger, trip number):  (363, 1) / 15096
(Passenger, trip number):  (364, 2) / 15096
(Passenger, trip number):  (365, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (367, 2) / 15096
(Passenger, trip number):  (368, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (370, 1) / 15096
(Passenger, trip number):  (371, 2) / 15096
(Passenger, trip number):  (372, 1) / 15096
(Passenger, trip number):  (373, 2) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (375, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (377, 1) / 15096
(Passenger, trip number):  (378, 1) / 15096
(Passenger, trip number):  (379, 2) / 15096
(Passenger, trip number):  (380, 2) / 15096
(Passenger, trip number):  (381, 2) / 15096
(Passenger, trip number):  (382, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (384, 1) / 15096
(Passenger, trip number):  (385, 1) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (387, 1) / 15096
(Passenger, trip number):  (388, 1) / 15096
(Passenger, trip number):  (389, 1) / 15096
(Passenger, trip number):  (390, 1) / 15096
(Passenger, trip number):  (391, 1) / 15096
(Passenger, trip number):  (392, 1) / 15096
(Passenger, trip number):  (393, 1) / 15096
(Passenger, trip number):  (394, 1) / 15096
(Passenger, trip number):  (395, 1) / 15096
(Passenger, trip number):  (396, 1) / 15096
(Passenger, trip number):  (397, 2) / 15096
(Passenger, trip number):  (398, 1) / 15096
(Passenger, trip number):  (399, 1) / 15096
(Passenger, trip number):  (400, 2) / 15096
(Passenger, trip number):  (401, 2) / 15096
(Passenger, trip number):  (402, 2) / 15096
(Passenger, trip number):  (403, 1) / 15096
(Passenger, trip number):  (404, 1) / 15096
(Passenger, trip number):  (405, 1) / 15096
(Passenger, trip number):  (406, 2) / 15096
(Passenger, trip number):  (407, 1) / 15096
(Passenger, trip number):  (408, 1) / 15096
(Passenger, trip number):  (409, 1) / 15096
(Passenger, trip number):  (410, 1) / 15096
(Passenger, trip number):  (411, 1) / 15096
(Passenger, trip number):  (412, 1) / 15096
(Passenger, trip number):  (413, 1) / 15096
(Passenger, trip number):  (414, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (416, 1) / 15096
(Passenger, trip number):  (417, 1) / 15096
(Passenger, trip number):  (418, 1) / 15096
(Passenger, trip number):  (419, 1) / 15096
(Passenger, trip number):  (420, 1) / 15096
(Passenger, trip number):  (421, 2) / 15096
(Passenger, trip number):  (422, 2) / 15096
(Passenger, trip number):  (423, 1) / 15096
(Passenger, trip number):  (424, 2) / 15096
(Passenger, trip number):  (425, 3) / 15096

## Multi-one case

In [108]:
for passenger in pnr_list:
    print("(Passenger, trip number): ", (passenger.recloc, passenger.trip_number[0]), "/", len(pnr_list))
    
    if (passenger.booked_multi_leg):
        available_flights_case = flights_out_in_dic[ (str(passenger.orig_cd), str(passenger.dest_cd)) ]
        
        # Now we iterate over all possible case
        for flight in available_flights_case:

            # Retrieve the new time departures
            new_time_dep = datetime.strptime(flight.dep_dtmz, "%Y-%m-%d %H:%M")  # flight time does include seconds
            new_time_arr = datetime.strptime(flight.arr_dtmz, "%Y-%m-%d %H:%M") 
            
            # Retrieve the original time departures
            orig_time_dep = datetime.strptime(passenger.dep_dtmz, "%Y-%m-%d %H:%M")
            orig_time_arr = datetime.strptime(passenger.arr_dtmz, "%Y-%m-%d %H:%M")
                
            time_diff_dep = ((new_time_dep - orig_time_dep).total_seconds() / 60.0) # Minutes
            time_diff_arr = ((new_time_arr - orig_time_arr).total_seconds() / 60.0) 

            cost_dep = time_penalty(time_diff_dep)
            cost_arr = time_penalty(time_diff_arr)

            # Is this a good pairing?
            if ((cost_dep <= 0) or (cost_arr <= 0)): # Check the penalty
                #  We do not add an energy for this flight, the flight is already terrible!
                continue 
            else:
                var_cost = cost_dep + cost_arr + cvm_factor["multi_one"]*passenger.cvm
                
                # We save the variable

                # We save the assigned DIRECT flight for this passenger
                #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))]["one_one"].append( var )
                flights_per_passenger[str(passenger.trip_id)]["multi_one"]["variables"].append((passenger.trip_id, flight.dep_key) )
                flights_per_passenger[str(passenger.trip_id)]["multi_one"]["values"].append(var_cost)
                flights_per_passenger[str(passenger.trip_id)]["multi_one"]["pax_cnt"].append(passenger.pax_cnt)
                flights_per_passenger[str(passenger.trip_id)]["multi_one"]["avail_cnt"].append(flight.c_avail_cnt + flight.y_avail_cnt)
                

                # We add the assigned flight to be dictionary saving the global variables
                passengers_per_flight[flight.dep_key]["multi_one"].append( ((passenger.trip_id, flight.dep_key), passenger.pax_cnt) )

                # We increment the number of total variables
                n_variables = n_variables + 1
                n_multi_one = n_multi_one + 1

(Passenger, trip number):  (0, 1) / 15096
(Passenger, trip number):  (1, 1) / 15096
(Passenger, trip number):  (2, 1) / 15096
(Passenger, trip number):  (3, 2) / 15096
(Passenger, trip number):  (4, 1) / 15096
(Passenger, trip number):  (5, 2) / 15096
(Passenger, trip number):  (6, 2) / 15096
(Passenger, trip number):  (7, 2) / 15096
(Passenger, trip number):  (8, 2) / 15096
(Passenger, trip number):  (9, 1) / 15096
(Passenger, trip number):  (10, 1) / 15096
(Passenger, trip number):  (11, 1) / 15096
(Passenger, trip number):  (12, 2) / 15096
(Passenger, trip number):  (13, 1) / 15096
(Passenger, trip number):  (14, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (16, 1) / 15096
(Passenger, trip number):  (17, 1) / 15096
(Passenger, trip number):  (18, 1) / 15096
(Passenger, trip number):  (19, 1) / 15096
(Passenger, trip number):  (20, 1) / 15096
(Passenger, trip number):  (21, 1) / 15096
(Passenger, trip number):  (22, 1) / 15096
(Passenger, trip number):  (23, 1) / 15096
(Passenger, trip number):  (24, 1) / 15096
(Passenger, trip number):  (25, 1) / 15096
(Passenger, trip number):  (26, 2) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (28, 1) / 15096
(Passenger, trip number):  (29, 1) / 15096
(Passenger, trip number):  (30, 2) / 15096
(Passenger, trip number):  (31, 2) / 15096
(Passenger, trip number):  (32, 1) / 15096
(Passenger, trip number):  (33, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (35, 2) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (37, 2) / 15096
(Passenger, trip number):  (38, 1) / 15096
(Passenger, trip number):  (39, 1) / 15096
(Passenger, trip number):  (40, 2) / 15096
(Passenger, trip number):  (41, 1) / 15096
(Passenger, trip number):  (42, 2) / 15096
(Passenger, trip number):  (43, 2) / 15096
(Passenger, trip number):  (44, 1) / 15096
(Passenger, trip number):  (45, 1) / 15096
(Passenger, trip number):  (46, 2) / 15096
(Passenger, trip number):  (47, 1) / 15096
(Passenger, trip number):  (48, 1) / 15096
(Passenger, trip number):  (49, 1) / 15096
(Passenger, trip number):  (50, 1) / 15096
(Passenger, trip number):  (51, 1) / 15096
(Passenger, trip number):  (52, 2) / 15096
(Passenger, trip number):  (53, 1) / 15096
(Passenger, trip number):  (54, 1) / 15096
(Passenger, trip number):  (55, 1) / 15096
(Passenger, trip number):  (56, 2) / 15096
(Passenger, trip number):  (57, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (59, 1) / 15096
(Passenger, trip number):  (60, 1) / 15096
(Passenger, trip number):  (61, 1) / 15096
(Passenger, trip number):  (62, 1) / 15096
(Passenger, trip number):  (63, 2) / 15096
(Passenger, trip number):  (64, 2) / 15096
(Passenger, trip number):  (65, 2) / 15096
(Passenger, trip number):  (66, 1) / 15096
(Passenger, trip number):  (67, 1) / 15096
(Passenger, trip number):  (68, 1) / 15096
(Passenger, trip number):  (69, 1) / 15096
(Passenger, trip number):  (70, 2) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (72, 1) / 15096
(Passenger, trip number):  (73, 1) / 15096
(Passenger, trip number):  (74, 2) / 15096
(Passenger, trip number):  (75, 2) / 15096
(Passenger, trip number):  (76, 2) / 15096
(Passenger, trip number):  (77, 1) / 15096
(Passenger, trip number):  (78, 2) / 15096
(Passenger, trip number):  (79, 1) / 15096
(Passenger, trip number):  (80, 1) / 15096
(Passenger, trip number):  (81, 2) / 15096
(Passenger, trip number):  (82, 2) / 15096
(Passenger, trip number):  (83, 2) / 15096
(Passenger, trip number):  (84, 1) / 15096
(Passenger, trip number):  (85, 2) / 15096
(Passenger, trip number):  (86, 2) / 15096
(Passenger, trip number):  (87, 1) / 15096
(Passenger, trip number):  (88, 2) / 15096
(Passenger, trip number):  (89, 1) / 15096
(Passenger, trip number):  (90, 1) / 15096
(Passenger, trip number):  (91, 1) / 15096
(Passenger, trip number):  (92, 1) / 15096
(Passenger, trip number):  (93, 2) / 15096
(Passenger, trip number):  (94, 1) / 15096
(Passenger, trip number):  (95, 2) / 15096
(Passenger, trip number):  (96, 2) / 15096
(Passenger, trip number):  (97, 1) / 15096
(Passenger, trip number):  (98, 1) / 15096
(Passenger, trip number):  (98, 2) / 15096
(Passenger, trip number):  (99, 2) / 15096
(Passenger, trip number):  (100, 1) / 15096
(Passenger, trip number):  (101, 2) / 15096
(Passenger, trip number):  (102, 2) / 15096
(Passenger, trip number):  (103, 1) / 15096
(Passenger, trip number):  (104, 1) / 15096
(Passenger, trip number):  (105, 1) / 15096
(Passenger, trip number):  (106, 1) / 15096
(Passenger, trip number):  (107, 2) / 15096
(Passenger, trip number):  (108, 2) / 15096
(Passenger, trip number):  (109, 1) / 15096
(Passenger, trip number):  (110, 2) / 15096
(Passenger, trip number):  (111, 1) / 15096
(Passenger, trip number):  (112, 2) / 15096
(Passenger, trip number):  (113, 2) / 15096
(Passenger, trip number):  (114, 2) / 15096
(Passenger, trip number):  (115, 1) / 15096
(Passenger, trip number):  (116, 1) / 15096
(Passenger, trip number):  (117, 1) / 15096
(Passenger, trip number):  (118, 2) / 15096
(Passenger, trip number):  (119, 2) / 15096
(Passenger, trip number):  (120, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (122, 1) / 15096
(Passenger, trip number):  (123, 1) / 15096
(Passenger, trip number):  (124, 1) / 15096
(Passenger, trip number):  (125, 1) / 15096
(Passenger, trip number):  (126, 2) / 15096
(Passenger, trip number):  (127, 1) / 15096
(Passenger, trip number):  (128, 1) / 15096
(Passenger, trip number):  (129, 2) / 15096
(Passenger, trip number):  (130, 2) / 15096
(Passenger, trip number):  (131, 3) / 15096
(Passenger, trip number):  (132, 1) / 15096
(Passenger, trip number):  (133, 1) / 15096
(Passenger, trip number):  (134, 1) / 15096
(Passenger, trip number):  (135, 1) / 15096
(Passenger, trip number):  (136, 1) / 15096
(Passenger, trip number):  (137, 1) / 15096
(Passenger, trip number):  (138, 2) / 15096
(Passenger, trip number):  (139, 1) / 15096
(Passenger, trip number):  (140, 1) / 15096
(Passenger, trip number):  (141, 1) / 15096
(Passenger, trip number):  (142, 1) / 15096
(Passenger, trip number):  (143, 1) / 15096
(Passenger, trip number):  (144, 1) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (146, 1) / 15096
(Passenger, trip number):  (147, 2) / 15096
(Passenger, trip number):  (148, 2) / 15096
(Passenger, trip number):  (149, 2) / 15096
(Passenger, trip number):  (150, 2) / 15096
(Passenger, trip number):  (151, 1) / 15096
(Passenger, trip number):  (152, 2) / 15096
(Passenger, trip number):  (153, 2) / 15096
(Passenger, trip number):  (154, 2) / 15096
(Passenger, trip number):  (155, 1) / 15096
(Passenger, trip number):  (156, 1) / 15096
(Passenger, trip number):  (157, 1) / 15096
(Passenger, trip number):  (158, 1) / 15096
(Passenger, trip number):  (159, 1) / 15096
(Passenger, trip number):  (160, 2) / 15096
(Passenger, trip number):  (161, 1) / 15096
(Passenger, trip number):  (162, 1) / 15096
(Passenger, trip number):  (163, 2) / 15096
(Passenger, trip number):  (164, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (166, 1) / 15096
(Passenger, trip number):  (167, 2) / 15096
(Passenger, trip number):  (168, 2) / 15096
(Passenger, trip number):  (169, 1) / 15096
(Passenger, trip number):  (170, 2) / 15096
(Passenger, trip number):  (171, 2) / 15096
(Passenger, trip number):  (172, 1) / 15096
(Passenger, trip number):  (173, 2) / 15096
(Passenger, trip number):  (174, 2) / 15096
(Passenger, trip number):  (175, 2) / 15096
(Passenger, trip number):  (176, 2) / 15096
(Passenger, trip number):  (177, 2) / 15096
(Passenger, trip number):  (178, 2) / 15096
(Passenger, trip number):  (179, 1) / 15096
(Passenger, trip number):  (180, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (182, 2) / 15096
(Passenger, trip number):  (183, 1) / 15096
(Passenger, trip number):  (184, 2) / 15096
(Passenger, trip number):  (185, 1) / 15096
(Passenger, trip number):  (186, 1) / 15096
(Passenger, trip number):  (187, 1) / 15096
(Passenger, trip number):  (188, 1) / 15096
(Passenger, trip number):  (189, 1) / 15096
(Passenger, trip number):  (190, 1) / 15096
(Passenger, trip number):  (191, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (193, 1) / 15096
(Passenger, trip number):  (194, 1) / 15096
(Passenger, trip number):  (195, 1) / 15096
(Passenger, trip number):  (196, 2) / 15096
(Passenger, trip number):  (197, 2) / 15096
(Passenger, trip number):  (198, 1) / 15096
(Passenger, trip number):  (199, 1) / 15096
(Passenger, trip number):  (200, 3) / 15096
(Passenger, trip number):  (201, 2) / 15096
(Passenger, trip number):  (202, 2) / 15096
(Passenger, trip number):  (203, 1) / 15096
(Passenger, trip number):  (204, 2) / 15096
(Passenger, trip number):  (205, 2) / 15096
(Passenger, trip number):  (206, 1) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (208, 1) / 15096
(Passenger, trip number):  (209, 1) / 15096
(Passenger, trip number):  (210, 2) / 15096
(Passenger, trip number):  (211, 1) / 15096
(Passenger, trip number):  (212, 2) / 15096
(Passenger, trip number):  (213, 2) / 15096
(Passenger, trip number):  (214, 1) / 15096
(Passenger, trip number):  (215, 1) / 15096
(Passenger, trip number):  (216, 2) / 15096
(Passenger, trip number):  (217, 2) / 15096
(Passenger, trip number):  (218, 2) / 15096
(Passenger, trip number):  (219, 1) / 15096
(Passenger, trip number):  (220, 2) / 15096
(Passenger, trip number):  (221, 2) / 15096
(Passenger, trip number):  (222, 1) / 15096
(Passenger, trip number):  (223, 2) / 15096
(Passenger, trip number):  (224, 1) / 15096
(Passenger, trip number):  (225, 1) / 15096
(Passenger, trip number):  (226, 1) / 15096
(Passenger, trip number):  (227, 2) / 15096
(Passenger, trip number):  (228, 1) / 15096
(Passenger, trip number):  (229, 1) / 15096
(Passenger, trip number):  (230, 1) / 15096
(Passenger, trip number):  (231, 2) / 15096
(Passenger, trip number):  (232, 2) / 15096
(Passenger, trip number):  (233, 2) / 15096
(Passenger, trip number):  (234, 1) / 15096
(Passenger, trip number):  (235, 1) / 15096
(Passenger, trip number):  (236, 1) / 15096
(Passenger, trip number):  (237, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (239, 1) / 15096
(Passenger, trip number):  (240, 1) / 15096
(Passenger, trip number):  (241, 1) / 15096
(Passenger, trip number):  (242, 1) / 15096
(Passenger, trip number):  (243, 1) / 15096
(Passenger, trip number):  (244, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (246, 1) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (248, 1) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (251, 1) / 15096
(Passenger, trip number):  (252, 2) / 15096
(Passenger, trip number):  (253, 2) / 15096
(Passenger, trip number):  (254, 1) / 15096
(Passenger, trip number):  (255, 1) / 15096
(Passenger, trip number):  (256, 2) / 15096
(Passenger, trip number):  (257, 2) / 15096
(Passenger, trip number):  (258, 2) / 15096
(Passenger, trip number):  (259, 1) / 15096
(Passenger, trip number):  (260, 1) / 15096
(Passenger, trip number):  (261, 2) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (263, 3) / 15096
(Passenger, trip number):  (264, 1) / 15096
(Passenger, trip number):  (265, 1) / 15096
(Passenger, trip number):  (266, 2) / 15096
(Passenger, trip number):  (267, 1) / 15096
(Passenger, trip number):  (268, 2) / 15096
(Passenger, trip number):  (269, 2) / 15096
(Passenger, trip number):  (270, 2) / 15096
(Passenger, trip number):  (271, 1) / 15096
(Passenger, trip number):  (272, 2) / 15096
(Passenger, trip number):  (273, 1) / 15096
(Passenger, trip number):  (274, 1) / 15096
(Passenger, trip number):  (275, 2) / 15096
(Passenger, trip number):  (276, 1) / 15096
(Passenger, trip number):  (277, 1) / 15096
(Passenger, trip number):  (278, 3) / 15096
(Passenger, trip number):  (279, 2) / 15096
(Passenger, trip number):  (280, 1) / 15096
(Passenger, trip number):  (281, 2) / 15096
(Passenger, trip number):  (282, 1) / 15096
(Passenger, trip number):  (283, 1) / 15096
(Passenger, trip number):  (284, 1) / 15096
(Passenger, trip number):  (285, 1) / 15096
(Passenger, trip number):  (286, 2) / 15096
(Passenger, trip number):  (287, 1) / 15096
(Passenger, trip number):  (288, 1) / 15096
(Passenger, trip number):  (289, 2) / 15096
(Passenger, trip number):  (290, 1) / 15096
(Passenger, trip number):  (291, 1) / 15096
(Passenger, trip number):  (292, 2) / 15096
(Passenger, trip number):  (293, 2) / 15096
(Passenger, trip number):  (294, 2) / 15096
(Passenger, trip number):  (295, 2) / 15096
(Passenger, trip number):  (296, 2) / 15096
(Passenger, trip number):  (297, 1) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (299, 2) / 15096
(Passenger, trip number):  (300, 1) / 15096
(Passenger, trip number):  (301, 2) / 15096
(Passenger, trip number):  (302, 2) / 15096
(Passenger, trip number):  (303, 2) / 15096
(Passenger, trip number):  (304, 1) / 15096
(Passenger, trip number):  (305, 1) / 15096
(Passenger, trip number):  (306, 1) / 15096
(Passenger, trip number):  (307, 1) / 15096
(Passenger, trip number):  (308, 1) / 15096
(Passenger, trip number):  (309, 2) / 15096
(Passenger, trip number):  (310, 2) / 15096
(Passenger, trip number):  (311, 2) / 15096
(Passenger, trip number):  (312, 1) / 15096
(Passenger, trip number):  (313, 2) / 15096
(Passenger, trip number):  (314, 2) / 15096
(Passenger, trip number):  (315, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (317, 2) / 15096
(Passenger, trip number):  (318, 2) / 15096
(Passenger, trip number):  (319, 2) / 15096
(Passenger, trip number):  (320, 2) / 15096
(Passenger, trip number):  (321, 1) / 15096
(Passenger, trip number):  (322, 2) / 15096
(Passenger, trip number):  (323, 1) / 15096
(Passenger, trip number):  (324, 1) / 15096
(Passenger, trip number):  (325, 1) / 15096
(Passenger, trip number):  (326, 2) / 15096
(Passenger, trip number):  (327, 2) / 15096
(Passenger, trip number):  (328, 1) / 15096
(Passenger, trip number):  (329, 1) / 15096
(Passenger, trip number):  (330, 2) / 15096
(Passenger, trip number):  (331, 1) / 15096
(Passenger, trip number):  (332, 2) / 15096
(Passenger, trip number):  (333, 1) / 15096
(Passenger, trip number):  (334, 1) / 15096
(Passenger, trip number):  (335, 1) / 15096
(Passenger, trip number):  (336, 2) / 15096
(Passenger, trip number):  (337, 1) / 15096
(Passenger, trip number):  (338, 1) / 15096
(Passenger, trip number):  (339, 1) / 15096
(Passenger, trip number):  (340, 2) / 15096
(Passenger, trip number):  (341, 2) / 15096
(Passenger, trip number):  (342, 2) / 15096
(Passenger, trip number):  (343, 1) / 15096
(Passenger, trip number):  (344, 1) / 15096
(Passenger, trip number):  (345, 1) / 15096
(Passenger, trip number):  (346, 2) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (349, 2) / 15096
(Passenger, trip number):  (350, 1) / 15096
(Passenger, trip number):  (351, 1) / 15096
(Passenger, trip number):  (352, 2) / 15096
(Passenger, trip number):  (353, 1) / 15096
(Passenger, trip number):  (354, 1) / 15096
(Passenger, trip number):  (355, 1) / 15096
(Passenger, trip number):  (356, 1) / 15096
(Passenger, trip number):  (357, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (359, 3) / 15096
(Passenger, trip number):  (360, 1) / 15096
(Passenger, trip number):  (361, 2) / 15096
(Passenger, trip number):  (362, 1) / 15096
(Passenger, trip number):  (363, 1) / 15096
(Passenger, trip number):  (364, 2) / 15096
(Passenger, trip number):  (365, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (367, 2) / 15096
(Passenger, trip number):  (368, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (370, 1) / 15096
(Passenger, trip number):  (371, 2) / 15096
(Passenger, trip number):  (372, 1) / 15096
(Passenger, trip number):  (373, 2) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (375, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (377, 1) / 15096
(Passenger, trip number):  (378, 1) / 15096
(Passenger, trip number):  (379, 2) / 15096
(Passenger, trip number):  (380, 2) / 15096
(Passenger, trip number):  (381, 2) / 15096
(Passenger, trip number):  (382, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (384, 1) / 15096
(Passenger, trip number):  (385, 1) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (387, 1) / 15096
(Passenger, trip number):  (388, 1) / 15096
(Passenger, trip number):  (389, 1) / 15096
(Passenger, trip number):  (390, 1) / 15096
(Passenger, trip number):  (391, 1) / 15096
(Passenger, trip number):  (392, 1) / 15096
(Passenger, trip number):  (393, 1) / 15096
(Passenger, trip number):  (394, 1) / 15096
(Passenger, trip number):  (395, 1) / 15096
(Passenger, trip number):  (396, 1) / 15096
(Passenger, trip number):  (397, 2) / 15096
(Passenger, trip number):  (398, 1) / 15096
(Passenger, trip number):  (399, 1) / 15096
(Passenger, trip number):  (400, 2) / 15096
(Passenger, trip number):  (401, 2) / 15096
(Passenger, trip number):  (402, 2) / 15096
(Passenger, trip number):  (403, 1) / 15096
(Passenger, trip number):  (404, 1) / 15096
(Passenger, trip number):  (405, 1) / 15096
(Passenger, trip number):  (406, 2) / 15096
(Passenger, trip number):  (407, 1) / 15096
(Passenger, trip number):  (408, 1) / 15096
(Passenger, trip number):  (409, 1) / 15096
(Passenger, trip number):  (410, 1) / 15096
(Passenger, trip number):  (411, 1) / 15096
(Passenger, trip number):  (412, 1) / 15096
(Passenger, trip number):  (413, 1) / 15096
(Passenger, trip number):  (414, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (416, 1) / 15096
(Passenger, trip number):  (417, 1) / 15096
(Passenger, trip number):  (418, 1) / 15096
(Passenger, trip number):  (419, 1) / 15096
(Passenger, trip number):  (420, 1) / 15096
(Passenger, trip number):  (421, 2) / 15096
(Passenger, trip number):  (422, 2) / 15096
(Passenger, trip number):  (423, 1) / 15096
(Passenger, trip number):  (424, 2) / 15096
(Passenger, trip number):  (425, 3) / 15096

In [109]:
passengers_per_flight['AZ20271023RHPTPH17919']

{'one_one': [(('387_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 5),
  (('639_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('877_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('922_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('985_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('2111_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('2999_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('3677_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('5941_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('6335_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('8761_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('8846_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('9103_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('9627_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('9728_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('10646_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('11918_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('12931_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('13332_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('13661_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('13931_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('14017_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1)],
 'forced_one': [],
 'one_multi': [],
 'multi_one': [(('207_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('247_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('249_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('481_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('1455_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('1550_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('1951_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('2269_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('2370_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 5),
  (('2839_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('3194_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('3431_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 5),
  (('4121_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('4333_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('4408_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('4527_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('4626_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('4746_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('5122_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('5125_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('5235_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('5333_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('5455_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('5481_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('5970_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('6457_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('6497_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('6679_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('7048_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 8),
  (('7794_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('7911_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('8192_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('8608_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('8821_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('9019_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('9160_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('9689_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 3),
  (('9803_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('9804_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('9880_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('10072_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('10721_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('10830_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('10867_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('11416_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('11474_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('13021_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4),
  (('13043_1_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('13590_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('13783_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('13805_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 1),
  (('13882_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 2),
  (('13989_2_AZ20271021RHPTPH851', 'AZ20271023RHPTPH17919'), 4)],
 'multi_multi': []}

## One-Multi

In [110]:
for passenger in pnr_list:
    print("(Passenger, trip number): ", (passenger.recloc, passenger.trip_number[0]), "/", len(pnr_list))
    
    if (not passenger.booked_multi_leg):
        
        #available_flights_case = flights_2legs_out_in_dic[(str(passenger.oper_od_orig_cd), str(passenger.oper_od_dest_cd))]
        available_flights_case = flights_2legs_out_in_dic[(str(passenger.orig_cd), str(passenger.dest_cd))]
        # Now we iterate over the flights
        for flight_combination in available_flights_case:
            
            first_leg = flight_combination[0]
            second_leg = flight_combination[1]
            
            # Check the departure penalty costs FIRST before doiny any computation
            original_time_dep = datetime.strptime(passenger.dep_dtmz, "%Y-%m-%d %H:%M")  # pnr does not include seconds
            new_time_dep = datetime.strptime(first_leg.dep_dtmz, "%Y-%m-%d %H:%M")  # flight time does include seconds
            time_diff_dep = ((new_time_dep - original_time_dep).total_seconds() / 60.0)  # in minutes
                        
            # Check if the penalty is acceptable or not
            cost_dep = time_penalty(time_diff_dep)
            if (cost_dep <= 0): # Check the penalty
                # Skip all the pairings with ths flight as the first leg
                continue

            # Now we check if the second flight is trash in terms of arriving
            original_time_arr = datetime.strptime(passenger.arr_dtmz, "%Y-%m-%d %H:%M")  # pnr does not include seconds
            new_time_arr = datetime.strptime(second_leg.arr_dtmz, "%Y-%m-%d %H:%M")
            time_diff_arr = ((new_time_arr - original_time_arr).total_seconds() / 60.0)  # in minutes

            # Check if the cost is acceptable or not
            cost_arr = time_penalty(time_diff_arr)
            if (cost_arr <= 0):
                # Skip this second leg
                continue
            
            # Now we add the variable!
            var = (passenger.trip_id, (first_leg.dep_key, second_leg.dep_key))
            
            var_cost = cost_dep + cost_arr + cvm_factor["one_multi"]*passenger.cvm        
                
            # We save the variable

            # We save the assigned DIRECT flight for this passenger
            #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))]["one_one"].append( var )
            flights_per_passenger[str(passenger.trip_id)]["one_multi"]["variables"].append( var )
            flights_per_passenger[str(passenger.trip_id)]["one_multi"]["values"].append(var_cost)
            flights_per_passenger[str(passenger.trip_id)]["one_multi"]["pax_cnt"].append(passenger.pax_cnt)
            flights_per_passenger[str(passenger.trip_id)]["one_multi"]["avail_cnt"].append((first_leg.c_avail_cnt + first_leg.y_avail_cnt, second_leg.c_avail_cnt + second_leg.y_avail_cnt))
            

            # We add the assigned flight to be dictionary saving the global variables
            passengers_per_flight[first_leg.dep_key]["one_multi"].append( (var, passenger.pax_cnt) )
            passengers_per_flight[second_leg.dep_key]["one_multi"].append( (var, passenger.pax_cnt) )



            # We increment the number of total variables
            n_variables = n_variables + 1
            n_one_multi = n_one_multi + 1

(Passenger, trip number):  (0, 1) / 15096
(Passenger, trip number):  (1, 1) / 15096
(Passenger, trip number):  (2, 1) / 15096
(Passenger, trip number):  (3, 2) / 15096
(Passenger, trip number):  (4, 1) / 15096
(Passenger, trip number):  (5, 2) / 15096
(Passenger, trip number):  (6, 2) / 15096
(Passenger, trip number):  (7, 2) / 15096
(Passenger, trip number):  (8, 2) / 15096
(Passenger, trip number):  (9, 1) / 15096
(Passenger, trip number):  (10, 1) / 15096
(Passenger, trip number):  (11, 1) / 15096
(Passenger, trip number):  (12, 2) / 15096
(Passenger, trip number):  (13, 1) / 15096
(Passenger, trip number):  (14, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (16, 1) / 15096
(Passenger, trip number):  (17, 1) / 15096
(Passenger, trip number):  (18, 1) / 15096
(Passenger, trip number):  (19, 1) / 15096
(Passenger, trip number):  (20, 1) / 15096
(Passenger, trip number):  (21, 1) / 15096
(Passenger, trip number):  (22, 1) / 15096
(Passenger, trip number):  (23, 1) / 15096
(Passenger, trip number):  (24, 1) / 15096
(Passenger, trip number):  (25, 1) / 15096
(Passenger, trip number):  (26, 2) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (28, 1) / 15096
(Passenger, trip number):  (29, 1) / 15096
(Passenger, trip number):  (30, 2) / 15096
(Passenger, trip number):  (31, 2) / 15096
(Passenger, trip number):  (32, 1) / 15096
(Passenger, trip number):  (33, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (35, 2) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (37, 2) / 15096
(Passenger, trip number):  (38, 1) / 15096
(Passenger, trip number):  (39, 1) / 15096
(Passenger, trip number):  (40, 2) / 15096
(Passenger, trip number):  (41, 1) / 15096
(Passenger, trip number):  (42, 2) / 15096
(Passenger, trip number):  (43, 2) / 15096
(Passenger, trip number):  (44, 1) / 15096
(Passenger, trip number):  (45, 1) / 15096
(Passenger, trip number):  (46, 2) / 15096
(Passenger, trip number):  (47, 1) / 15096
(Passenger, trip number):  (48, 1) / 15096
(Passenger, trip number):  (49, 1) / 15096
(Passenger, trip number):  (50, 1) / 15096
(Passenger, trip number):  (51, 1) / 15096
(Passenger, trip number):  (52, 2) / 15096
(Passenger, trip number):  (53, 1) / 15096
(Passenger, trip number):  (54, 1) / 15096
(Passenger, trip number):  (55, 1) / 15096
(Passenger, trip number):  (56, 2) / 15096
(Passenger, trip number):  (57, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (59, 1) / 15096
(Passenger, trip number):  (60, 1) / 15096
(Passenger, trip number):  (61, 1) / 15096
(Passenger, trip number):  (62, 1) / 15096
(Passenger, trip number):  (63, 2) / 15096
(Passenger, trip number):  (64, 2) / 15096
(Passenger, trip number):  (65, 2) / 15096
(Passenger, trip number):  (66, 1) / 15096
(Passenger, trip number):  (67, 1) / 15096
(Passenger, trip number):  (68, 1) / 15096
(Passenger, trip number):  (69, 1) / 15096
(Passenger, trip number):  (70, 2) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (72, 1) / 15096
(Passenger, trip number):  (73, 1) / 15096
(Passenger, trip number):  (74, 2) / 15096
(Passenger, trip number):  (75, 2) / 15096
(Passenger, trip number):  (76, 2) / 15096
(Passenger, trip number):  (77, 1) / 15096
(Passenger, trip number):  (78, 2) / 15096
(Passenger, trip number):  (79, 1) / 15096
(Passenger, trip number):  (80, 1) / 15096
(Passenger, trip number):  (81, 2) / 15096
(Passenger, trip number):  (82, 2) / 15096
(Passenger, trip number):  (83, 2) / 15096
(Passenger, trip number):  (84, 1) / 15096
(Passenger, trip number):  (85, 2) / 15096
(Passenger, trip number):  (86, 2) / 15096
(Passenger, trip number):  (87, 1) / 15096
(Passenger, trip number):  (88, 2) / 15096
(Passenger, trip number):  (89, 1) / 15096
(Passenger, trip number):  (90, 1) / 15096
(Passenger, trip number):  (91, 1) / 15096
(Passenger, trip number):  (92, 1) / 15096
(Passenger, trip number):  (93, 2) / 15096
(Passenger, trip number):  (94, 1) / 15096
(Passenger, trip number):  (95, 2) / 15096
(Passenger, trip number):  (96, 2) / 15096
(Passenger, trip number):  (97, 1) / 15096
(Passenger, trip number):  (98, 1) / 15096
(Passenger, trip number):  (98, 2) / 15096
(Passenger, trip number):  (99, 2) / 15096
(Passenger, trip number):  (100, 1) / 15096
(Passenger, trip number):  (101, 2) / 15096
(Passenger, trip number):  (102, 2) / 15096
(Passenger, trip number):  (103, 1) / 15096
(Passenger, trip number):  (104, 1) / 15096
(Passenger, trip number):  (105, 1) / 15096
(Passenger, trip number):  (106, 1) / 15096
(Passenger, trip number):  (107, 2) / 15096
(Passenger, trip number):  (108, 2) / 15096
(Passenger, trip number):  (109, 1) / 15096
(Passenger, trip number):  (110, 2) / 15096
(Passenger, trip number):  (111, 1) / 15096
(Passenger, trip number):  (112, 2) / 15096
(Passenger, trip number):  (113, 2) / 15096
(Passenger, trip number):  (114, 2) / 15096
(Passenger, trip number):  (115, 1) / 15096
(Passenger, trip number):  (116, 1) / 15096
(Passenger, trip number):  (117, 1) / 15096
(Passenger, trip number):  (118, 2) / 15096
(Passenger, trip number):  (119, 2) / 15096
(Passenger, trip number):  (120, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (122, 1) / 15096
(Passenger, trip number):  (123, 1) / 15096
(Passenger, trip number):  (124, 1) / 15096
(Passenger, trip number):  (125, 1) / 15096
(Passenger, trip number):  (126, 2) / 15096
(Passenger, trip number):  (127, 1) / 15096
(Passenger, trip number):  (128, 1) / 15096
(Passenger, trip number):  (129, 2) / 15096
(Passenger, trip number):  (130, 2) / 15096
(Passenger, trip number):  (131, 3) / 15096
(Passenger, trip number):  (132, 1) / 15096
(Passenger, trip number):  (133, 1) / 15096
(Passenger, trip number):  (134, 1) / 15096
(Passenger, trip number):  (135, 1) / 15096
(Passenger, trip number):  (136, 1) / 15096
(Passenger, trip number):  (137, 1) / 15096
(Passenger, trip number):  (138, 2) / 15096
(Passenger, trip number):  (139, 1) / 15096
(Passenger, trip number):  (140, 1) / 15096
(Passenger, trip number):  (141, 1) / 15096
(Passenger, trip number):  (142, 1) / 15096
(Passenger, trip number):  (143, 1) / 15096
(Passenger, trip number):  (144, 1) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (146, 1) / 15096
(Passenger, trip number):  (147, 2) / 15096
(Passenger, trip number):  (148, 2) / 15096
(Passenger, trip number):  (149, 2) / 15096
(Passenger, trip number):  (150, 2) / 15096
(Passenger, trip number):  (151, 1) / 15096
(Passenger, trip number):  (152, 2) / 15096
(Passenger, trip number):  (153, 2) / 15096
(Passenger, trip number):  (154, 2) / 15096
(Passenger, trip number):  (155, 1) / 15096
(Passenger, trip number):  (156, 1) / 15096
(Passenger, trip number):  (157, 1) / 15096
(Passenger, trip number):  (158, 1) / 15096
(Passenger, trip number):  (159, 1) / 15096
(Passenger, trip number):  (160, 2) / 15096
(Passenger, trip number):  (161, 1) / 15096
(Passenger, trip number):  (162, 1) / 15096
(Passenger, trip number):  (163, 2) / 15096
(Passenger, trip number):  (164, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (166, 1) / 15096
(Passenger, trip number):  (167, 2) / 15096
(Passenger, trip number):  (168, 2) / 15096
(Passenger, trip number):  (169, 1) / 15096
(Passenger, trip number):  (170, 2) / 15096
(Passenger, trip number):  (171, 2) / 15096
(Passenger, trip number):  (172, 1) / 15096
(Passenger, trip number):  (173, 2) / 15096
(Passenger, trip number):  (174, 2) / 15096
(Passenger, trip number):  (175, 2) / 15096
(Passenger, trip number):  (176, 2) / 15096
(Passenger, trip number):  (177, 2) / 15096
(Passenger, trip number):  (178, 2) / 15096
(Passenger, trip number):  (179, 1) / 15096
(Passenger, trip number):  (180, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (182, 2) / 15096
(Passenger, trip number):  (183, 1) / 15096
(Passenger, trip number):  (184, 2) / 15096
(Passenger, trip number):  (185, 1) / 15096
(Passenger, trip number):  (186, 1) / 15096
(Passenger, trip number):  (187, 1) / 15096
(Passenger, trip number):  (188, 1) / 15096
(Passenger, trip number):  (189, 1) / 15096
(Passenger, trip number):  (190, 1) / 15096
(Passenger, trip number):  (191, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (193, 1) / 15096
(Passenger, trip number):  (194, 1) / 15096
(Passenger, trip number):  (195, 1) / 15096
(Passenger, trip number):  (196, 2) / 15096
(Passenger, trip number):  (197, 2) / 15096
(Passenger, trip number):  (198, 1) / 15096
(Passenger, trip number):  (199, 1) / 15096
(Passenger, trip number):  (200, 3) / 15096
(Passenger, trip number):  (201, 2) / 15096
(Passenger, trip number):  (202, 2) / 15096
(Passenger, trip number):  (203, 1) / 15096
(Passenger, trip number):  (204, 2) / 15096
(Passenger, trip number):  (205, 2) / 15096
(Passenger, trip number):  (206, 1) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (208, 1) / 15096
(Passenger, trip number):  (209, 1) / 15096
(Passenger, trip number):  (210, 2) / 15096
(Passenger, trip number):  (211, 1) / 15096
(Passenger, trip number):  (212, 2) / 15096
(Passenger, trip number):  (213, 2) / 15096
(Passenger, trip number):  (214, 1) / 15096
(Passenger, trip number):  (215, 1) / 15096
(Passenger, trip number):  (216, 2) / 15096
(Passenger, trip number):  (217, 2) / 15096
(Passenger, trip number):  (218, 2) / 15096
(Passenger, trip number):  (219, 1) / 15096
(Passenger, trip number):  (220, 2) / 15096
(Passenger, trip number):  (221, 2) / 15096
(Passenger, trip number):  (222, 1) / 15096
(Passenger, trip number):  (223, 2) / 15096
(Passenger, trip number):  (224, 1) / 15096
(Passenger, trip number):  (225, 1) / 15096
(Passenger, trip number):  (226, 1) / 15096
(Passenger, trip number):  (227, 2) / 15096
(Passenger, trip number):  (228, 1) / 15096
(Passenger, trip number):  (229, 1) / 15096
(Passenger, trip number):  (230, 1) / 15096
(Passenger, trip number):  (231, 2) / 15096
(Passenger, trip number):  (232, 2) / 15096
(Passenger, trip number):  (233, 2) / 15096
(Passenger, trip number):  (234, 1) / 15096
(Passenger, trip number):  (235, 1) / 15096
(Passenger, trip number):  (236, 1) / 15096
(Passenger, trip number):  (237, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (239, 1) / 15096
(Passenger, trip number):  (240, 1) / 15096
(Passenger, trip number):  (241, 1) / 15096
(Passenger, trip number):  (242, 1) / 15096
(Passenger, trip number):  (243, 1) / 15096
(Passenger, trip number):  (244, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (246, 1) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (248, 1) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (251, 1) / 15096
(Passenger, trip number):  (252, 2) / 15096
(Passenger, trip number):  (253, 2) / 15096
(Passenger, trip number):  (254, 1) / 15096
(Passenger, trip number):  (255, 1) / 15096
(Passenger, trip number):  (256, 2) / 15096
(Passenger, trip number):  (257, 2) / 15096
(Passenger, trip number):  (258, 2) / 15096
(Passenger, trip number):  (259, 1) / 15096
(Passenger, trip number):  (260, 1) / 15096
(Passenger, trip number):  (261, 2) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (263, 3) / 15096
(Passenger, trip number):  (264, 1) / 15096
(Passenger, trip number):  (265, 1) / 15096
(Passenger, trip number):  (266, 2) / 15096
(Passenger, trip number):  (267, 1) / 15096
(Passenger, trip number):  (268, 2) / 15096
(Passenger, trip number):  (269, 2) / 15096
(Passenger, trip number):  (270, 2) / 15096
(Passenger, trip number):  (271, 1) / 15096
(Passenger, trip number):  (272, 2) / 15096
(Passenger, trip number):  (273, 1) / 15096
(Passenger, trip number):  (274, 1) / 15096
(Passenger, trip number):  (275, 2) / 15096
(Passenger, trip number):  (276, 1) / 15096
(Passenger, trip number):  (277, 1) / 15096
(Passenger, trip number):  (278, 3) / 15096
(Passenger, trip number):  (279, 2) / 15096
(Passenger, trip number):  (280, 1) / 15096
(Passenger, trip number):  (281, 2) / 15096
(Passenger, trip number):  (282, 1) / 15096
(Passenger, trip number):  (283, 1) / 15096
(Passenger, trip number):  (284, 1) / 15096
(Passenger, trip number):  (285, 1) / 15096
(Passenger, trip number):  (286, 2) / 15096
(Passenger, trip number):  (287, 1) / 15096
(Passenger, trip number):  (288, 1) / 15096
(Passenger, trip number):  (289, 2) / 15096
(Passenger, trip number):  (290, 1) / 15096
(Passenger, trip number):  (291, 1) / 15096
(Passenger, trip number):  (292, 2) / 15096
(Passenger, trip number):  (293, 2) / 15096
(Passenger, trip number):  (294, 2) / 15096
(Passenger, trip number):  (295, 2) / 15096
(Passenger, trip number):  (296, 2) / 15096
(Passenger, trip number):  (297, 1) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (299, 2) / 15096
(Passenger, trip number):  (300, 1) / 15096
(Passenger, trip number):  (301, 2) / 15096
(Passenger, trip number):  (302, 2) / 15096
(Passenger, trip number):  (303, 2) / 15096
(Passenger, trip number):  (304, 1) / 15096
(Passenger, trip number):  (305, 1) / 15096
(Passenger, trip number):  (306, 1) / 15096
(Passenger, trip number):  (307, 1) / 15096
(Passenger, trip number):  (308, 1) / 15096
(Passenger, trip number):  (309, 2) / 15096
(Passenger, trip number):  (310, 2) / 15096
(Passenger, trip number):  (311, 2) / 15096
(Passenger, trip number):  (312, 1) / 15096
(Passenger, trip number):  (313, 2) / 15096
(Passenger, trip number):  (314, 2) / 15096
(Passenger, trip number):  (315, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (317, 2) / 15096
(Passenger, trip number):  (318, 2) / 15096
(Passenger, trip number):  (319, 2) / 15096
(Passenger, trip number):  (320, 2) / 15096
(Passenger, trip number):  (321, 1) / 15096
(Passenger, trip number):  (322, 2) / 15096
(Passenger, trip number):  (323, 1) / 15096
(Passenger, trip number):  (324, 1) / 15096
(Passenger, trip number):  (325, 1) / 15096
(Passenger, trip number):  (326, 2) / 15096
(Passenger, trip number):  (327, 2) / 15096
(Passenger, trip number):  (328, 1) / 15096
(Passenger, trip number):  (329, 1) / 15096
(Passenger, trip number):  (330, 2) / 15096
(Passenger, trip number):  (331, 1) / 15096
(Passenger, trip number):  (332, 2) / 15096
(Passenger, trip number):  (333, 1) / 15096
(Passenger, trip number):  (334, 1) / 15096
(Passenger, trip number):  (335, 1) / 15096
(Passenger, trip number):  (336, 2) / 15096
(Passenger, trip number):  (337, 1) / 15096
(Passenger, trip number):  (338, 1) / 15096
(Passenger, trip number):  (339, 1) / 15096
(Passenger, trip number):  (340, 2) / 15096
(Passenger, trip number):  (341, 2) / 15096
(Passenger, trip number):  (342, 2) / 15096
(Passenger, trip number):  (343, 1) / 15096
(Passenger, trip number):  (344, 1) / 15096
(Passenger, trip number):  (345, 1) / 15096
(Passenger, trip number):  (346, 2) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (349, 2) / 15096
(Passenger, trip number):  (350, 1) / 15096
(Passenger, trip number):  (351, 1) / 15096
(Passenger, trip number):  (352, 2) / 15096
(Passenger, trip number):  (353, 1) / 15096
(Passenger, trip number):  (354, 1) / 15096
(Passenger, trip number):  (355, 1) / 15096
(Passenger, trip number):  (356, 1) / 15096
(Passenger, trip number):  (357, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (359, 3) / 15096
(Passenger, trip number):  (360, 1) / 15096
(Passenger, trip number):  (361, 2) / 15096
(Passenger, trip number):  (362, 1) / 15096
(Passenger, trip number):  (363, 1) / 15096
(Passenger, trip number):  (364, 2) / 15096
(Passenger, trip number):  (365, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (367, 2) / 15096
(Passenger, trip number):  (368, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (370, 1) / 15096
(Passenger, trip number):  (371, 2) / 15096
(Passenger, trip number):  (372, 1) / 15096
(Passenger, trip number):  (373, 2) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (375, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (377, 1) / 15096
(Passenger, trip number):  (378, 1) / 15096
(Passenger, trip number):  (379, 2) / 15096
(Passenger, trip number):  (380, 2) / 15096
(Passenger, trip number):  (381, 2) / 15096
(Passenger, trip number):  (382, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (384, 1) / 15096
(Passenger, trip number):  (385, 1) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (387, 1) / 15096
(Passenger, trip number):  (388, 1) / 15096
(Passenger, trip number):  (389, 1) / 15096
(Passenger, trip number):  (390, 1) / 15096
(Passenger, trip number):  (391, 1) / 15096
(Passenger, trip number):  (392, 1) / 15096
(Passenger, trip number):  (393, 1) / 15096
(Passenger, trip number):  (394, 1) / 15096
(Passenger, trip number):  (395, 1) / 15096
(Passenger, trip number):  (396, 1) / 15096
(Passenger, trip number):  (397, 2) / 15096
(Passenger, trip number):  (398, 1) / 15096
(Passenger, trip number):  (399, 1) / 15096
(Passenger, trip number):  (400, 2) / 15096
(Passenger, trip number):  (401, 2) / 15096
(Passenger, trip number):  (402, 2) / 15096
(Passenger, trip number):  (403, 1) / 15096
(Passenger, trip number):  (404, 1) / 15096
(Passenger, trip number):  (405, 1) / 15096
(Passenger, trip number):  (406, 2) / 15096
(Passenger, trip number):  (407, 1) / 15096
(Passenger, trip number):  (408, 1) / 15096
(Passenger, trip number):  (409, 1) / 15096
(Passenger, trip number):  (410, 1) / 15096
(Passenger, trip number):  (411, 1) / 15096
(Passenger, trip number):  (412, 1) / 15096
(Passenger, trip number):  (413, 1) / 15096
(Passenger, trip number):  (414, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (416, 1) / 15096
(Passenger, trip number):  (417, 1) / 15096
(Passenger, trip number):  (418, 1) / 15096
(Passenger, trip number):  (419, 1) / 15096
(Passenger, trip number):  (420, 1) / 15096
(Passenger, trip number):  (421, 2) / 15096
(Passenger, trip number):  (422, 2) / 15096
(Passenger, trip number):  (423, 1) / 15096
(Passenger, trip number):  (424, 2) / 15096
(Passenger, trip number):  (425, 3) / 15096

## Multi-Multi

In [111]:
for passenger in pnr_list:
    print("(Passenger, trip number): ", (passenger.recloc, passenger.trip_number[0]), "/", len(pnr_list))
    
    if (passenger.booked_multi_leg):
        
        #available_flights_case = flights_2legs_out_in_dic[(str(passenger.oper_od_orig_cd), str(passenger.oper_od_dest_cd))]
        available_flights_case = flights_2legs_out_in_dic[(str(passenger.orig_cd), str(passenger.dest_cd))]
        # Now we iterate over the flights
        for flight_combination in available_flights_case:
            
            first_leg = flight_combination[0]
            second_leg = flight_combination[1]
            
            # Check the departure penalty costs FIRST before doiny any computation
            original_time_dep = datetime.strptime(passenger.dep_dtmz, "%Y-%m-%d %H:%M")  # pnr does not include seconds
            new_time_dep = datetime.strptime(first_leg.dep_dtmz, "%Y-%m-%d %H:%M")  # flight time does include seconds
            time_diff_dep = ((new_time_dep - original_time_dep).total_seconds() / 60.0)  # in minutes
                        
            # Check if the penalty is acceptable or not
            cost_dep = time_penalty(time_diff_dep)
            if (cost_dep <= 0): # Check the penalty
                # Skip all the pairings with ths flight as the first leg
                continue

            # Now we check if the second flight is trash in terms of arriving
            original_time_arr = datetime.strptime(passenger.arr_dtmz, "%Y-%m-%d %H:%M")  # pnr does not include seconds
            new_time_arr = datetime.strptime(second_leg.arr_dtmz, "%Y-%m-%d %H:%M")
            time_diff_arr = ((new_time_arr - original_time_arr).total_seconds() / 60.0)  # in minutes

            # Check if the cost is acceptable or not
            cost_arr = time_penalty(time_diff_arr)
            if (cost_arr <= 0):
                # Skip this second leg
                continue
            
            # Now we add the variable!
            var = (passenger.trip_id, (first_leg.dep_key, second_leg.dep_key))
            
            var_cost = cost_dep + cost_arr + cvm_factor["multi_multi"]*passenger.cvm        
                
            # We save the variable

            # We save the assigned DIRECT flight for this passenger
            #variables_per_passenger[(str(passenger.recloc), str(passenger.trip_number[0]))]["one_one"].append( var )
            flights_per_passenger[str(passenger.trip_id)]["multi_multi"]["variables"].append( var )
            flights_per_passenger[str(passenger.trip_id)]["multi_multi"]["values"].append(var_cost)
            flights_per_passenger[str(passenger.trip_id)]["multi_multi"]["pax_cnt"].append(passenger.pax_cnt)
            flights_per_passenger[str(passenger.trip_id)]["one_multi"]["avail_cnt"].append((first_leg.c_avail_cnt + first_leg.y_avail_cnt, second_leg.c_avail_cnt + second_leg.y_avail_cnt))
            

            # We add the assigned flight to be dictionary saving the global variables
            passengers_per_flight[first_leg.dep_key]["multi_multi"].append( (var, passenger.pax_cnt) )
            passengers_per_flight[second_leg.dep_key]["multi_multi"].append( (var, passenger.pax_cnt) )



            # We increment the number of total variables
            n_variables = n_variables + 1
            n_multi_multi = n_multi_multi + 1

(Passenger, trip number):  (0, 1) / 15096
(Passenger, trip number):  (1, 1) / 15096
(Passenger, trip number):  (2, 1) / 15096
(Passenger, trip number):  (3, 2) / 15096
(Passenger, trip number):  (4, 1) / 15096
(Passenger, trip number):  (5, 2) / 15096
(Passenger, trip number):  (6, 2) / 15096
(Passenger, trip number):  (7, 2) / 15096
(Passenger, trip number):  (8, 2) / 15096
(Passenger, trip number):  (9, 1) / 15096
(Passenger, trip number):  (10, 1) / 15096
(Passenger, trip number):  (11, 1) / 15096
(Passenger, trip number):  (12, 2) / 15096
(Passenger, trip number):  (13, 1) / 15096
(Passenger, trip number):  (14, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (15, 1) / 15096
(Passenger, trip number):  (16, 1) / 15096
(Passenger, trip number):  (17, 1) / 15096
(Passenger, trip number):  (18, 1) / 15096
(Passenger, trip number):  (19, 1) / 15096
(Passenger, trip number):  (20, 1) / 15096
(Passenger, trip number):  (21, 1) / 15096
(Passenger, trip number):  (22, 1) / 15096
(Passenger, trip number):  (23, 1) / 15096
(Passenger, trip number):  (24, 1) / 15096
(Passenger, trip number):  (25, 1) / 15096
(Passenger, trip number):  (26, 2) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (27, 1) / 15096
(Passenger, trip number):  (28, 1) / 15096
(Passenger, trip number):  (29, 1) / 15096
(Passenger, trip number):  (30, 2) / 15096
(Passenger, trip number):  (31, 2) / 15096
(Passenger, trip number):  (32, 1) / 15096
(Passenger, trip number):  (33, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (34, 1) / 15096
(Passenger, trip number):  (35, 2) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (36, 1) / 15096
(Passenger, trip number):  (37, 2) / 15096
(Passenger, trip number):  (38, 1) / 15096
(Passenger, trip number):  (39, 1) / 15096
(Passenger, trip number):  (40, 2) / 15096
(Passenger, trip number):  (41, 1) / 15096
(Passenger, trip number):  (42, 2) / 15096
(Passenger, trip number):  (43, 2) / 15096
(Passenger, trip number):  (44, 1) / 15096
(Passenger, trip number):  (45, 1) / 15096
(Passenger, trip number):  (46, 2) / 15096
(Passenger, trip number):  (47, 1) / 15096
(Passenger, trip number):  (48, 1) / 15096
(Passenger, trip number):  (49, 1) / 15096
(Passenger, trip number):  (50, 1) / 15096
(Passenger, trip number):  (51, 1) / 15096
(Passenger, trip number):  (52, 2) / 15096
(Passenger, trip number):  (53, 1) / 15096
(Passenger, trip number):  (54, 1) / 15096
(Passenger, trip number):  (55, 1) / 15096
(Passenger, trip number):  (56, 2) / 15096
(Passenger, trip number):  (57, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (58, 2) / 15096
(Passenger, trip number):  (59, 1) / 15096
(Passenger, trip number):  (60, 1) / 15096
(Passenger, trip number):  (61, 1) / 15096
(Passenger, trip number):  (62, 1) / 15096
(Passenger, trip number):  (63, 2) / 15096
(Passenger, trip number):  (64, 2) / 15096
(Passenger, trip number):  (65, 2) / 15096
(Passenger, trip number):  (66, 1) / 15096
(Passenger, trip number):  (67, 1) / 15096
(Passenger, trip number):  (68, 1) / 15096
(Passenger, trip number):  (69, 1) / 15096
(Passenger, trip number):  (70, 2) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (71, 1) / 15096
(Passenger, trip number):  (72, 1) / 15096
(Passenger, trip number):  (73, 1) / 15096
(Passenger, trip number):  (74, 2) / 15096
(Passenger, trip number):  (75, 2) / 15096
(Passenger, trip number):  (76, 2) / 15096
(Passenger, trip number):  (77, 1) / 15096
(Passenger, trip number):  (78, 2) / 15096
(Passenger, trip number):  (79, 1) / 15096
(Passenger, trip number):  (80, 1) / 15096
(Passenger, trip number):  (81, 2) / 15096
(Passenger, trip number):  (82, 2) / 15096
(Passenger, trip number):  (83, 2) / 15096
(Passenger, trip number):  (84, 1) / 15096
(Passenger, trip number):  (85, 2) / 15096
(Passenger, trip number):  (86, 2) / 15096
(Passenger, trip number):  (87, 1) / 15096
(Passenger, trip number):  (88, 2) / 15096
(Passenger, trip number):  (89, 1) / 15096
(Passenger, trip number):  (90, 1) / 15096
(Passenger, trip number):  (91, 1) / 15096
(Passenger, trip number):  (92, 1) / 15096
(Passenger, trip number):  (93, 2) / 15096
(Passenger, trip number):  (94, 1) / 15096
(Passenger, trip number):  (95, 2) / 15096
(Passenger, trip number):  (96, 2) / 15096
(Passenger, trip number):  (97, 1) / 15096
(Passenger, trip number):  (98, 1) / 15096
(Passenger, trip number):  (98, 2) / 15096
(Passenger, trip number):  (99, 2) / 15096
(Passenger, trip number):  (100, 1) / 15096
(Passenger, trip number):  (101, 2) / 15096
(Passenger, trip number):  (102, 2) / 15096
(Passenger, trip number):  (103, 1) / 15096
(Passenger, trip number):  (104, 1) / 15096
(Passenger, trip number):  (105, 1) / 15096
(Passenger, trip number):  (106, 1) / 15096
(Passenger, trip number):  (107, 2) / 15096
(Passenger, trip number):  (108, 2) / 15096
(Passenger, trip number):  (109, 1) / 15096
(Passenger, trip number):  (110, 2) / 15096
(Passenger, trip number):  (111, 1) / 15096
(Passenger, trip number):  (112, 2) / 15096
(Passenger, trip number):  (113, 2) / 15096
(Passenger, trip number):  (114, 2) / 15096
(Passenger, trip number):  (115, 1) / 15096
(Passenger, trip number):  (116, 1) / 15096
(Passenger, trip number):  (117, 1) / 15096
(Passenger, trip number):  (118, 2) / 15096
(Passenger, trip number):  (119, 2) / 15096
(Passenger, trip number):  (120, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (121, 1) / 15096
(Passenger, trip number):  (122, 1) / 15096
(Passenger, trip number):  (123, 1) / 15096
(Passenger, trip number):  (124, 1) / 15096
(Passenger, trip number):  (125, 1) / 15096
(Passenger, trip number):  (126, 2) / 15096
(Passenger, trip number):  (127, 1) / 15096
(Passenger, trip number):  (128, 1) / 15096
(Passenger, trip number):  (129, 2) / 15096
(Passenger, trip number):  (130, 2) / 15096
(Passenger, trip number):  (131, 3) / 15096
(Passenger, trip number):  (132, 1) / 15096
(Passenger, trip number):  (133, 1) / 15096
(Passenger, trip number):  (134, 1) / 15096
(Passenger, trip number):  (135, 1) / 15096
(Passenger, trip number):  (136, 1) / 15096
(Passenger, trip number):  (137, 1) / 15096
(Passenger, trip number):  (138, 2) / 15096
(Passenger, trip number):  (139, 1) / 15096
(Passenger, trip number):  (140, 1) / 15096
(Passenger, trip number):  (141, 1) / 15096
(Passenger, trip number):  (142, 1) / 15096
(Passenger, trip number):  (143, 1) / 15096
(Passenger, trip number):  (144, 1) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (145, 2) / 15096
(Passenger, trip number):  (146, 1) / 15096
(Passenger, trip number):  (147, 2) / 15096
(Passenger, trip number):  (148, 2) / 15096
(Passenger, trip number):  (149, 2) / 15096
(Passenger, trip number):  (150, 2) / 15096
(Passenger, trip number):  (151, 1) / 15096
(Passenger, trip number):  (152, 2) / 15096
(Passenger, trip number):  (153, 2) / 15096
(Passenger, trip number):  (154, 2) / 15096
(Passenger, trip number):  (155, 1) / 15096
(Passenger, trip number):  (156, 1) / 15096
(Passenger, trip number):  (157, 1) / 15096
(Passenger, trip number):  (158, 1) / 15096
(Passenger, trip number):  (159, 1) / 15096
(Passenger, trip number):  (160, 2) / 15096
(Passenger, trip number):  (161, 1) / 15096
(Passenger, trip number):  (162, 1) / 15096
(Passenger, trip number):  (163, 2) / 15096
(Passenger, trip number):  (164, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (165, 2) / 15096
(Passenger, trip number):  (166, 1) / 15096
(Passenger, trip number):  (167, 2) / 15096
(Passenger, trip number):  (168, 2) / 15096
(Passenger, trip number):  (169, 1) / 15096
(Passenger, trip number):  (170, 2) / 15096
(Passenger, trip number):  (171, 2) / 15096
(Passenger, trip number):  (172, 1) / 15096
(Passenger, trip number):  (173, 2) / 15096
(Passenger, trip number):  (174, 2) / 15096
(Passenger, trip number):  (175, 2) / 15096
(Passenger, trip number):  (176, 2) / 15096
(Passenger, trip number):  (177, 2) / 15096
(Passenger, trip number):  (178, 2) / 15096
(Passenger, trip number):  (179, 1) / 15096
(Passenger, trip number):  (180, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (181, 1) / 15096
(Passenger, trip number):  (182, 2) / 15096
(Passenger, trip number):  (183, 1) / 15096
(Passenger, trip number):  (184, 2) / 15096
(Passenger, trip number):  (185, 1) / 15096
(Passenger, trip number):  (186, 1) / 15096
(Passenger, trip number):  (187, 1) / 15096
(Passenger, trip number):  (188, 1) / 15096
(Passenger, trip number):  (189, 1) / 15096
(Passenger, trip number):  (190, 1) / 15096
(Passenger, trip number):  (191, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (192, 2) / 15096
(Passenger, trip number):  (193, 1) / 15096
(Passenger, trip number):  (194, 1) / 15096
(Passenger, trip number):  (195, 1) / 15096
(Passenger, trip number):  (196, 2) / 15096
(Passenger, trip number):  (197, 2) / 15096
(Passenger, trip number):  (198, 1) / 15096
(Passenger, trip number):  (199, 1) / 15096
(Passenger, trip number):  (200, 3) / 15096
(Passenger, trip number):  (201, 2) / 15096
(Passenger, trip number):  (202, 2) / 15096
(Passenger, trip number):  (203, 1) / 15096
(Passenger, trip number):  (204, 2) / 15096
(Passenger, trip number):  (205, 2) / 15096
(Passenger, trip number):  (206, 1) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (207, 2) / 15096
(Passenger, trip number):  (208, 1) / 15096
(Passenger, trip number):  (209, 1) / 15096
(Passenger, trip number):  (210, 2) / 15096
(Passenger, trip number):  (211, 1) / 15096
(Passenger, trip number):  (212, 2) / 15096
(Passenger, trip number):  (213, 2) / 15096
(Passenger, trip number):  (214, 1) / 15096
(Passenger, trip number):  (215, 1) / 15096
(Passenger, trip number):  (216, 2) / 15096
(Passenger, trip number):  (217, 2) / 15096
(Passenger, trip number):  (218, 2) / 15096
(Passenger, trip number):  (219, 1) / 15096
(Passenger, trip number):  (220, 2) / 15096
(Passenger, trip number):  (221, 2) / 15096
(Passenger, trip number):  (222, 1) / 15096
(Passenger, trip number):  (223, 2) / 15096
(Passenger, trip number):  (224, 1) / 15096
(Passenger, trip number):  (225, 1) / 15096
(Passenger, trip number):  (226, 1) / 15096
(Passenger, trip number):  (227, 2) / 15096
(Passenger, trip number):  (228, 1) / 15096
(Passenger, trip number):  (229, 1) / 15096
(Passenger, trip number):  (230, 1) / 15096
(Passenger, trip number):  (231, 2) / 15096
(Passenger, trip number):  (232, 2) / 15096
(Passenger, trip number):  (233, 2) / 15096
(Passenger, trip number):  (234, 1) / 15096
(Passenger, trip number):  (235, 1) / 15096
(Passenger, trip number):  (236, 1) / 15096
(Passenger, trip number):  (237, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (238, 2) / 15096
(Passenger, trip number):  (239, 1) / 15096
(Passenger, trip number):  (240, 1) / 15096
(Passenger, trip number):  (241, 1) / 15096
(Passenger, trip number):  (242, 1) / 15096
(Passenger, trip number):  (243, 1) / 15096
(Passenger, trip number):  (244, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (245, 1) / 15096
(Passenger, trip number):  (246, 1) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (247, 2) / 15096
(Passenger, trip number):  (248, 1) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (249, 2) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (250, 1) / 15096
(Passenger, trip number):  (251, 1) / 15096
(Passenger, trip number):  (252, 2) / 15096
(Passenger, trip number):  (253, 2) / 15096
(Passenger, trip number):  (254, 1) / 15096
(Passenger, trip number):  (255, 1) / 15096
(Passenger, trip number):  (256, 2) / 15096
(Passenger, trip number):  (257, 2) / 15096
(Passenger, trip number):  (258, 2) / 15096
(Passenger, trip number):  (259, 1) / 15096
(Passenger, trip number):  (260, 1) / 15096
(Passenger, trip number):  (261, 2) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (262, 1) / 15096
(Passenger, trip number):  (263, 3) / 15096
(Passenger, trip number):  (264, 1) / 15096
(Passenger, trip number):  (265, 1) / 15096
(Passenger, trip number):  (266, 2) / 15096
(Passenger, trip number):  (267, 1) / 15096
(Passenger, trip number):  (268, 2) / 15096
(Passenger, trip number):  (269, 2) / 15096
(Passenger, trip number):  (270, 2) / 15096
(Passenger, trip number):  (271, 1) / 15096
(Passenger, trip number):  (272, 2) / 15096
(Passenger, trip number):  (273, 1) / 15096
(Passenger, trip number):  (274, 1) / 15096
(Passenger, trip number):  (275, 2) / 15096
(Passenger, trip number):  (276, 1) / 15096
(Passenger, trip number):  (277, 1) / 15096
(Passenger, trip number):  (278, 3) / 15096
(Passenger, trip number):  (279, 2) / 15096
(Passenger, trip number):  (280, 1) / 15096
(Passenger, trip number):  (281, 2) / 15096
(Passenger, trip number):  (282, 1) / 15096
(Passenger, trip number):  (283, 1) / 15096
(Passenger, trip number):  (284, 1) / 15096
(Passenger, trip number):  (285, 1) / 15096
(Passenger, trip number):  (286, 2) / 15096
(Passenger, trip number):  (287, 1) / 15096
(Passenger, trip number):  (288, 1) / 15096
(Passenger, trip number):  (289, 2) / 15096
(Passenger, trip number):  (290, 1) / 15096
(Passenger, trip number):  (291, 1) / 15096
(Passenger, trip number):  (292, 2) / 15096
(Passenger, trip number):  (293, 2) / 15096
(Passenger, trip number):  (294, 2) / 15096
(Passenger, trip number):  (295, 2) / 15096
(Passenger, trip number):  (296, 2) / 15096
(Passenger, trip number):  (297, 1) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (298, 2) / 15096
(Passenger, trip number):  (299, 2) / 15096
(Passenger, trip number):  (300, 1) / 15096
(Passenger, trip number):  (301, 2) / 15096
(Passenger, trip number):  (302, 2) / 15096
(Passenger, trip number):  (303, 2) / 15096
(Passenger, trip number):  (304, 1) / 15096
(Passenger, trip number):  (305, 1) / 15096
(Passenger, trip number):  (306, 1) / 15096
(Passenger, trip number):  (307, 1) / 15096
(Passenger, trip number):  (308, 1) / 15096
(Passenger, trip number):  (309, 2) / 15096
(Passenger, trip number):  (310, 2) / 15096
(Passenger, trip number):  (311, 2) / 15096
(Passenger, trip number):  (312, 1) / 15096
(Passenger, trip number):  (313, 2) / 15096
(Passenger, trip number):  (314, 2) / 15096
(Passenger, trip number):  (315, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (316, 1) / 15096
(Passenger, trip number):  (317, 2) / 15096
(Passenger, trip number):  (318, 2) / 15096
(Passenger, trip number):  (319, 2) / 15096
(Passenger, trip number):  (320, 2) / 15096
(Passenger, trip number):  (321, 1) / 15096
(Passenger, trip number):  (322, 2) / 15096
(Passenger, trip number):  (323, 1) / 15096
(Passenger, trip number):  (324, 1) / 15096
(Passenger, trip number):  (325, 1) / 15096
(Passenger, trip number):  (326, 2) / 15096
(Passenger, trip number):  (327, 2) / 15096
(Passenger, trip number):  (328, 1) / 15096
(Passenger, trip number):  (329, 1) / 15096
(Passenger, trip number):  (330, 2) / 15096
(Passenger, trip number):  (331, 1) / 15096
(Passenger, trip number):  (332, 2) / 15096
(Passenger, trip number):  (333, 1) / 15096
(Passenger, trip number):  (334, 1) / 15096
(Passenger, trip number):  (335, 1) / 15096
(Passenger, trip number):  (336, 2) / 15096
(Passenger, trip number):  (337, 1) / 15096
(Passenger, trip number):  (338, 1) / 15096
(Passenger, trip number):  (339, 1) / 15096
(Passenger, trip number):  (340, 2) / 15096
(Passenger, trip number):  (341, 2) / 15096
(Passenger, trip number):  (342, 2) / 15096
(Passenger, trip number):  (343, 1) / 15096
(Passenger, trip number):  (344, 1) / 15096
(Passenger, trip number):  (345, 1) / 15096
(Passenger, trip number):  (346, 2) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (347, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (348, 1) / 15096
(Passenger, trip number):  (349, 2) / 15096
(Passenger, trip number):  (350, 1) / 15096
(Passenger, trip number):  (351, 1) / 15096
(Passenger, trip number):  (352, 2) / 15096
(Passenger, trip number):  (353, 1) / 15096
(Passenger, trip number):  (354, 1) / 15096
(Passenger, trip number):  (355, 1) / 15096
(Passenger, trip number):  (356, 1) / 15096
(Passenger, trip number):  (357, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (358, 1) / 15096
(Passenger, trip number):  (359, 3) / 15096
(Passenger, trip number):  (360, 1) / 15096
(Passenger, trip number):  (361, 2) / 15096
(Passenger, trip number):  (362, 1) / 15096
(Passenger, trip number):  (363, 1) / 15096
(Passenger, trip number):  (364, 2) / 15096
(Passenger, trip number):  (365, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (366, 2) / 15096
(Passenger, trip number):  (367, 2) / 15096
(Passenger, trip number):  (368, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (369, 1) / 15096
(Passenger, trip number):  (370, 1) / 15096
(Passenger, trip number):  (371, 2) / 15096
(Passenger, trip number):  (372, 1) / 15096
(Passenger, trip number):  (373, 2) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (374, 1) / 15096
(Passenger, trip number):  (375, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (376, 1) / 15096
(Passenger, trip number):  (377, 1) / 15096
(Passenger, trip number):  (378, 1) / 15096
(Passenger, trip number):  (379, 2) / 15096
(Passenger, trip number):  (380, 2) / 15096
(Passenger, trip number):  (381, 2) / 15096
(Passenger, trip number):  (382, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (383, 1) / 15096
(Passenger, trip number):  (384, 1) / 15096
(Passenger, trip number):  (385, 1) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (386, 2) / 15096
(Passenger, trip number):  (387, 1) / 15096
(Passenger, trip number):  (388, 1) / 15096
(Passenger, trip number):  (389, 1) / 15096
(Passenger, trip number):  (390, 1) / 15096
(Passenger, trip number):  (391, 1) / 15096
(Passenger, trip number):  (392, 1) / 15096
(Passenger, trip number):  (393, 1) / 15096
(Passenger, trip number):  (394, 1) / 15096
(Passenger, trip number):  (395, 1) / 15096
(Passenger, trip number):  (396, 1) / 15096
(Passenger, trip number):  (397, 2) / 15096
(Passenger, trip number):  (398, 1) / 15096
(Passenger, trip number):  (399, 1) / 15096
(Passenger, trip number):  (400, 2) / 15096
(Passenger, trip number):  (401, 2) / 15096
(Passenger, trip number):  (402, 2) / 15096
(Passenger, trip number):  (403, 1) / 15096
(Passenger, trip number):  (404, 1) / 15096
(Passenger, trip number):  (405, 1) / 15096
(Passenger, trip number):  (406, 2) / 15096
(Passenger, trip number):  (407, 1) / 15096
(Passenger, trip number):  (408, 1) / 15096
(Passenger, trip number):  (409, 1) / 15096
(Passenger, trip number):  (410, 1) / 15096
(Passenger, trip number):  (411, 1) / 15096
(Passenger, trip number):  (412, 1) / 15096
(Passenger, trip number):  (413, 1) / 15096
(Passenger, trip number):  (414, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (415, 1) / 15096
(Passenger, trip number):  (416, 1) / 15096
(Passenger, trip number):  (417, 1) / 15096
(Passenger, trip number):  (418, 1) / 15096
(Passenger, trip number):  (419, 1) / 15096
(Passenger, trip number):  (420, 1) / 15096
(Passenger, trip number):  (421, 2) / 15096
(Passenger, trip number):  (422, 2) / 15096
(Passenger, trip number):  (423, 1) / 15096
(Passenger, trip number):  (424, 2) / 15096
(Passenger, trip number):  (425, 3) / 15096

In [112]:
flights_per_passenger[ list(flights_per_passenger.keys())[2] ]

{'one_one': {'variables': [], 'values': [], 'pax_cnt': [], 'avail_cnt': []},
 'forced_one': {'variables': [], 'values': [], 'pax_cnt': [], 'avail_cnt': []},
 'multi_one': {'variables': [('2_1_AZ20271021TPHOLT17144',
    'AZ20271022TPHOLT8798'),
   ('2_1_AZ20271021TPHOLT17144', 'AZ20271023TPHOLT8798'),
   ('2_1_AZ20271021TPHOLT17144', 'AZ20271022TPHOLT17144'),
   ('2_1_AZ20271021TPHOLT17144', 'AZ20271023TPHOLT17144'),
   ('2_1_AZ20271021TPHOLT17144', 'AZ20271022TPHOLT5535')],
  'values': [197.114198, 177.114198, 197.114198, 177.114198, 187.114198],
  'pax_cnt': [1, 1, 1, 1, 1],
  'avail_cnt': [1, -3, 2, -3, -2]},
 'one_multi': {'variables': [], 'values': [], 'pax_cnt': [], 'avail_cnt': []},
 'multi_multi': {'variables': [],
  'values': [],
  'pax_cnt': [],
  'avail_cnt': []}}

In [113]:
n_variables

125452

In [114]:
t2 = time.time()
print("Variables created! ")
print("Seconds elapsed: ", t2 - t1)

Variables created!
Seconds elapsed:  134.14127469062805

# Craetion of variables to optimize the model!

In [115]:
## Now we create the dictionaries! 
# For local constraints
variables_per_passenger = {}
# For seat constraints!
variables_per_flight = {}

In [116]:
# We initialize the dictionaries
for passenger in list( flights_per_passenger.keys() ):
    variables_per_passenger[passenger] = []

for idx in range(len(available_flights)):
    variables_per_flight[available_flights[idx].dep_key] = {}
    available_seats = available_flights[idx].c_avail_cnt + available_flights[idx].y_avail_cnt
    #
    # Now we save the variables
    variables_per_flight[available_flights[idx].dep_key]["variables"] = []
    variables_per_flight[available_flights[idx].dep_key]["pax_cnt"] = []
    #variables_per_flight[available_flights[idx].dep_key]["avail_cnt"] = available_seats
    variables_per_flight[available_flights[idx].dep_key]["avail_cnt"] = []

# Now we create the variables !

In [117]:
#flights_per_passenger

# CREATION OF THE MODEL !!!

In [118]:
from dimod import ConstrainedQuadraticModel
from dwave.system import LeapHybridCQMSampler

In [119]:
#! pip install multiverse_singularity_optimization-1.9.1-py3-none-any.whl 
import singularity.optimization as sop

In [120]:
ancilla_variable = sop.Variable("ancilla")
# We initialize the total cost
Total_cost = 0*ancilla_variable

In [122]:
n = 0
for passenger in list( flights_per_passenger.keys() ):
    print("Cost: ", n, " / ", len(flights_per_passenger.keys()))
    mini_dict = flights_per_passenger[passenger]
    single_variables = mini_dict["one_one"]["variables"] + mini_dict["forced_one"]["variables"] + mini_dict["multi_one"]["variables"]
    single_values = mini_dict["one_one"]["values"] + mini_dict["forced_one"]["values"] + mini_dict["multi_one"]["values"]
    single_pax_cnt = mini_dict["one_one"]["pax_cnt"] + mini_dict["forced_one"]["pax_cnt"] + mini_dict["multi_one"]["pax_cnt"]
    single_avail_cnt = mini_dict["one_one"]["avail_cnt"] + mini_dict["forced_one"]["avail_cnt"] + mini_dict["multi_one"]["avail_cnt"]

    double_variables = mini_dict["one_multi"]["variables"] + mini_dict["multi_multi"]["variables"]
    double_values = mini_dict["one_multi"]["values"] + mini_dict["multi_multi"]["values"]
    double_pax_cnt = mini_dict["one_multi"]["pax_cnt"] + mini_dict["multi_multi"]["pax_cnt"]
    double_avail_cnt = mini_dict["one_multi"]["avail_cnt"] + mini_dict["multi_multi"]["avail_cnt"]

    for idx in range(len(single_variables)):
        if (len(single_variables) != 0):
            flight_key = single_variables[idx][1]
            
            # The whole variable is the passenger id PLUS the flight
            single_variable = sop.Variable(str(single_variables[idx]))
            single_value = single_values[idx]
            Total_cost = Total_cost + single_variable * single_value

            # We save the variables ! 
            variables_per_passenger[passenger].append(single_variable)

            # For the airplanes! 
            variables_per_flight[flight_key]["variables"].append(single_variable)
            variables_per_flight[flight_key]["pax_cnt"].append(single_pax_cnt[idx])
            if single_avail_cnt[idx] <= 0:
                variables_per_flight[flight_key]["avail_cnt"].append(0)
            else:
                variables_per_flight[flight_key]["avail_cnt"].append(single_avail_cnt[idx])

    for idx2 in range(len(double_variables)):
        if (len(double_variables) != 0):
            flight1, flight2 = double_variables[idx2][1][0], double_variables[idx2][1][1]

            # The whole variable is the apssenger id PLUS the flights
            double_variable = sop.Variable(str(double_variables[idx2]))
            double_value = double_values[idx2]
            Total_cost = Total_cost + double_variable * double_value

            # We save the variables
            variables_per_passenger[passenger].append(double_variable)

            # For the airplanes! 
            ## First plane
            variables_per_flight[flight1]["variables"].append(double_variable)
            variables_per_flight[flight1]["pax_cnt"].append(double_pax_cnt[idx2])
            if double_avail_cnt[idx2][0] <= 0:
                variables_per_flight[flight1]["avail_cnt"].append(0)
            else:
                variables_per_flight[flight1]["avail_cnt"].append(double_avail_cnt[idx2][0])

            ## Second plane
            variables_per_flight[flight2]["variables"].append(double_variable)
            variables_per_flight[flight2]["pax_cnt"].append(double_pax_cnt[idx2])
            if double_avail_cnt[idx2][1] <= 0:
                variables_per_flight[flight2]["avail_cnt"].append(0)
            else:
                variables_per_flight[flight2]["avail_cnt"].append(double_avail_cnt[idx2][1])

    n = n + 1

Constraint:  0  /  15096
Constraint:  1  /  15096
Constraint:  2  /  15096
Constraint:  3  /  15096
Constraint:  4  /  15096
Constraint:  5  /  15096
Constraint:  6  /  15096
Constraint:  7  /  15096
Constraint:  8  /  15096
Constraint:  9  /  15096
Constraint:  10  /  15096
Constraint:  11  /  15096
Constraint:  12  /  15096
Constraint:  13  /  15096
Constraint:  14  /  15096
Constraint:  15  /  15096
Constraint:  16  /  15096
Constraint:  17  /  15096
Constraint:  18  /  15096
Constraint:  19  /  15096
Constraint:  20  /  15096
Constraint:  21  /  15096
Constraint:  22  /  15096
Constraint:  23  /  15096
Constraint:  24  /  15096
Constraint:  25  /  15096
Constraint:  26  /  15096
Constraint:  27  /  15096
Constraint:  28  /  15096
Constraint:  29  /  15096
Constraint:  30  /  15096
Constraint:  31  /  15096
Constraint:  32  /  15096
Constraint:  33  /  15096
Constraint:  34  /  15096
Constraint:  35  /  15096
Constraint:  36  /  15096
Constraint:  37  /  15096
Constraint:  38  /  15096
Constraint:  39  /  15096
Constraint:  40  /  15096
Constraint:  41  /  15096
Constraint:  42  /  15096
Constraint:  43  /  15096
Constraint:  44  /  15096
Constraint:  45  /  15096
Constraint:  46  /  15096
Constraint:  47  /  15096
Constraint:  48  /  15096
Constraint:  49  /  15096
Constraint:  50  /  15096
Constraint:  51  /  15096
Constraint:  52  /  15096
Constraint:  53  /  15096
Constraint:  54  /  15096
Constraint:  55  /  15096
Constraint:  56  /  15096
Constraint:  57  /  15096
Constraint:  58  /  15096
Constraint:  59  /  15096
Constraint:  60  /  15096
Constraint:  61  /  15096
Constraint:  62  /  15096
Constraint:  63  /  15096
Constraint:  64  /  15096
Constraint:  65  /  15096
Constraint:  66  /  15096
Constraint:  67  /  15096
Constraint:  68  /  15096
Constraint:  69  /  15096
Constraint:  70  /  15096
Constraint:  71  /  15096
Constraint:  72  /  15096
Constraint:  73  /  15096
Constraint:  74  /  15096
Constraint:  75  /  15096
Constraint:  76  /  15096
Constraint:  77  /  15096
Constraint:  78  /  15096
Constraint:  79  /  15096
Constraint:  80  /  15096
Constraint:  81  /  15096
Constraint:  82  /  15096
Constraint:  83  /  15096
Constraint:  84  /  15096
Constraint:  85  /  15096
Constraint:  86  /  15096
Constraint:  87  /  15096
Constraint:  88  /  15096
Constraint:  89  /  15096
Constraint:  90  /  15096
Constraint:  91  /  15096
Constraint:  92  /  15096
Constraint:  93  /  15096
Constraint:  94  /  15096
Constraint:  95  /  15096
Constraint:  96  /  15096
Constraint:  97  /  15096
Constraint:  98  /  15096
Constraint:  99  /  15096
Constraint:  100  /  15096
Constraint:  101  /  15096
Constraint:  102  /  15096
Constraint:  103  /  15096
Constraint:  104  /  15096
Constraint:  105  /  15096
Constraint:  106  /  15096
Constraint:  107  /  15096
Constraint:  108  /  15096
Constraint:  109  /  15096
Constraint:  110  /  15096
Constraint:  111  /  15096
Constraint:  112  /  15096
Constraint:  113  /  15096
Constraint:  114  /  15096
Constraint:  115  /  15096
Constraint:  116  /  15096
Constraint:  117  /  15096
Constraint:  118  /  15096
Constraint:  119  /  15096
Constraint:  120  /  15096
Constraint:  121  /  15096
Constraint:  122  /  15096
Constraint:  123  /  15096
Constraint:  124  /  15096
Constraint:  125  /  15096
Constraint:  126  /  15096
Constraint:  127  /  15096
Constraint:  128  /  15096
Constraint:  129  /  15096
Constraint:  130  /  15096
Constraint:  131  /  15096
Constraint:  132  /  15096
Constraint:  133  /  15096
Constraint:  134  /  15096
Constraint:  135  /  15096
Constraint:  136  /  15096
Constraint:  137  /  15096
Constraint:  138  /  15096
Constraint:  139  /  15096
Constraint:  140  /  15096
Constraint:  141  /  15096
Constraint:  142  /  15096
Constraint:  143  /  15096
Constraint:  144  /  15096
Constraint:  145  /  15096
Constraint:  146  /  15096
Constraint:  147  /  15096
Constraint:  148  /  15096
Constraint:  149  /  15096
Constraint:  150  /  15096
Constraint:  151  /  15096
Constraint:  152  /  15096
Constraint:  153  /  15096
Constraint:  154  /  15096
Constraint:  155  /  15096
Constraint:  156  /  15096
Constraint:  157  /  15096
Constraint:  158  /  15096
Constraint:  159  /  15096
Constraint:  160  /  15096
Constraint:  161  /  15096
Constraint:  162  /  15096
Constraint:  163  /  15096
Constraint:  164  /  15096
Constraint:  165  /  15096
Constraint:  166  /  15096
Constraint:  167  /  15096
Constraint:  168  /  15096
Constraint:  169  /  15096
Constraint:  170  /  15096
Constraint:  171  /  15096
Constraint:  172  /  15096
Constraint:  173  /  15096
Constraint:  174  /  15096
Constraint:  175  /  15096
Constraint:  176  /  15096
Constraint:  177  /  15096
Constraint:  178  /  15096
Constraint:  179  /  15096
Constraint:  180  /  15096
Constraint:  181  /  15096
Constraint:  182  /  15096
Constraint:  183  /  15096
Constraint:  184  /  15096
Constraint:  185  /  15096
Constraint:  186  /  15096
Constraint:  187  /  15096
Constraint:  188  /  15096
Constraint:  189  /  15096
Constraint:  190  /  15096
Constraint:  191  /  15096
Constraint:  192  /  15096
Constraint:  193  /  15096
Constraint:  194  /  15096
Constraint:  195  /  15096
Constraint:  196  /  15096
Constraint:  197  /  15096
Constraint:  198  /  15096
Constraint:  199  /  15096
Constraint:  200  /  15096
Constraint:  201  /  15096
Constraint:  202  /  15096
Constraint:  203  /  15096
Constraint:  204  /  15096
Constraint:  205  /  15096
Constraint:  206  /  15096
Constraint:  207  /  15096
Constraint:  208  /  15096
Constraint:  209  /  15096
Constraint:  210  /  15096
Constraint:  211  /  15096
Constraint:  212  /  15096
Constraint:  213  /  15096
Constraint:  214  /  15096
Constraint:  215  /  15096
Constraint:  216  /  15096
Constraint:  217  /  15096
Constraint:  218  /  15096
Constraint:  219  /  15096
Constraint:  220  /  15096
Constraint:  221  /  15096
Constraint:  222  /  15096
Constraint:  223  /  15096
Constraint:  224  /  15096
Constraint:  225  /  15096
Constraint:  226  /  15096
Constraint:  227  /  15096
Constraint:  228  /  15096
Constraint:  229  /  15096
Constraint:  230  /  15096
Constraint:  231  /  15096
Constraint:  232  /  15096
Constraint:  233  /  15096
Constraint:  234  /  15096
Constraint:  235  /  15096
Constraint:  236  /  15096
Constraint:  237  /  15096
Constraint:  238  /  15096
Constraint:  239  /  15096
Constraint:  240  /  15096
Constraint:  241  /  15096
Constraint:  242  /  15096
Constraint:  243  /  15096
Constraint:  244  /  15096
Constraint:  245  /  15096
Constraint:  246  /  15096
Constraint:  247  /  15096
Constraint:  248  /  15096
Constraint:  249  /  15096
Constraint:  250  /  15096
Constraint:  251  /  15096
Constraint:  252  /  15096
Constraint:  253  /  15096
Constraint:  254  /  15096
Constraint:  255  /  15096
Constraint:  256  /  15096
Constraint:  257  /  15096
Constraint:  258  /  15096
Constraint:  259  /  15096
Constraint:  260  /  15096
Constraint:  261  /  15096
Constraint:  262  /  15096
Constraint:  263  /  15096
Constraint:  264  /  15096
Constraint:  265  /  15096
Constraint:  266  /  15096
Constraint:  267  /  15096
Constraint:  268  /  15096
Constraint:  269  /  15096
Constraint:  270  /  15096
Constraint:  271  /  15096
Constraint:  272  /  15096
Constraint:  273  /  15096
Constraint:  274  /  15096
Constraint:  275  /  15096
Constraint:  276  /  15096
Constraint:  277  /  15096
Constraint:  278  /  15096
Constraint:  279  /  15096
Constraint:  280  /  15096
Constraint:  281  /  15096
Constraint:  282  /  15096
Constraint:  283  /  15096
Constraint:  284  /  15096
Constraint:  285  /  15096
Constraint:  286  /  15096
Constraint:  287  /  15096
Constraint:  288  /  15096
Constraint:  289  /  15096
Constraint:  290  /  15096
Constraint:  291  /  15096
Constraint:  292  /  15096
Constraint:  293  /  15096
Constraint:  294  /  15096
Constraint:  295  /  15096
Constraint:  296  /  15096
Constraint:  297  /  15096
Constraint:  298  /  15096
Constraint:  299  /  15096
Constraint:  300  /  15096
Constraint:  301  /  15096
Constraint:  302  /  15096
Constraint:  303  /  15096
Constraint:  304  /  15096
Constraint:  305  /  15096
Constraint:  306  /  15096
Constraint:  307  /  15096
Constraint:  308  /  15096
Constraint:  309  /  15096
Constraint:  310  /  15096
Constraint:  311  /  15096
Constraint:  312  /  15096
Constraint:  313  /  15096
Constraint:  314  /  15096
Constraint:  315  /  15096
Constraint:  316  /  15096
Constraint:  317  /  15096
Constraint:  318  /  15096
Constraint:  319  /  15096
Constraint:  320  /  15096
Constraint:  321  /  15096
Constraint:  322  /  15096
Constraint:  323  /  15096
Constraint:  324  /  15096
Constraint:  325  /  15096
Constraint:  326  /  15096
Constraint:  327  /  15096
Constraint:  328  /  15096
Constraint:  329  /  15096
Constraint:  330  /  15096
Constraint:  331  /  15096
Constraint:  332  /  15096
Constraint:  333  /  15096
Constraint:  334  /  15096
Constraint:  335  /  15096
Constraint:  336  /  15096
Constraint:  337  /  15096
Constraint:  338  /  15096
Constraint:  339  /  15096
Constraint:  340  /  15096
Constraint:  341  /  15096
Constraint:  342  /  15096
Constraint:  343  /  15096
Constraint:  344  /  15096
Constraint:  345  /  15096
Constraint:  346  /  15096
Constraint:  347  /  15096
Constraint:  348  /  15096
Constraint:  349  /  15096
Constraint:  350  /  15096
Constraint:  351  /  15096
Constraint:  352  /  15096
Constraint:  353  /  15096
Constraint:  354  /  15096
Constraint:  355  /  15096
Constraint:  356  /  15096
Constraint:  357  /  15096
Constraint:  358  /  15096
Constraint:  359  /  15096
Constraint:  360  /  15096
Constraint:  361  /  15096
Constraint:  362  /  15096
Constraint:  363  /  15096
Constraint:  364  /  15096
Constraint:  365  /  15096
Constraint:  366  /  15096
Constraint:  367  /  15096
Constraint:  368  /  15096
Constraint:  369  /  15096
Constraint:  370  /  15096
Constraint:  371  /  15096
Constraint:  372  /  15096
Constraint:  373  /  15096
Constraint:  374  /  15096
Constraint:  375  /  15096
Constraint:  376  /  15096
Constraint:  377  /  15096
Constraint:  378  /  15096
Constraint:  379  /  15096
Constraint:  380  /  15096
Constraint:  381  /  15096
Constraint:  382  /  15096
Constraint:  383  /  15096
Constraint:  384  /  15096
Constraint:  385  /  15096
Constraint:  386  /  15096
Constraint:  387  /  15096
Constraint:  388  /  15096
Constraint:  389  /  15096
Constraint:  390  /  15096
Constraint:  391  /  15096
Constraint:  392  /  15096
Constraint:  393  /  15096
Constraint:  394  /  15096
Constraint:  395  /  15096
Constraint:  396  /  15096
Constraint:  397  /  15096
Constraint:  398  /  15096
Constraint:  399  /  15096
Constraint:  400  /  15096
Constraint:  401  /  15096
Constraint:  402  /  15096
Constraint:  403  /  15096
Constraint:  404  /  15096
Constraint:  405  /  15096
Constraint:  406  /  15096
Constraint:  407  /  15096
Constraint:  408  /  15096
Constraint:  409  /  15096
Constraint:  410  /  15096
Constraint:  411  /  15096
Constraint:  412  /  15096
Constraint:  413  /  15096
Constraint:  414  /  15096
Constraint:  415  /  15096
Constraint:  416  /  15096
Constraint:  417  /  15096
Constraint:  418  /  15096
Constraint:  419  /  15096
Constraint:  420  /  15096
Constraint:  421  /  15096
Constraint:  422  /  15096
Constraint:  423  /  15096
Constraint:  424  /  15096
Constraint:  425  /  15096
Constraint:  426  /  15096
Constraint:  427  /  15096
Constraint:  428  /  15096
Constraint:  429  /  15096
Constraint:  430  /  15096
Constraint:  431  /  15096
Constraint:  432  /  15096
Constraint:  433  /  15096
Constraint:  434  /  15096
Constraint:  435  /  15096
Constraint:  436  /  15096
Constraint:  437  /  15096
Constraint:  438  /  15096
Constraint:  439  /  15096
Constraint:  440  /  15096
Constraint:  441  /  15096
Constraint:  442  /  15096
Constraint:  443  /  15096
Constraint:  444  /  15096
Constraint:  445  /  15096
Constraint:  446  /  15096
Constraint:  447  /  15096
Constraint:  448  /  15096
Constraint:  449  /  15096
Constraint:  450  /  15096
Constraint:  451  /  15096
Constraint:  452  /  15096
Constraint:  453  /  15096
Constraint:  454  /  15096
Constraint:  455  /  15096
Constraint:  456  /  15096
Constraint:  457  /  15096
Constraint:  458  /  15096
Constraint:  459  /  15096
Constraint:  460  /  15096
Constraint:  461  /  15096
Constraint:  462  /  15096
Constraint:  463  /  15096
Constraint:  464  /  15096
Constraint:  465  /  15096
Constraint:  466  /  15096
Constraint:  467  /  15096
Constraint:  468  /  15096
Constraint:  469  /  15096
Constraint:  470  /  15096
Constraint:  471  /  15096
Constraint:  472  /  15096
Constraint:  473  /  15096
Constraint:  474  /  15096
Constraint:  475  /  15096
Constraint:  476  /  15096
Constraint:  477  /  15096
Constraint:  478  /  15096
Constraint:  479  /  15096
Constraint:  480  /  15096
Constraint:  481  /  15096
Constraint:  482  /  15096
Constraint:  483  /  15096
Constraint:  484  /  15096
Constraint:  485  /  15096
Constraint:  486  /  15096
Constraint:  487  /  15096
Constraint:  488  /  15096
Constraint:  489  /  15096
Constraint:  490  /  15096
Constraint:  491  /  15096
Constraint:  492  /  15096
Constraint:  493  /  15096
Constraint:  494  /  15096
Constraint:  495  /  15096
Constraint:  496  /  15096
Constraint:  497  /  15096
Constraint:  498  /  15096
Constraint:  499  /  15096
Constraint:  500  /  15096
Constraint:  501  /  15096
Constraint:  502  /  15096
Constraint:  503  /  15096
Constraint:  504  /  15096
Constraint:  505  /  15096
Constraint:  506  /  15096
Constraint:  507  /  15096
Constraint:  508  /  15096
Constraint:  509  /  15096
Constraint:  510  /  15096
Constraint:  511  /  15096
Constraint:  512  /  15096
Constraint:  513  /  15096
Constraint:  514  /  15096
Constraint:  515  /  15096
Constraint:  516  /  15096
Constraint:  517  /  15096
Constraint:  518  /  15096
Constraint:  519  /  15096
Constraint:  520  /  15096
Constraint:  521  /  15096
Constraint:  522  /  15096
Constraint:  523  /  15096
Constraint:  524  /  15096
Constraint:  525  /  15096
Constraint:  526  /  15096
Constraint:  527  /  15096
Constraint:  528  /  15096
Constraint:  529  /  15096
Constraint:  530  /  15096
Constraint:  531  /  15096
Constraint:  532  /  15096
Constraint:  533  /  15096
Constraint:  534  /  15096
Constraint:  535  /  15096
Constraint:  536  /  15096
Constraint:  537  /  15096
Constraint:  538  /  15096
Constraint:  539  /  15096
Constraint:  540  /  15096
Constraint:  541  /  15096
Constraint:  542  /  15096
Constraint:  543  /  15096
Constraint:  544  /  15096
Constraint:  545  /  15096
Constraint:  546  /  15096
Constraint:  547  /  15096
Constraint:  548  /  15096
Constraint:  549  /  15096
Constraint:  550  /  15096
Constraint:  551  /  15096
Constraint:  552  /  15096
Constraint:  553  /  15096
Constraint:  554  /  15096
Constraint:  555  /  15096
Constraint:  556  /  15096
Constraint:  557  /  15096
Constraint:  558  /  15096
Constraint:  559  /  15096
Constraint:  560  /  15096
Constraint:  561  /  15096
Constraint:  562  /  15096
Constraint:  563  /  15096
Constraint:  564  /  15096
Constraint:  565  /  15096
Constraint:  566  /  15096
Constraint:  567  /  15096
Constraint:  568  /  15096
Constraint:  569  /  15096
Constraint:  570  /  15096
Constraint:  571  /  15096
Constraint:  572  /  15096
Constraint:  573  /  15096
Constraint:  574  /  15096
Constraint:  575  /  15096
Constraint:  576  /  15096
Constraint:  577  /  15096
Constraint:  578  /  15096
Constraint:  579  /  15096
Constraint:  580  /  15096
Constraint:  581  /  15096
Constraint:  582  /  15096
Constraint:  583  /  15096
Constraint:  584  /  15096
Constraint:  585  /  15096
Constraint:  586  /  15096
Constraint:  587  /  15096
Constraint:  588  /  15096
Constraint:  589  /  15096
Constraint:  590  /  15096
Constraint:  591  /  15096
Constraint:  592  /  15096
Constraint:  593  /  15096
Constraint:  594  /  15096
Constraint:  595  /  15096
Constraint:  596  /  15096
Constraint:  597  /  15096
Constraint:  598  /  15096
Constraint:  599  /  15096
Constraint:  600  /  15096
Constraint:  601  /  15096
Constraint:  602  /  15096
Constraint:  603  /  15096
Constraint:  604  /  15096
Constraint:  605  /  15096
Constraint:  606  /  15096
Constraint:  607  /  15096
Constraint:  608  /  15096
Constraint:  609  /  15096
Constraint:  610  /  15096
Constraint:  611  /  15096
Constraint:  612  /  15096
Constraint:  613  /  15096
Constraint:  614  /  15096
Constraint:  615  /  15096
Constraint:  616  /  15096
Constraint:  617  /  15096
Constraint:  618  /  15096
Constraint:  619  /  15096
Constraint:  620  /  15096
Constraint:  621  /  15096
Constraint:  622  /  15096
Constraint:  623  /  15096
Constraint:  624  /  15096
Constraint:  625  /  15096
Constraint:  626  /  15096
Constraint:  627  /  15096
Constraint:  628  /  15096
Constraint:  629  /  15096
Constraint:  630  /  15096
Constraint:  631  /  15096
Constraint:  632  /  15096
Constraint:  633  /  15096
Constraint:  634  /  15096
Constraint:  635  /  15096
Constraint:  636  /  15096
Constraint:  637  /  15096
Constraint:  638  /  15096
Constraint:  639  /  15096
Constraint:  640  /  15096
Constraint:  641  /  15096
Constraint:  642  /  15096
Constraint:  643  /  15096
Constraint:  644  /  15096
Constraint:  645  /  15096
Constraint:  646  /  15096
Constraint:  647  /  15096
Constraint:  648  /  15096
Constraint:  649  /  15096
Constraint:  650  /  15096
Constraint:  651  /  15096
Constraint:  652  /  15096
Constraint:  653  /  15096
Constraint:  654  /  15096
Constraint:  655  /  15096
Constraint:  656  /  15096
Constraint:  657  /  15096
Constraint:  658  /  15096
Constraint:  659  /  15096
Constraint:  660  /  15096
Constraint:  661  /  15096
Constraint:  662  /  15096
Constraint:  663  /  15096
Constraint:  664  /  15096
Constraint:  665  /  15096
Constraint:  666  /  15096
Constraint:  667  /  15096
Constraint:  668  /  15096
Constraint:  669  /  15096
Constraint:  670  /  15096
Constraint:  671  /  15096
Constraint:  672  /  15096
Constraint:  673  /  15096
Constraint:  674  /  15096
Constraint:  675  /  15096
Constraint:  676  /  15096
Constraint:  677  /  15096
Constraint:  678  /  15096
Constraint:  679  /  15096
Constraint:  680  /  15096
Constraint:  681  /  15096
Constraint:  682  /  15096
Constraint:  683  /  15096
Constraint:  684  /  15096
Constraint:  685  /  15096
Constraint:  686  /  15096
Constraint:  687  /  15096
Constraint:  688  /  15096
Constraint:  689  /  15096
Constraint:  690  /  15096
Constraint:  691  /  15096
Constraint:  692  /  15096
Constraint:  693  /  15096
Constraint:  694  /  15096
Constraint:  695  /  15096
Constraint:  696  /  15096
Constraint:  697  /  15096
Constraint:  698  /  15096
Constraint:  699  /  15096
Constraint:  700  /  15096
Constraint:  701  /  15096
Constraint:  702  /  15096
Constraint:  703  /  15096
Constraint:  704  /  15096
Constraint:  705  /  15096
Constraint:  706  /  15096
Constraint:  707  /  15096
Constraint:  708  /  15096
Constraint:  709  /  15096
Constraint:  710  /  15096
Constraint:  711  /  15096
Constraint:  712  /  15096
Constraint:  713  /  15096
Constraint:  714  /  15096
Constraint:  715  /  15096
Constraint:  716  /  15096
Constraint:  717  /  15096
Constraint:  718  /  15096
Constraint:  719  /  15096
Constraint:  720  /  15096
Constraint:  721  /  15096
Constraint:  722  /  15096
Constraint:  723  /  15096
Constraint:  724  /  15096
Constraint:  725  /  15096
Constraint:  726  /  15096
Constraint:  727  /  15096
Constraint:  728  /  15096
Constraint:  729  /  15096
Constraint:  730  /  15096
Constraint:  731  /  15096
Constraint:  732  /  15096
Constraint:  733  /  15096
Constraint:  734  /  15096
Constraint:  735  /  15096
Constraint:  736  /  15096
Constraint:  737  /  15096
Constraint:  738  /  15096
Constraint:  739  /  15096
Constraint:  740  /  15096
Constraint:  741  /  15096
Constraint:  742  /  15096
Constraint:  743  /  15096

In [123]:
variables_per_flight.keys()

dict_keys(['AZ20271023RHPTPH17919', 'AZ20271021RHPTPH17919', 'AZ20271024RHPTPH17919', 'AZ20271025RHPTPH17919', 'AZ20271027RHPTPH17919', 'AZ20271020RHPTPH17919', 'AZ20271028RHPTPH17919', 'AZ20271022JDPTPH19123', 'AZ20271024JDPTPH19123', 'AZ20271021JDPTPH19123', 'AZ20271023JDPTPH19123', 'AZ20271020JDPTPH19123', 'AZ20271027JDPTPH19123', 'AZ20271026JDPTPH19123', 'AZ20271028JDPTPH19123', 'AZ20271025JDPTPH19123', 'AZ20271019JDPTPH19123', 'AZ20271023TPHNWY10061', 'AZ20271028TPHNWY10061', 'AZ20271024TPHNWY10061', 'AZ20271027TPHNWY10061', 'AZ20271025TPHNWY10061', 'AZ20271020TPHNWY10061', 'AZ20271022TPHNWY10061', 'AZ20271019TPHNWY10061', 'AZ20271026TPHNWY10061', 'AZ20271028TPHJDP6704', 'AZ20271025TPHJDP6704', 'AZ20271027TPHJDP6704', 'AZ20271023TPHJDP6704', 'AZ20271026TPHJDP6704', 'AZ20271021TPHJDP6704', 'AZ20271024TPHJDP6704', 'AZ20271022TPHJDP6704', 'AZ20271020ECZTPH10704', 'AZ20271024ECZTPH10704', 'AZ20271022ECZTPH10704', 'AZ20271027ECZTPH10704', 'AZ20271024VCFTPH17724', 'AZ20271019VCFTPH17724', 'AZ20271022VCFTPH17724', 'AZ20271025VCFTPH17724', 'AZ20271027VCFTPH17724', 'AZ20271026VCFTPH17724', 'AZ20271020VCFTPH17724', 'AZ20271026TPHQXG9080', 'AZ20271023TPHQXG9080', 'AZ20271025TPHQXG9080', 'AZ20271022TPHQXG9080', 'AZ20271024TPHQXG9080', 'AZ20271027TPHQXG9080', 'AZ20271028TPHQXG9080', 'AZ20271021TPHQXG9080', 'AZ20271020EYFTPH17051', 'AZ20271023EYFTPH17051', 'AZ20271024EYFTPH17051', 'AZ20271028EYFTPH17051', 'AZ20271022EYFTPH17051', 'AZ20271019EYFTPH17051', 'AZ20271027EYFTPH17051', 'AZ20271025EYFTPH17051', 'AZ20271021EYFTPH17051', 'AZ20271026EYFTPH17051', 'AZ20271026EBGTPH5654', 'AZ20271022EBGTPH5654', 'AZ20271024EBGTPH5654', 'AZ20271019EBGTPH5654', 'AZ20271028EBGTPH5654', 'AZ20271021EBGTPH5654', 'AZ20271020EBGTPH5654', 'AZ20271027EBGTPH5654', 'AZ20271025EBGTPH5654', 'AZ20271023EBGTPH5654', 'AZ20271024ZFMTPH17726', 'AZ20271028ZFMTPH17726', 'AZ20271021ZFMTPH17726', 'AZ20271027ZFMTPH17726', 'AZ20271025ZFMTPH17726', 'AZ20271026ZFMTPH17726', 'AZ20271023ZFMTPH17726', 'AZ20271019ZFMTPH17726', 'AZ20271020ZFMTPH17726', 'AZ20271022ZFMTPH17726', 'AZ20271028TPHTZJ10685', 'AZ20271020TPHTZJ10685', 'AZ20271023TPHTZJ10685', 'AZ20271021TPHTZJ10685', 'AZ20271026TPHTZJ10685', 'AZ20271027TPHTZJ10685', 'AZ20271024TPHTZJ10685', 'AZ20271022TZJTPH11611', 'AZ20271025TZJTPH11611', 'AZ20271028TZJTPH11611', 'AZ20271027TZJTPH11611', 'AZ20271021TZJTPH11611', 'AZ20271019TZJTPH11611', 'AZ20271020TZJTPH11611', 'AZ20271023TZJTPH11611', 'AZ20271024TZJTPH11611', 'AZ20271026TZJTPH11611', 'AZ20271026NWYTPH11552', 'AZ20271025NWYTPH11552', 'AZ20271027NWYTPH11552', 'AZ20271022NWYTPH11552', 'AZ20271028NWYTPH11552', 'AZ20271023NWYTPH11552', 'AZ20271021NWYTPH11552', 'AZ20271024NWYTPH11552', 'AZ20271025JDPTPH15100', 'AZ20271019JDPTPH15100', 'AZ20271020JDPTPH15100', 'AZ20271027JDPTPH15100', 'AZ20271028JDPTPH15100', 'AZ20271024JDPTPH15100', 'AZ20271023JDPTPH15100', 'AZ20271021JDPTPH15100', 'AZ20271026JDPTPH15100', 'AZ20271022JDPTPH15100', 'AZ20271019TPHOSW3559', 'AZ20271025TPHOSW3559', 'AZ20271023TPHOSW3559', 'AZ20271022TPHOSW3559', 'AZ20271021TPHOSW3559', 'AZ20271026TPHOSW3559', 'AZ20271028TPHOSW3559', 'AZ20271024TPHOVS17846', 'AZ20271020TPHOVS17846', 'AZ20271027TPHOVS17846', 'AZ20271022TPHOVS17846', 'AZ20271028TZJTPH16021', 'AZ20271026TZJTPH16021', 'AZ20271021TZJTPH16021', 'AZ20271025TZJTPH16021', 'AZ20271023TZJTPH16021', 'AZ20271022TZJTPH16021', 'AZ20271020TZJTPH16021', 'AZ20271024TZJTPH16021', 'AZ20271027TZJTPH16021', 'AZ20271023TPHNAD18287', 'AZ20271028TPHNAD18287', 'AZ20271025TPHNAD18287', 'AZ20271022TPHNAD18287', 'AZ20271027TPHNAD18287', 'AZ20271021TPHNAD18287', 'AZ20271026TPHNAD18287', 'AZ20271024TPHNAD18287', 'AZ20271022TPHVUY17637', 'AZ20271024TPHVUY17637', 'AZ20271025TPHVUY17637', 'AZ20271026TPHVUY17637', 'AZ20271020TPHVUY17637', 'AZ20271019TPHVUY17637', 'AZ20271027TPHVUY17637', 'AZ20271023TPHVUY17637', 'AZ20271028TPHVUY17637', 'AZ20271023QXGRBR14385', 'AZ20271025QXGRBR14385', 'AZ20271021QXGRBR14385', 'AZ20271028QXGRBR14385', 'AZ20271022TPHQXG14385', 'AZ20271025TPHQXG14385', 'AZ20271023TPHQXG14385', 'AZ20271026TPHQXG14385', 'AZ20271024TPHQXG14385', 'AZ20271020TPHQXG14385', 'AZ20271021TPHQXG14385', 'AZ20271027TPHQXG14385', 'AZ20271028TPHQXG14385', 'AZ20271019TPHIPF6489', 'AZ20271027TPHIPF6489', 'AZ20271024TPHIPF6489', 'AZ20271025TPHIPF6489', 'AZ20271021TPHIPF6489', 'AZ20271020TPHIPF6489', 'AZ20271023TPHIPF6489', 'AZ20271028TPHIPF6489', 'AZ20271022TPHIPF6489', 'AZ20271026TPHIPF6489', 'AZ20271023VUYTPH5659', 'AZ20271025VUYTPH5659', 'AZ20271026VUYTPH5659', 'AZ20271021VUYTPH5659', 'AZ20271027VUYTPH5659', 'AZ20271028VUYTPH5659', 'AZ20271024VUYTPH5659', 'AZ20271020TPHERW5969', 'AZ20271026TPHERW5969', 'AZ20271027TPHERW5969', 'AZ20271028TPHERW5969', 'AZ20271025TPHERW5969', 'AZ20271021TPHERW5969', 'AZ20271022TPHERW5969', 'AZ20271023TPHERW5969', 'AZ20271024TPHERW5969', 'AZ20271019TPHHHO3567', 'AZ20271022TPHHHO3567', 'AZ20271021TPHHHO3567', 'AZ20271023TPHHHO3567', 'AZ20271026TPHHHO3567', 'AZ20271020TPHHHO3567', 'AZ20271025TPHHHO3567', 'AZ20271028TPHHHO3567', 'AZ20271024TPHHHO3567', 'AZ20271027TPHHHO3567', 'AZ20271020TPHVUY19976', 'AZ20271023TPHVUY19976', 'AZ20271028TPHVUY19976', 'AZ20271026TPHVUY19976', 'AZ20271022TPHVUY19976', 'AZ20271019TPHVUY19976', 'AZ20271021TPHVUY19976', 'AZ20271027TPHVUY19976', 'AZ20271024TPHVUY19976', 'AZ20271025TPHVUY19976', 'AZ20271027TPHTZJ19911', 'AZ20271023TPHTZJ19911', 'AZ20271022TPHTZJ19911', 'AZ20271025TPHTZJ19911', 'AZ20271026TPHTZJ19911', 'AZ20271028TPHTZJ19911', 'AZ20271019TPHTZJ19911', 'AZ20271024TPHTZJ19911', 'AZ20271021TPHTZJ19911', 'AZ20271027EIDTPH14320', 'AZ20271028EIDTPH14320', 'AZ20271023EIDTPH14320', 'AZ20271020EIDTPH14320', 'AZ20271026EIDTPH14320', 'AZ20271025EIDTPH14320', 'AZ20271024EIDTPH14320', 'AZ20271021EIDTPH14320', 'AZ20271019EIDTPH14320', 'AZ20271023TPHALN8203', 'AZ20271025TPHALN8203', 'AZ20271022TPHALN8203', 'AZ20271024TPHALN8203', 'AZ20271027TPHALN8203', 'AZ20271028TPHALN8203', 'AZ20271021TPHALN8203', 'AZ20271026TPHALN8203', 'AZ20271020EYFTPH14730', 'AZ20271027EYFTPH14730', 'AZ20271022EYFTPH14730', 'AZ20271021EYFTPH14730', 'AZ20271023EYFTPH14730', 'AZ20271024EYFTPH14730', 'AZ20271019EYFTPH14730', 'AZ20271026EYFTPH14730', 'AZ20271028EYFTPH14730', 'AZ20271025EYFTPH14730', 'AZ20271024HIPTPH12956', 'AZ20271025HIPTPH12956', 'AZ20271023HIPTPH12956', 'AZ20271028HIPTPH12956', 'AZ20271027HIPTPH12956', 'AZ20271026HIPTPH12956', 'AZ20271021HIPTPH12956', 'AZ20271028VUYTPH18329', 'AZ20271020VUYTPH18329', 'AZ20271026VUYTPH18329', 'AZ20271023VUYTPH18329', 'AZ20271025VUYTPH18329', 'AZ20271024VUYTPH18329', 'AZ20271019VUYTPH18329', 'AZ20271022VUYTPH18329', 'AZ20271027VUYTPH18329', 'AZ20271019TPHYNZ16840', 'AZ20271020TPHYNZ16840', 'AZ20271024TPHYNZ16840', 'AZ20271025TPHYNZ16840', 'AZ20271021TPHYNZ16840', 'AZ20271028TPHYNZ16840', 'AZ20271022TPHYNZ16840', 'AZ20271026TPHYNZ16840', 'AZ20271023TPHYNZ16840', 'AZ20271027TPHYNZ16840', 'AZ20271027NWYTPH3857', 'AZ20271025NWYTPH3857', 'AZ20271022NWYTPH3857', 'AZ20271026NWYTPH3857', 'AZ20271028NWYTPH3857', 'AZ20271021NWYTPH3857', 'AZ20271020NWYTPH3857', 'AZ20271023NWYTPH3857', 'AZ20271024NWYTPH3857', 'AZ20271019NWYTPH3857', 'AZ20271026QHPTPH5747', 'AZ20271019QHPTPH5747', 'AZ20271028QHPTPH5747', 'AZ20271025QHPTPH5747', 'AZ20271023QHPTPH5747', 'AZ20271027QHPTPH5747', 'AZ20271024QHPTPH5747', 'AZ20271022QHPTPH5747', 'AZ20271024OZGTPH6791', 'AZ20271020OZGTPH6791', 'AZ20271027OZGTPH6791', 'AZ20271022OZGTPH6791', 'AZ20271026OLTTPH7116', 'AZ20271025OLTTPH7116', 'AZ20271027OLTTPH7116', 'AZ20271020OLTTPH7116', 'AZ20271019OLTTPH7116', 'AZ20271024OLTTPH7116', 'AZ20271022OLTTPH7116', 'AZ20271028OLTTPH7116', 'AZ20271021OLTTPH7116', 'AZ20271023OLTTPH7116', 'AZ20271025EIDTPH19272', 'AZ20271022EIDTPH19272', 'AZ20271024EIDTPH19272', 'AZ20271023EIDTPH19272', 'AZ20271028EIDTPH19272', 'AZ20271027EIDTPH19272', 'AZ20271026EIDTPH19272', 'AZ20271027ALNTPH6238', 'AZ20271023ALNTPH6238', 'AZ20271025ALNTPH6238', 'AZ20271026ALNTPH6238', 'AZ20271021ALNTPH6238', 'AZ20271028ALNTPH6238', 'AZ20271024ALNTPH6238', 'AZ20271022ALNTPH6238', 'AZ20271019ALNTPH6238', 'AZ20271020ALNTPH6238', 'AZ20271024TPHRHP2755', 'AZ20271020TPHRHP2755', 'AZ20271023TPHRHP2755', 'AZ20271028TPHRHP2755', 'AZ20271025TPHRHP2755', 'AZ20271027TPHRHP2755', 'AZ20271021TPHRHP2755', 'AZ20271022QRDTPH8166', 'AZ20271028QRDTPH8166', 'AZ20271023QRDTPH8166', 'AZ20271024QRDTPH8166', 'AZ20271019QRDTPH8166', 'AZ20271027QRDTPH8166', 'AZ20271026QRDTPH8166', 'AZ20271025QRDTPH8166', 'AZ20271021QRDTPH8166', 'AZ20271028BPJTPH3490', 'AZ20271024BPJTPH3490', 'AZ20271027BPJTPH3490', 'AZ20271025BPJTPH3490', 'AZ20271022BPJTPH3490', 'AZ20271026BPJTPH3490', 'AZ20271019BPJTPH3490', 'AZ20271023BPJTPH3490', 'AZ20271020BPJTPH3490', 'AZ20271021BPJTPH3490', 'AZ20271025PGMTPH2952', 'AZ20271027PGMTPH2952', 'AZ20271021PGMTPH2952', 'AZ20271028PGMTPH2952', 'AZ20271019PGMTPH2952', 'AZ20271024PGMTPH2952', 'AZ20271022PGMTPH2952', 'AZ20271023PGMTPH2952', 'AZ20271026PGMTPH2952', 'AZ20271020PGMTPH2952', 'AZ20271025IDKTPH10819', 'AZ20271021IDKTPH10819', 'AZ20271020IDKTPH10819', 'AZ20271024IDKTPH10819', 'AZ20271023IDKTPH10819', 'AZ20271028IDKTPH10819', 'AZ20271027IDKTPH10819', 'AZ20271023OYCTPH17708', 'AZ20271027OYCTPH17708', 'AZ20271025OYCTPH17708', 'AZ20271028OYCTPH17708', 'AZ20271021OYCTPH17708', 'AZ20271019OYCTPH17708', 'AZ20271026OYCTPH17708', 'AZ20271024OYCTPH17708', 'AZ20271022OYCTPH17708', 'AZ20271021TPHAIO17519', 'AZ20271020TPHAIO17519', 'AZ20271026TPHAIO17519', 'AZ20271027TPHAIO17519', 'AZ20271023TPHAIO17519', 'AZ20271028TPHAIO17519', 'AZ20271019TPHAIO17519', 'AZ20271022CIATPH10949', 'AZ20271028CIATPH10949', 'AZ20271026CIATPH10949', 'AZ20271025CIATPH10949', 'AZ20271023CIATPH10949', 'AZ20271019CIATPH10949', 'AZ20271024CIATPH10949', 'AZ20271020CIATPH10949', 'AZ20271021CIATPH10949', 'AZ20271027CIATPH10949', 'AZ20271025TPHEYF972', 'AZ20271023TPHEYF972', 'AZ20271022TPHEYF972', 'AZ20271019TPHEYF972', 'AZ20271028TPHEYF972', 'AZ20271026TPHEYF972', 'AZ20271020TPHEYF972', 'AZ20271021TPHEYF972', 'AZ20271024TPHEYF972', 'AZ20271027TPHEYF972', 'AZ20271020PGMTPH18891', 'AZ20271028PGMTPH18891', 'AZ20271027PGMTPH18891', 'AZ20271025PGMTPH18891', 'AZ20271024PGMTPH18891', 'AZ20271023PGMTPH18891', 'AZ20271022JDPTPH8350', 'AZ20271025JDPTPH8350', 'AZ20271023JDPTPH8350', 'AZ20271027JDPTPH8350', 'AZ20271023TPHERW12432', 'AZ20271021TPHERW12432', 'AZ20271020TPHERW12432', 'AZ20271025TPHERW12432', 'AZ20271027TPHERW12432', 'AZ20271028TPHERW12432', 'AZ20271021QHPTPH6350', 'AZ20271020QHPTPH6350', 'AZ20271027QHPTPH6350', 'AZ20271028QHPTPH6350', 'AZ20271025QHPTPH6350', 'AZ20271025ERWTPH18828', 'AZ20271023ERWTPH18828', 'AZ20271021ERWTPH18828', 'AZ20271028ERWTPH18828', 'AZ20271027ERWTPH18828', 'AZ20271020ERWTPH18828', 'AZ20271027JDPTPH16414', 'AZ20271019JDPTPH16414', 'AZ20271022JDPTPH16414', 'AZ20271028JDPTPH16414', 'AZ20271024JDPTPH16414', 'AZ20271023JDPTPH16414', 'AZ20271026JDPTPH16414', 'AZ20271025JDPTPH16414', 'AZ20271028TPHBPJ14232', 'AZ20271022TPHBPJ14232', 'AZ20271019TPHBPJ14232', 'AZ20271023TPHBPJ14232', 'AZ20271026TPHBPJ14232', 'AZ20271025TPHBPJ14232', 'AZ20271027TPHBPJ14232', 'AZ20271021TPHBPJ14232', 'AZ20271024TPHBPJ14232', 'AZ20271026TZJTPH6737', 'AZ20271028TZJTPH6737', 'AZ20271025TZJTPH6737', 'AZ20271022TZJTPH6737', 'AZ20271023TZJTPH6737', 'AZ20271020TZJTPH6737', 'AZ20271027TZJTPH6737', 'AZ20271024TZJTPH6737', 'AZ20271026TPHRJD8543', 'AZ20271024TPHRJD8543', 'AZ20271028TPHRJD8543', 'AZ20271021TPHRJD8543', 'AZ20271019TPHRJD8543', 'AZ20271022TPHEID12343', 'AZ20271026TPHEID12343', 'AZ20271020TPHEID12343', 'AZ20271028TPHEID12343', 'AZ20271019TPHEID12343', 'AZ20271025TPHEID12343', 'AZ20271024TPHEID12343', 'AZ20271027TPHEID12343', 'AZ20271023TPHEID12343', 'AZ20271028IRNTPH19856', 'AZ20271019IRNTPH19856', 'AZ20271021IRNTPH19856', 'AZ20271023IRNTPH19856', 'AZ20271025IRNTPH19856', 'AZ20271026IRNTPH19856', 'AZ20271020TPHMHI8117', 'AZ20271027TPHMHI8117', 'AZ20271025TPHMHI8117', 'AZ20271023TPHMHI8117', 'AZ20271027ZFMTPH9266', 'AZ20271028ZFMTPH9266', 'AZ20271025ZFMTPH9266', 'AZ20271022ZFMTPH9266', 'AZ20271026ZFMTPH9266', 'AZ20271024ZFMTPH9266', 'AZ20271021ZFMTPH9266', 'AZ20271023ZFMTPH9266', 'AZ20271028PSXTPH13635', 'AZ20271023PSXTPH13635', 'AZ20271025PSXTPH13635', 'AZ20271024PSXTPH13635', 'AZ20271026PSXTPH13635', 'AZ20271022PSXTPH13635', 'AZ20271027PSXTPH13635', 'AZ20271021PSXTPH13635', 'AZ20271021ZFMTPH10080', 'AZ20271028ZFMTPH10080', 'AZ20271026ZFMTPH10080', 'AZ20271019ZFMTPH10080', 'AZ20271020ZFMTPH10080', 'AZ20271027ZFMTPH10080', 'AZ20271025ZFMTPH10080', 'AZ20271024ZFMTPH10080', 'AZ20271022ZFMTPH10080', 'AZ20271023ZFMTPH10080', 'AZ20271028TPHEID11017', 'AZ20271021TPHEID11017', 'AZ20271025TPHEID11017', 'AZ20271024TPHEID11017', 'AZ20271027TPHEID11017', 'AZ20271023TPHEID11017', 'AZ20271022TPHEID11017', 'AZ20271026TPHEID11017', 'AZ20271026KHLTPH9777', 'AZ20271023KHLTPH9777', 'AZ20271021KHLTPH9777', 'AZ20271027KHLTPH9777', 'AZ20271025KHLTPH9777', 'AZ20271022KHLTPH9777', 'AZ20271028KHLTPH9777', 'AZ20271024KHLTPH9777', 'AZ20271019KHLTPH9777', 'AZ20271020KHLTPH9777', 'AZ20271020VLLTPH11204', 'AZ20271019VLLTPH11204', 'AZ20271026VLLTPH11204', 'AZ20271022VLLTPH11204', 'AZ20271028VLLTPH11204', 'AZ20271024VLLTPH11204', 'AZ20271021VLLTPH11204', 'AZ20271027VLLTPH11204', 'AZ20271025VLLTPH11204', 'AZ20271027TPHPJY16397', 'AZ20271021TPHPJY16397', 'AZ20271026TPHPJY16397', 'AZ20271022TPHPJY16397', 'AZ20271025TPHPJY16397', 'AZ20271028TPHPJY16397', 'AZ20271023TPHPJY16397', 'AZ20271024TPHPJY16397', 'AZ20271019TPHPJY16397', 'AZ20271026TPHBJH12112', 'AZ20271022TPHBJH12112', 'AZ20271024TPHBJH12112', 'AZ20271023TPHZFM12096', 'AZ20271026TPHZFM12096', 'AZ20271021TPHZFM12096', 'AZ20271028TPHZFM12096', 'AZ20271019TPHALN3819', 'AZ20271020TPHALN3819', 'AZ20271023TPHALN3819', 'AZ20271025TPHALN3819', 'AZ20271026TPHALN3819', 'AZ20271028TPHALN3819', 'AZ20271027TPHALN3819', 'AZ20271022TPHALN3819', 'AZ20271024TPHALN3819', 'AZ20271026NWYTPH12647', 'AZ20271022NWYTPH12647', 'AZ20271024NWYTPH12647', 'AZ20271025NWYTPH12647', 'AZ20271020NWYTPH12647', 'AZ20271023NWYTPH12647', 'AZ20271027NWYTPH12647', 'AZ20271028NWYTPH12647', 'AZ20271026RZDTPH6084', 'AZ20271025RZDTPH6084', 'AZ20271020RZDTPH6084', 'AZ20271019RZDTPH6084', 'AZ20271028RZDTPH6084', 'AZ20271027RZDTPH6084', 'AZ20271021RZDTPH6084', 'AZ20271023RZDTPH6084', 'AZ20271022RZDTPH6084', 'AZ20271024RZDTPH6084', 'AZ20271020TPHCEF5687', 'AZ20271023TPHCEF5687', 'AZ20271028TPHCEF5687', 'AZ20271025TPHCEF5687', 'AZ20271027TPHCEF5687', 'AZ20271024TPHCEF5687', 'AZ20271026TPHCEF5687', 'AZ20271022TPHCEF5687', 'AZ20271022TPHJDP15580', 'AZ20271024TPHJDP15580', 'AZ20271019TPHJDP15580', 'AZ20271028TPHJDP15580', 'AZ20271021TPHJDP15580', 'AZ20271027TPHJDP15580', 'AZ20271026TPHJDP15580', 'AZ20271023TPHJDP15580', 'AZ20271020TPHJDP15580', 'AZ20271025TPHJDP15580', 'AZ20271024TPHJDP12048', 'AZ20271023TPHJDP12048', 'AZ20271019TPHJDP12048', 'AZ20271021TPHJDP12048', 'AZ20271025TPHJDP12048', 'AZ20271022TPHJDP12048', 'AZ20271020TPHJDP12048', 'AZ20271028TPHJDP12048', 'AZ20271027TPHJDP12048', 'AZ20271026TPHJDP12048', 'AZ20271025TPHQRD1370', 'AZ20271027TPHQRD1370', 'AZ20271021TPHQRD1370', 'AZ20271023TPHQRD1370', 'AZ20271026TPHQRD1370', 'AZ20271028TPHQRD1370', 'AZ20271019TPHQRD1370', 'AZ20271022TPHQRD1370', 'AZ20271024TPHQRD1370', 'AZ20271022TPHPSX6156', 'AZ20271027TPHPSX6156', 'AZ20271021TPHPSX6156', 'AZ20271023TPHPSX6156', 'AZ20271020TPHPSX6156', 'AZ20271028TPHPSX6156', 'AZ20271025TPHPSX6156', 'AZ20271026TPHPTP8447', 'AZ20271022TPHPTP8447', 'AZ20271021TPHPTP8447', 'AZ20271027TPHPTP8447', 'AZ20271020TPHPTP8447', 'AZ20271025TPHPTP8447', 'AZ20271019TPHPTP8447', 'AZ20271024TPHPTP8447', 'AZ20271028TPHPTP8447', 'AZ20271023TPHPTP8447', 'AZ20271026JDPTPH15178', 'AZ20271020JDPTPH15178', 'AZ20271025JDPTPH15178', 'AZ20271024JDPTPH15178', 'AZ20271027JDPTPH15178', 'AZ20271028JDPTPH15178', 'AZ20271023JDPTPH15178', 'AZ20271021JDPTPH15178', 'AZ20271019JDPTPH15178', 'AZ20271022LIZTPH14965', 'AZ20271019LIZTPH14965', 'AZ20271026LIZTPH14965', 'AZ20271023LIZTPH14965', 'AZ20271028TPHERW6703', 'AZ20271022TPHERW6703', 'AZ20271024TPHERW6703', 'AZ20271019TPHERW6703', 'AZ20271026TPHERW6703', 'AZ20271023TPHERW6703', 'AZ20271025TPHERW6703', 'AZ20271027TPHEYF15612', 'AZ20271021TPHEYF15612', 'AZ20271023TPHEYF15612', 'AZ20271028TPHEYF15612', 'AZ20271024TPHEYF15612', 'AZ20271025TPHEYF15612', 'AZ20271022TPHEYF15612', 'AZ20271026TPHEYF15612', 'AZ20271019TPHBPJ2145', 'AZ20271023TPHBPJ2145', 'AZ20271020TPHBPJ2145', 'AZ20271021TPHBPJ2145', 'AZ20271028TPHBPJ2145', 'AZ20271025TPHBPJ2145', 'AZ20271024TPHBPJ2145', 'AZ20271022TPHBPJ2145', 'AZ20271026TPHBPJ2145', 'AZ20271027TPHBPJ2145', 'AZ20271027ZRRTPH1266', 'AZ20271026ZRRTPH1266', 'AZ20271023ZRRTPH1266', 'AZ20271021ZRRTPH1266', 'AZ20271024ZRRTPH1266', 'AZ20271020ZRRTPH1266', 'AZ20271025ZRRTPH1266', 'AZ20271028ZRRTPH1266', 'AZ20271019ZRRTPH1266', 'AZ20271022ZRRTPH1266', 'AZ20271028TPHRIU5463', 'AZ20271021TPHRIU5463', 'AZ20271024TPHRIU5463', 'AZ20271020TPHRIU5463', 'AZ20271027TPHRIU5463', 'AZ20271023TPHRIU5463', 'AZ20271020OLTTPH9791', 'AZ20271025OLTTPH9791', 'AZ20271019OLTTPH9791', 'AZ20271021OLTTPH9791', 'AZ20271024OLTTPH9791', 'AZ20271023OLTTPH9791', 'AZ20271026OLTTPH9791', 'AZ20271028OLTTPH9791', 'AZ20271027OLTTPH9791', 'AZ20271025TPHNWY19873', 'AZ20271027TPHNWY19873', 'AZ20271021TPHNWY19873', 'AZ20271023TPHNWY19873', 'AZ20271022TPHNWY19873', 'AZ20271024TPHNWY19873', 'AZ20271028TPHNWY19873', 'AZ20271026TPHNWY19873', 'AZ20271019TPHNWY19873', 'AZ20271025IPFTPH11157', 'AZ20271026IPFTPH11157', 'AZ20271024IPFTPH11157', 'AZ20271028IPFTPH11157', 'AZ20271023IPFTPH11157', 'AZ20271019IPFTPH11157', 'AZ20271020IPFTPH11157', 'AZ20271027IPFTPH11157', 'AZ20271022IPFTPH11157', 'AZ20271021IPFTPH11157', 'AZ20271025TPHCHC18415', 'AZ20271022TPHCHC18415', 'AZ20271027TPHCHC18415', 'AZ20271028TPHRHP12465', 'AZ20271022TPHRHP12465', 'AZ20271019TPHRHP12465', 'AZ20271025TPHRHP12465', 'AZ20271024TPHRHP12465', 'AZ20271027TPHRHP12465', 'AZ20271020TPHRHP12465', 'AZ20271023TPHRHP12465', 'AZ20271026TPHRHP12465', 'AZ20271023TPHIJA11417', 'AZ20271021TPHIJA11417', 'AZ20271019TPHIJA11417', 'AZ20271022TPHIJA11417', 'AZ20271028TPHIJA11417', 'AZ20271025TPHIJA11417', 'AZ20271027TPHIJA11417', 'AZ20271020TPHIJA11417', 'AZ20271024TPHIJA11417', 'AZ20271026TPHIJA11417', 'AZ20271023TPHRHP16724', 'AZ20271024TPHRHP16724', 'AZ20271028TPHRHP16724', 'AZ20271027TPHRHP16724', 'AZ20271026TPHRHP16724', 'AZ20271025TPHRHP16724', 'AZ20271022TPHRHP16724', 'AZ20271021TPHRHP16724', 'AZ20271027NMKTPH16390', 'AZ20271025NMKTPH16390', 'AZ20271028NMKTPH16390', 'AZ20271019NMKTPH16390', 'AZ20271020NMKTPH16390', 'AZ20271021NMKTPH16390', 'AZ20271026NMKTPH16390', 'AZ20271028PTPTPH8485', 'AZ20271023PTPTPH8485', 'AZ20271020PTPTPH8485', 'AZ20271024PTPTPH8485', 'AZ20271019PTPTPH8485', 'AZ20271025PTPTPH8485', 'AZ20271027PTPTPH8485', 'AZ20271021PTPTPH8485', 'AZ20271026PTPTPH8485', 'AZ20271019BPJTPH16910', 'AZ20271028BPJTPH16910', 'AZ20271023BPJTPH16910', 'AZ20271025BPJTPH16910', 'AZ20271020BPJTPH16910', 'AZ20271024BPJTPH16910', 'AZ20271026BPJTPH16910', 'AZ20271022BPJTPH16910', 'AZ20271021BPJTPH16910', 'AZ20271027BPJTPH16910', 'AZ20271020IPFTPH7343', 'AZ20271024IPFTPH7343', 'AZ20271026IPFTPH7343', 'AZ20271028IPFTPH7343', 'AZ20271027IPFTPH7343', 'AZ20271019IPFTPH7343', 'AZ20271022IPFTPH7343', 'AZ20271021IPFTPH7343', 'AZ20271023IPFTPH7343', 'AZ20271025IPFTPH7343', 'AZ20271024VKOTPH3115', 'AZ20271025VKOTPH3115', 'AZ20271020VKOTPH3115', 'AZ20271022VKOTPH3115', 'AZ20271027VKOTPH3115', 'AZ20271021TPHVUY2154', 'AZ20271027TPHVUY2154', 'AZ20271026TPHVUY2154', 'AZ20271020TPHVUY2154', 'AZ20271028TPHVUY2154', 'AZ20271023TPHVUY2154', 'AZ20271024TPHVUY2154', 'AZ20271025TPHVUY2154', 'AZ20271022TPHVUY2154', 'AZ20271024VUYRBR2154', 'AZ20271021VUYRBR2154', 'AZ20271028VUYRBR2154', 'AZ20271025VUYRBR2154', 'AZ20271024JDPTPH19671', 'AZ20271028JDPTPH19671', 'AZ20271026JDPTPH19671', 'AZ20271022JDPTPH19671', 'AZ20271020JDPTPH19671', 'AZ20271025JDPTPH19671', 'AZ20271019JDPTPH19671', 'AZ20271027JDPTPH19671', 'AZ20271023JDPTPH19671', 'AZ20271024TPHLIZ18249', 'AZ20271023TPHLIZ18249', 'AZ20271028TPHLIZ18249', 'AZ20271019TPHLIZ18249', 'AZ20271025TPHLIZ18249', 'AZ20271021TPHLIZ18249', 'AZ20271027TPHLIZ18249', 'AZ20271026TPHLIZ18249', 'AZ20271022TPHL

In [124]:
variables_per_flight["AZ20271022TPHPJY16397"]

{'variables': [('205_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('269_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('274_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('520_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('647_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1185_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1196_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1416_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1762_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1891_3_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1899_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1946_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1975_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2005_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2404_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2475_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2591_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2741_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2842_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3074_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3081_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3225_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3338_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3396_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3511_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3576_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3711_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3791_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3818_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3895_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3961_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3964_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4140_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4385_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4505_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4522_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4777_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5019_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5041_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5488_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5513_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5916_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5973_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6386_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6405_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6415_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6544_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6568_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6621_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6943_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7250_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7644_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7745_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7776_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8016_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8021_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8080_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8133_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8172_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8256_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8429_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8438_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8652_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8850_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8919_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9076_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9309_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9355_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9401_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9435_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9457_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9608_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9759_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9802_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10041_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10196_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10712_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10801_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10908_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10989_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11015_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11118_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11190_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11196_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11671_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11704_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11883_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11915_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11968_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('205_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('269_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('274_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('520_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('647_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1185_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1196_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1416_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1762_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1891_3_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1899_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1946_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('1975_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2005_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2404_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2475_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2591_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2741_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('2842_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3074_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3081_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3225_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3338_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3396_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3511_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3576_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3711_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3791_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3818_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3895_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3961_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('3964_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4140_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4385_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4505_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4522_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('4777_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5019_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5041_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5488_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5513_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5916_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('5973_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6386_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6405_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6415_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6544_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6568_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6621_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('6943_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7250_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7644_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7745_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('7776_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8016_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8021_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8080_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8133_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8172_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8256_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8429_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8438_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8652_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8850_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('8919_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9076_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9309_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9355_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9401_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9435_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9457_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9608_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9759_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('9802_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10041_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10196_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10712_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10801_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10908_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('10989_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11015_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11118_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11190_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11196_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11671_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11704_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11883_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11915_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('11968_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('12299_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('12706_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('12904_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('12989_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13027_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13094_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13195_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13224_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13239_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13396_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13429_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13437_1_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13442_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13628_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13836_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('13870_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397'),
  ('14177_2_AZ20271020TPHPJY16397', 'AZ20271022TPHPJY16397')],
 'pax_cnt': [1,
  1,
  1,
  5,
  1,
  3,
  1,
  1,
  1,
  2,
  4,
  1,
  1,
  1,
  1,
  1,
  5,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  2,
  1,
  2,
  1,
  2,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  4,
  1,
  1,
  6,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  4,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  5,
  1,
  3,
  1,
  1,
  1,
  2,
  4,
  1,
  1,
  1,
  1,
  1,
  5,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  2,
  1,
  2,
  1,
  2,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  1,
  4,
  1,
  1,
  6,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  4,
  1,
  1,
  3,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  3,
  1,
  1,
  1,
  4,
  2,
  2,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  1,
  2,
  1],
 'avail_cnt': [2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2]}

In [125]:
#variables_per_passenger["1772_1_AZ20271021TPHRBR5443"]

# Now we add the seat constraints

In [126]:
seat_constraints = []

for flight in list( variables_per_flight.keys() ):

    sub_dict = variables_per_flight[flight]

    # Some flights are not considered, SKIP !!!
    if all(not v for v in sub_dict.values()):
        print("Skipping flight: ", flight)
        continue  # Skip this flight

    passenger_count = sub_dict["pax_cnt"]
    vars = sub_dict["variables"]
    avail_seats = sub_dict["avail_cnt"][0]

    # Now we perform the weighted sum
    sum_passengers = sum( np.array(vars) * np.array(passenger_count) )

    constraint = sop.Constraint(lhs = sum_passengers, operator="<=", 
                               rhs = avail_seats, penalty_strength= int(1e8),
                               name = f"Seats_{flight}")
    seat_constraints.append(constraint)

Skipping flight:  AZ20271024RHPTPH17919
Skipping flight:  AZ20271025RHPTPH17919
Skipping flight:  AZ20271027RHPTPH17919
Skipping flight:  AZ20271020RHPTPH17919
Skipping flight:  AZ20271028RHPTPH17919
Skipping flight:  AZ20271024JDPTPH19123
Skipping flight:  AZ20271020JDPTPH19123
Skipping flight:  AZ20271027JDPTPH19123
Skipping flight:  AZ20271026JDPTPH19123
Skipping flight:  AZ20271028JDPTPH19123
Skipping flight:  AZ20271025JDPTPH19123
Skipping flight:  AZ20271019JDPTPH19123
Skipping flight:  AZ20271028TPHNWY10061
Skipping flight:  AZ20271024TPHNWY10061
Skipping flight:  AZ20271027TPHNWY10061
Skipping flight:  AZ20271025TPHNWY10061
Skipping flight:  AZ20271020TPHNWY10061
Skipping flight:  AZ20271019TPHNWY10061
Skipping flight:  AZ20271026TPHNWY10061
Skipping flight:  AZ20271028TPHJDP6704
Skipping flight:  AZ20271025TPHJDP6704
Skipping flight:  AZ20271027TPHJDP6704
Skipping flight:  AZ20271026TPHJDP6704
Skipping flight:  AZ20271024TPHJDP6704
Skipping flight:  AZ20271020ECZTPH10704
Skipping flight:  AZ20271024ECZTPH10704
Skipping flight:  AZ20271027ECZTPH10704
Skipping flight:  AZ20271024VCFTPH17724
Skipping flight:  AZ20271019VCFTPH17724
Skipping flight:  AZ20271022VCFTPH17724
Skipping flight:  AZ20271025VCFTPH17724
Skipping flight:  AZ20271027VCFTPH17724
Skipping flight:  AZ20271026VCFTPH17724
Skipping flight:  AZ20271020VCFTPH17724
Skipping flight:  AZ20271026TPHQXG9080
Skipping flight:  AZ20271025TPHQXG9080
Skipping flight:  AZ20271024TPHQXG9080
Skipping flight:  AZ20271027TPHQXG9080
Skipping flight:  AZ20271028TPHQXG9080
Skipping flight:  AZ20271024EYFTPH17051
Skipping flight:  AZ20271028EYFTPH17051
Skipping flight:  AZ20271019EYFTPH17051
Skipping flight:  AZ20271027EYFTPH17051
Skipping flight:  AZ20271025EYFTPH17051
Skipping flight:  AZ20271026EYFTPH17051
Skipping flight:  AZ20271026EBGTPH5654
Skipping flight:  AZ20271022EBGTPH5654
Skipping flight:  AZ20271019EBGTPH5654
Skipping flight:  AZ20271028EBGTPH5654
Skipping flight:  AZ20271021EBGTPH5654
Skipping flight:  AZ20271020EBGTPH5654
Skipping flight:  AZ20271027EBGTPH5654
Skipping flight:  AZ20271025EBGTPH5654
Skipping flight:  AZ20271024ZFMTPH17726
Skipping flight:  AZ20271028ZFMTPH17726
Skipping flight:  AZ20271021ZFMTPH17726
Skipping flight:  AZ20271027ZFMTPH17726
Skipping flight:  AZ20271025ZFMTPH17726
Skipping flight:  AZ20271026ZFMTPH17726
Skipping flight:  AZ20271019ZFMTPH17726
Skipping flight:  AZ20271020ZFMTPH17726
Skipping flight:  AZ20271028TPHTZJ10685
Skipping flight:  AZ20271023TPHTZJ10685
Skipping flight:  AZ20271026TPHTZJ10685
Skipping flight:  AZ20271027TPHTZJ10685
Skipping flight:  AZ20271024TPHTZJ10685
Skipping flight:  AZ20271025TZJTPH11611
Skipping flight:  AZ20271028TZJTPH11611
Skipping flight:  AZ20271027TZJTPH11611
Skipping flight:  AZ20271019TZJTPH11611
Skipping flight:  AZ20271024TZJTPH11611
Skipping flight:  AZ20271026TZJTPH11611
Skipping flight:  AZ20271026NWYTPH11552
Skipping flight:  AZ20271025NWYTPH11552
Skipping flight:  AZ20271027NWYTPH11552
Skipping flight:  AZ20271028NWYTPH11552
Skipping flight:  AZ20271024NWYTPH11552
Skipping flight:  AZ20271025JDPTPH15100
Skipping flight:  AZ20271019JDPTPH15100
Skipping flight:  AZ20271020JDPTPH15100
Skipping flight:  AZ20271027JDPTPH15100
Skipping flight:  AZ20271028JDPTPH15100
Skipping flight:  AZ20271024JDPTPH15100
Skipping flight:  AZ20271026JDPTPH15100
Skipping flight:  AZ20271019TPHOSW3559
Skipping flight:  AZ20271025TPHOSW3559
Skipping flight:  AZ20271026TPHOSW3559
Skipping flight:  AZ20271028TPHOSW3559
Skipping flight:  AZ20271024TPHOVS17846
Skipping flight:  AZ20271020TPHOVS17846
Skipping flight:  AZ20271027TPHOVS17846
Skipping flight:  AZ20271022TPHOVS17846
Skipping flight:  AZ20271028TZJTPH16021
Skipping flight:  AZ20271026TZJTPH16021
Skipping flight:  AZ20271025TZJTPH16021
Skipping flight:  AZ20271020TZJTPH16021
Skipping flight:  AZ20271027TZJTPH16021
Skipping flight:  AZ20271028TPHNAD18287
Skipping flight:  AZ20271025TPHNAD18287
Skipping flight:  AZ20271027TPHNAD18287
Skipping flight:  AZ20271026TPHNAD18287
Skipping flight:  AZ20271024TPHNAD18287
Skipping flight:  AZ20271024TPHVUY17637
Skipping flight:  AZ20271025TPHVUY17637
Skipping flight:  AZ20271026TPHVUY17637
Skipping flight:  AZ20271020TPHVUY17637
Skipping flight:  AZ20271019TPHVUY17637
Skipping flight:  AZ20271027TPHVUY17637
Skipping flight:  AZ20271028TPHVUY17637
Skipping flight:  AZ20271025QXGRBR14385
Skipping flight:  AZ20271021QXGRBR14385
Skipping flight:  AZ20271028QXGRBR14385
Skipping flight:  AZ20271025TPHQXG14385
Skipping flight:  AZ20271026TPHQXG14385
Skipping flight:  AZ20271024TPHQXG14385
Skipping flight:  AZ20271020TPHQXG14385
Skipping flight:  AZ20271027TPHQXG14385
Skipping flight:  AZ20271028TPHQXG14385
Skipping flight:  AZ20271019TPHIPF6489
Skipping flight:  AZ20271027TPHIPF6489
Skipping flight:  AZ20271024TPHIPF6489
Skipping flight:  AZ20271025TPHIPF6489
Skipping flight:  AZ20271021TPHIPF6489
Skipping flight:  AZ20271020TPHIPF6489
Skipping flight:  AZ20271023TPHIPF6489
Skipping flight:  AZ20271028TPHIPF6489
Skipping flight:  AZ20271022TPHIPF6489
Skipping flight:  AZ20271026TPHIPF6489
Skipping flight:  AZ20271025VUYTPH5659
Skipping flight:  AZ20271026VUYTPH5659
Skipping flight:  AZ20271027VUYTPH5659
Skipping flight:  AZ20271028VUYTPH5659
Skipping flight:  AZ20271026TPHERW5969
Skipping flight:  AZ20271027TPHERW5969
Skipping flight:  AZ20271028TPHERW5969
Skipping flight:  AZ20271025TPHERW5969
Skipping flight:  AZ20271024TPHERW5969
Skipping flight:  AZ20271019TPHHHO3567
Skipping flight:  AZ20271021TPHHHO3567
Skipping flight:  AZ20271026TPHHHO3567
Skipping flight:  AZ20271020TPHHHO3567
Skipping flight:  AZ20271025TPHHHO3567
Skipping flight:  AZ20271028TPHHHO3567
Skipping flight:  AZ20271024TPHHHO3567
Skipping flight:  AZ20271027TPHHHO3567
Skipping flight:  AZ20271020TPHVUY19976
Skipping flight:  AZ20271028TPHVUY19976
Skipping flight:  AZ20271026TPHVUY19976
Skipping flight:  AZ20271019TPHVUY19976
Skipping flight:  AZ20271027TPHVUY19976
Skipping flight:  AZ20271024TPHVUY19976
Skipping flight:  AZ20271025TPHVUY19976
Skipping flight:  AZ20271027TPHTZJ19911
Skipping flight:  AZ20271025TPHTZJ19911
Skipping flight:  AZ20271026TPHTZJ19911
Skipping flight:  AZ20271028TPHTZJ19911
Skipping flight:  AZ20271019TPHTZJ19911
Skipping flight:  AZ20271024TPHTZJ19911
Skipping flight:  AZ20271027EIDTPH14320
Skipping flight:  AZ20271028EIDTPH14320
Skipping flight:  AZ20271020EIDTPH14320
Skipping flight:  AZ20271026EIDTPH14320
Skipping flight:  AZ20271025EIDTPH14320
Skipping flight:  AZ20271019EIDTPH14320
Skipping flight:  AZ20271025TPHALN8203
Skipping flight:  AZ20271024TPHALN8203
Skipping flight:  AZ20271027TPHALN8203
Skipping flight:  AZ20271028TPHALN8203
Skipping flight:  AZ20271026TPHALN8203
Skipping flight:  AZ20271020EYFTPH14730
Skipping flight:  AZ20271027EYFTPH14730
Skipping flight:  AZ20271024EYFTPH14730
Skipping flight:  AZ20271019EYFTPH14730
Skipping flight:  AZ20271026EYFTPH14730
Skipping flight:  AZ20271028EYFTPH14730
Skipping flight:  AZ20271025EYFTPH14730
Skipping flight:  AZ20271025HIPTPH12956
Skipping flight:  AZ20271028HIPTPH12956
Skipping flight:  AZ20271027HIPTPH12956
Skipping flight:  AZ20271026HIPTPH12956
Skipping flight:  AZ20271021HIPTPH12956
Skipping flight:  AZ20271028VUYTPH18329
Skipping flight:  AZ20271020VUYTPH18329
Skipping flight:  AZ20271026VUYTPH18329
Skipping flight:  AZ20271025VUYTPH18329
Skipping flight:  AZ20271024VUYTPH18329
Skipping flight:  AZ20271019VUYTPH18329
Skipping flight:  AZ20271027VUYTPH18329
Skipping flight:  AZ20271019TPHYNZ16840
Skipping flight:  AZ20271020TPHYNZ16840
Skipping flight:  AZ20271024TPHYNZ16840
Skipping flight:  AZ20271025TPHYNZ16840
Skipping flight:  AZ20271021TPHYNZ16840
Skipping flight:  AZ20271028TPHYNZ16840
Skipping flight:  AZ20271022TPHYNZ16840
Skipping flight:  AZ20271026TPHYNZ16840
Skipping flight:  AZ20271023TPHYNZ16840
Skipping flight:  AZ20271027TPHYNZ16840
Skipping flight:  AZ20271027NWYTPH3857
Skipping flight:  AZ20271025NWYTPH3857
Skipping flight:  AZ20271026NWYTPH3857
Skipping flight:  AZ20271028NWYTPH3857
Skipping flight:  AZ20271020NWYTPH3857
Skipping flight:  AZ20271024NWYTPH3857
Skipping flight:  AZ20271019NWYTPH3857
Skipping flight:  AZ20271026QHPTPH5747
Skipping flight:  AZ20271019QHPTPH5747
Skipping flight:  AZ20271028QHPTPH5747
Skipping flight:  AZ20271025QHPTPH5747
Skipping flight:  AZ20271027QHPTPH5747
Skipping flight:  AZ20271024OZGTPH6791
Skipping flight:  AZ20271020OZGTPH6791
Skipping flight:  AZ20271027OZGTPH6791
Skipping flight:  AZ20271022OZGTPH6791
Skipping flight:  AZ20271026OLTTPH7116
Skipping flight:  AZ20271025OLTTPH7116
Skipping flight:  AZ20271027OLTTPH7116
Skipping flight:  AZ20271020OLTTPH7116
Skipping flight:  AZ20271019OLTTPH7116
Skipping flight:  AZ20271028OLTTPH7116
Skipping flight:  AZ20271021OLTTPH7116
Skipping flight:  AZ20271025EIDTPH19272
Skipping flight:  AZ20271028EIDTPH19272
Skipping flight:  AZ20271027EIDTPH19272
Skipping flight:  AZ20271026EIDTPH19272
Skipping flight:  AZ20271027ALNTPH6238
Skipping flight:  AZ20271025ALNTPH6238
Skipping flight:  AZ20271026ALNTPH6238
Skipping flight:  AZ20271028ALNTPH6238
Skipping flight:  AZ20271019ALNTPH6238
Skipping flight:  AZ20271020ALNTPH6238
Skipping flight:  AZ20271024TPHRHP2755
Skipping flight:  AZ20271020TPHRHP2755
Skipping flight:  AZ20271028TPHRHP2755
Skipping flight:  AZ20271025TPHRHP2755
Skipping flight:  AZ20271027TPHRHP2755
Skipping flight:  AZ20271028QRDTPH8166
Skipping flight:  AZ20271023QRDTPH8166
Skipping flight:  AZ20271024QRDTPH8166
Skipping flight:  AZ20271019QRDTPH8166
Skipping flight:  AZ20271027QRDTPH8166
Skipping flight:  AZ20271026QRDTPH8166
Skipping flight:  AZ20271025QRDTPH8166
Skipping flight:  AZ20271028BPJTPH3490
Skipping flight:  AZ20271024BPJTPH3490
Skipping flight:  AZ20271027BPJTPH3490
Skipping flight:  AZ20271025BPJTPH3490
Skipping flight:  AZ20271026BPJTPH3490
Skipping flight:  AZ20271019BPJTPH3490
Skipping flight:  AZ20271020BPJTPH3490
Skipping flight:  AZ20271021BPJTPH3490
Skipping flight:  AZ20271025PGMTPH2952
Skipping flight:  AZ20271027PGMTPH2952
Skipping flight:  AZ20271028PGMTPH2952
Skipping flight:  AZ20271019PGMTPH2952
Skipping flight:  AZ20271024PGMTPH2952
Skipping flight:  AZ20271026PGMTPH2952
Skipping flight:  AZ20271020PGMTPH2952
Skipping flight:  AZ20271025IDKTPH10819
Skipping flight:  AZ20271021IDKTPH10819
Skipping flight:  AZ20271020IDKTPH10819
Skipping flight:  AZ20271024IDKTPH10819
Skipping flight:  AZ20271023IDKTPH10819
Skipping flight:  AZ20271028IDKTPH10819
Skipping flight:  AZ20271027IDKTPH10819
Skipping flight:  AZ20271023OYCTPH17708
Skipping flight:  AZ20271027OYCTPH17708
Skipping flight:  AZ20271025OYCTPH17708
Skipping flight:  AZ20271028OYCTPH17708
Skipping flight:  AZ20271019OYCTPH17708
Skipping flight:  AZ20271026OYCTPH17708
Skipping flight:  AZ20271024OYCTPH17708
Skipping flight:  AZ20271021TPHAIO17519
Skipping flight:  AZ20271020TPHAIO17519
Skipping flight:  AZ20271026TPHAIO17519
Skipping flight:  AZ20271027TPHAIO17519
Skipping flight:  AZ20271023TPHAIO17519
Skipping flight:  AZ20271028TPHAIO17519
Skipping flight:  AZ20271019TPHAIO17519
Skipping flight:  AZ20271022CIATPH10949
Skipping flight:  AZ20271028CIATPH10949
Skipping flight:  AZ20271026CIATPH10949
Skipping flight:  AZ20271025CIATPH10949
Skipping flight:  AZ20271023CIATPH10949
Skipping flight:  AZ20271019CIATPH10949
Skipping flight:  AZ20271024CIATPH10949
Skipping flight:  AZ20271020CIATPH10949
Skipping flight:  AZ20271021CIATPH10949
Skipping flight:  AZ20271027CIATPH10949
Skipping flight:  AZ20271025TPHEYF972
Skipping flight:  AZ20271019TPHEYF972
Skipping flight:  AZ20271028TPHEYF972
Skipping flight:  AZ20271026TPHEYF972
Skipping flight:  AZ20271020TPHEYF972
Skipping flight:  AZ20271024TPHEYF972
Skipping flight:  AZ20271027TPHEYF972
Skipping flight:  AZ20271020PGMTPH18891
Skipping flight:  AZ20271028PGMTPH18891
Skipping flight:  AZ20271027PGMTPH18891
Skipping flight:  AZ20271025PGMTPH18891
Skipping flight:  AZ20271025JDPTPH8350
Skipping flight:  AZ20271027JDPTPH8350
Skipping flight:  AZ20271025TPHERW12432
Skipping flight:  AZ20271027TPHERW12432
Skipping flight:  AZ20271028TPHERW12432
Skipping flight:  AZ20271020QHPTPH6350
Skipping flight:  AZ20271027QHPTPH6350
Skipping flight:  AZ20271028QHPTPH6350
Skipping flight:  AZ20271025QHPTPH6350
Skipping flight:  AZ20271025ERWTPH18828
Skipping flight:  AZ20271028ERWTPH18828
Skipping flight:  AZ20271027ERWTPH18828
Skipping flight:  AZ20271027JDPTPH16414
Skipping flight:  AZ20271019JDPTPH16414
Skipping flight:  AZ20271028JDPTPH16414
Skipping flight:  AZ20271024JDPTPH16414
Skipping flight:  AZ20271026JDPTPH16414
Skipping flight:  AZ20271025JDPTPH16414
Skipping flight:  AZ20271028TPHBPJ14232
Skipping flight:  AZ20271019TPHBPJ14232
Skipping flight:  AZ20271023TPHBPJ14232
Skipping flight:  AZ20271026TPHBPJ14232
Skipping flight:  AZ20271025TPHBPJ14232
Skipping flight:  AZ20271027TPHBPJ14232
Skipping flight:  AZ20271024TPHBPJ14232
Skipping flight:  AZ20271026TZJTPH6737
Skipping flight:  AZ20271028TZJTPH6737
Skipping flight:  AZ20271025TZJTPH6737
Skipping flight:  AZ20271027TZJTPH6737
Skipping flight:  AZ20271024TZJTPH6737
Skipping flight:  AZ20271026TPHRJD8543
Skipping flight:  AZ20271024TPHRJD8543
Skipping flight:  AZ20271028TPHRJD8543
Skipping flight:  AZ20271021TPHRJD8543
Skipping flight:  AZ20271019TPHRJD8543
Skipping flight:  AZ20271026TPHEID12343
Skipping flight:  AZ20271028TPHEID12343
Skipping flight:  AZ20271019TPHEID12343
Skipping flight:  AZ20271025TPHEID12343
Skipping flight:  AZ20271024TPHEID12343
Skipping flight:  AZ20271027TPHEID12343
Skipping flight:  AZ20271028IRNTPH19856
Skipping flight:  AZ20271019IRNTPH19856
Skipping flight:  AZ20271021IRNTPH19856
Skipping flight:  AZ20271023IRNTPH19856
Skipping flight:  AZ20271025IRNTPH19856
Skipping flight:  AZ20271026IRNTPH19856
Skipping flight:  AZ20271020TPHMHI8117
Skipping flight:  AZ20271027TPHMHI8117
Skipping flight:  AZ20271025TPHMHI8117
Skipping flight:  AZ20271023TPHMHI8117
Skipping flight:  AZ20271027ZFMTPH9266
Skipping flight:  AZ20271028ZFMTPH9266
Skipping flight:  AZ20271025ZFMTPH9266
Skipping flight:  AZ20271022ZFMTPH9266
Skipping flight:  AZ20271026ZFMTPH9266
Skipping flight:  AZ20271021ZFMTPH9266
Skipping flight:  AZ20271028PSXTPH13635
Skipping flight:  AZ20271023PSXTPH13635
Skipping flight:  AZ20271025PSXTPH13635
Skipping flight:  AZ20271024PSXTPH13635
Skipping flight:  AZ20271026PSXTPH13635
Skipping flight:  AZ20271027PSXTPH13635
Skipping flight:  AZ20271021ZFMTPH10080
Skipping flight:  AZ20271028ZFMTPH10080
Skipping flight:  AZ20271026ZFMTPH10080
Skipping flight:  AZ20271019ZFMTPH10080
Skipping flight:  AZ20271020ZFMTPH10080
Skipping flight:  AZ20271027ZFMTPH10080
Skipping flight:  AZ20271025ZFMTPH10080
Skipping flight:  AZ20271022ZFMTPH10080
Skipping flight:  AZ20271028TPHEID11017
Skipping flight:  AZ20271025TPHEID11017
Skipping flight:  AZ20271024TPHEID11017
Skipping flight:  AZ20271027TPHEID11017
Skipping flight:  AZ20271026TPHEID11017
Skipping flight:  AZ20271026KHLTPH9777
Skipping flight:  AZ20271021KHLTPH9777
Skipping flight:  AZ20271027KHLTPH9777
Skipping flight:  AZ20271025KHLTPH9777
Skipping flight:  AZ20271028KHLTPH9777
Skipping flight:  AZ20271024KHLTPH9777
Skipping flight:  AZ20271019KHLTPH9777
Skipping flight:  AZ20271020KHLTPH9777
Skipping flight:  AZ20271020VLLTPH11204
Skipping flight:  AZ20271019VLLTPH11204
Skipping flight:  AZ20271026VLLTPH11204
Skipping flight:  AZ20271022VLLTPH11204
Skipping flight:  AZ20271028VLLTPH11204
Skipping flight:  AZ20271024VLLTPH11204
Skipping flight:  AZ20271021VLLTPH11204
Skipping flight:  AZ20271027VLLTPH11204
Skipping flight:  AZ20271025VLLTPH11204
Skipping flight:  AZ20271027TPHPJY16397
Skipping flight:  AZ20271026TPHPJY16397
Skipping flight:  AZ20271025TPHPJY16397
Skipping flight:  AZ20271028TPHPJY16397
Skipping flight:  AZ20271023TPHPJY16397
Skipping flight:  AZ20271024TPHPJY16397
Skipping flight:  AZ20271019TPHPJY16397
Skipping flight:  AZ20271026TPHBJH12112
Skipping flight:  AZ20271022TPHBJH12112
Skipping flight:  AZ20271024TPHBJH12112
Skipping flight:  AZ20271023TPHZFM12096
Skipping flight:  AZ20271026TPHZFM12096
Skipping flight:  AZ20271028TPHZFM12096
Skipping flight:  AZ20271019TPHALN3819
Skipping flight:  AZ20271025TPHALN3819
Skipping flight:  AZ20271026TPHALN3819
Skipping flight:  AZ20271028TPHALN3819
Skipping flight:  AZ20271027TPHALN3819
Skipping flight:  AZ20271024TPHALN3819
Skipping flight:  AZ20271026NWYTPH12647
Skipping flight:  AZ20271025NWYTPH12647
Skipping flight:  AZ20271020NWYTPH12647
Skipping flight:  AZ20271027NWYTPH12647
Skipping flight:  AZ20271028NWYTPH12647
Skipping flight:  AZ20271026RZDTPH6084
Skipping flight:  AZ20271025RZDTPH6084
Skipping flight:  AZ20271020RZDTPH6084
Skipping flight:  AZ20271019RZDTPH6084
Skipping flight:  AZ20271028RZDTPH6084
Skipping flight:  AZ20271027RZDTPH6084
Skipping flight:  AZ20271021RZDTPH6084
Skipping flight:  AZ20271024RZDTPH6084
Skipping flight:  AZ20271028TPHCEF5687
Skipping flight:  AZ20271025TPHCEF5687
Skipping flight:  AZ20271027TPHCEF5687
Skipping flight:  AZ20271024TPHCEF5687
Skipping flight:  AZ20271026TPHCEF5687
Skipping flight:  AZ20271024TPHJDP15580
Skipping flight:  AZ20271019TPHJDP15580
Skipping flight:  AZ20271028TPHJDP15580
Skipping flight:  AZ20271027TPHJDP15580
Skipping flight:  AZ20271026TPHJDP15580
Skipping flight:  AZ20271020TPHJDP15580
Skipping flight:  AZ20271025TPHJDP15580
Skipping flight:  AZ20271024TPHJDP12048
Skipping flight:  AZ20271019TPHJDP12048
Skipping flight:  AZ20271025TPHJDP12048
Skipping flight:  AZ20271020TPHJDP12048
Skipping flight:  AZ20271028TPHJDP12048
Skipping flight:  AZ20271027TPHJDP12048
Skipping flight:  AZ20271026TPHJDP12048
Skipping flight:  AZ20271025TPHQRD1370
Skipping flight:  AZ20271027TPHQRD1370
Skipping flight:  AZ20271023TPHQRD1370
Skipping flight:  AZ20271026TPHQRD1370
Skipping flight:  AZ20271028TPHQRD1370
Skipping flight:  AZ20271019TPHQRD1370
Skipping flight:  AZ20271024TPHQRD1370
Skipping flight:  AZ20271022TPHPSX6156
Skipping flight:  AZ20271027TPHPSX6156
Skipping flight:  AZ20271023TPHPSX6156
Skipping flight:  AZ20271028TPHPSX6156
Skipping flight:  AZ20271025TPHPSX6156
Skipping flight:  AZ20271026TPHPTP8447
Skipping flight:  AZ20271021TPHPTP8447
Skipping flight:  AZ20271027TPHPTP8447
Skipping flight:  AZ20271020TPHPTP8447
Skipping flight:  AZ20271025TPHPTP8447
Skipping flight:  AZ20271019TPHPTP8447
Skipping flight:  AZ20271024TPHPTP8447
Skipping flight:  AZ20271028TPHPTP8447
Skipping flight:  AZ20271023TPHPTP8447
Skipping flight:  AZ20271026JDPTPH15178
Skipping flight:  AZ20271020JDPTPH15178
Skipping flight:  AZ20271025JDPTPH15178
Skipping flight:  AZ20271027JDPTPH15178
Skipping flight:  AZ20271028JDPTPH15178
Skipping flight:  AZ20271019JDPTPH15178
Skipping flight:  AZ20271019LIZTPH14965
Skipping flight:  AZ20271026LIZTPH14965
Skipping flight:  AZ20271028TPHERW6703
Skipping flight:  AZ20271024TPHERW6703
Skipping flight:  AZ20271019TPHERW6703
Skipping flight:  AZ20271026TPHERW6703
Skipping flight:  AZ20271025TPHERW6703
Skipping flight:  AZ20271027TPHEYF15612
Skipping flight:  AZ20271028TPHEYF15612
Skipping flight:  AZ20271024TPHEYF15612
Skipping flight:  AZ20271025TPHEYF15612
Skipping flight:  AZ20271026TPHEYF15612
Skipping flight:  AZ20271019TPHBPJ2145
Skipping flight:  AZ20271023TPHBPJ2145
Skipping flight:  AZ20271020TPHBPJ2145
Skipping flight:  AZ20271028TPHBPJ2145
Skipping flight:  AZ20271025TPHBPJ2145
Skipping flight:  AZ20271024TPHBPJ2145
Skipping flight:  AZ20271026TPHBPJ2145
Skipping flight:  AZ20271027TPHBPJ2145
Skipping flight:  AZ20271027ZRRTPH1266
Skipping flight:  AZ20271026ZRRTPH1266
Skipping flight:  AZ20271023ZRRTPH1266
Skipping flight:  AZ20271021ZRRTPH1266
Skipping flight:  AZ20271024ZRRTPH1266
Skipping flight:  AZ20271020ZRRTPH1266
Skipping flight:  AZ20271025ZRRTPH1266
Skipping flight:  AZ20271028ZRRTPH1266
Skipping flight:  AZ20271019ZRRTPH1266
Skipping flight:  AZ20271022ZRRTPH1266
Skipping flight:  AZ20271028TPHRIU5463
Skipping flight:  AZ20271021TPHRIU5463
Skipping flight:  AZ20271024TPHRIU5463
Skipping flight:  AZ20271020TPHRIU5463

In [127]:
print("These flights were not even considered! Example: ")
variables_per_flight["AZ20271024JDPTPH19123"]

These flights were not even considered! Example:

{'variables': [], 'pax_cnt': [], 'avail_cnt': []}

# Now we add the variable constraints

In [128]:
# Number of reaccommodations to assign to each passenger
min_reaccommodations = 1
passenger_constraints = []

for passenger in list( variables_per_passenger.keys() ):
    sum_constraint_passenger = sum(variables_per_passenger[passenger])

    constraint = sop.Constraint(lhs = sum_constraint_passenger, operator=">=", 
                               rhs = min_reaccommodations, penalty_strength= int(1e5),
                               name = f"Min_reaccommodations_{passenger}")
    passenger_constraints.append(constraint)

In [129]:
# Number of reaccommodations to assign to each passenger
max_reaccommodations = 5

for passenger in list( variables_per_passenger.keys() ):
    sum_constraint_passenger = sum(variables_per_passenger[passenger])

    constraint = sop.Constraint(lhs = sum_constraint_passenger, operator="<=", 
                               rhs = max_reaccommodations, penalty_strength= int(1e3),
                               name = f"Max_reaccommodations_{passenger}")
    passenger_constraints.append(constraint)

# Now we obtain the model !!!

In [130]:
objective = sop.Objective(Total_cost, "maximize")
Reaccommodation = sop.Model(objective)

## Now we add the constraints

In [131]:
total_constraints = seat_constraints + passenger_constraints
for idx in range(len(total_constraints)):
    print("Adding constraint: ", idx, "/", len(total_constraints))
    Reaccommodation.add_constraint(total_constraints[idx])

Adding constraint:  0 / 30960
Adding constraint:  1 / 30960
Adding constraint:  2 / 30960
Adding constraint:  3 / 30960
Adding constraint:  4 / 30960
Adding constraint:  5 / 30960
Adding constraint:  6 / 30960
Adding constraint:  7 / 30960
Adding constraint:  8 / 30960
Adding constraint:  9 / 30960
Adding constraint:  10 / 30960
Adding constraint:  11 / 30960
Adding constraint:  12 / 30960
Adding constraint:  13 / 30960
Adding constraint:  14 / 30960
Adding constraint:  15 / 30960
Adding constraint:  16 / 30960
Adding constraint:  17 / 30960
Adding constraint:  18 / 30960
Adding constraint:  19 / 30960
Adding constraint:  20 / 30960
Adding constraint:  21 / 30960
Adding constraint:  22 / 30960
Adding constraint:  23 / 30960
Adding constraint:  24 / 30960
Adding constraint:  25 / 30960
Adding constraint:  26 / 30960
Adding constraint:  27 / 30960
Adding constraint:  28 / 30960
Adding constraint:  29 / 30960
Adding constraint:  30 / 30960
Adding constraint:  31 / 30960
Adding constraint:  32 / 30960
Adding constraint:  33 / 30960
Adding constraint:  34 / 30960
Adding constraint:  35 / 30960
Adding constraint:  36 / 30960
Adding constraint:  37 / 30960
Adding constraint:  38 / 30960
Adding constraint:  39 / 30960
Adding constraint:  40 / 30960
Adding constraint:  41 / 30960
Adding constraint:  42 / 30960
Adding constraint:  43 / 30960
Adding constraint:  44 / 30960
Adding constraint:  45 / 30960
Adding constraint:  46 / 30960
Adding constraint:  47 / 30960
Adding constraint:  48 / 30960
Adding constraint:  49 / 30960
Adding constraint:  50 / 30960
Adding constraint:  51 / 30960
Adding constraint:  52 / 30960
Adding constraint:  53 / 30960
Adding constraint:  54 / 30960
Adding constraint:  55 / 30960
Adding constraint:  56 / 30960
Adding constraint:  57 / 30960
Adding constraint:  58 / 30960
Adding constraint:  59 / 30960
Adding constraint:  60 / 30960
Adding constraint:  61 / 30960
Adding constraint:  62 / 30960
Adding constraint:  63 / 30960
Adding constraint:  64 / 30960
Adding constraint:  65 / 30960
Adding constraint:  66 / 30960
Adding constraint:  67 / 30960
Adding constraint:  68 / 30960
Adding constraint:  69 / 30960
Adding constraint:  70 / 30960
Adding constraint:  71 / 30960
Adding constraint:  72 / 30960
Adding constraint:  73 / 30960
Adding constraint:  74 / 30960
Adding constraint:  75 / 30960
Adding constraint:  76 / 30960
Adding constraint:  77 / 30960
Adding constraint:  78 / 30960
Adding constraint:  79 / 30960
Adding constraint:  80 / 30960
Adding constraint:  81 / 30960
Adding constraint:  82 / 30960
Adding constraint:  83 / 30960
Adding constraint:  84 / 30960
Adding constraint:  85 / 30960
Adding constraint:  86 / 30960
Adding constraint:  87 / 30960
Adding constraint:  88 / 30960
Adding constraint:  89 / 30960
Adding constraint:  90 / 30960
Adding constraint:  91 / 30960
Adding constraint:  92 / 30960
Adding constraint:  93 / 30960
Adding constraint:  94 / 30960
Adding constraint:  95 / 30960
Adding constraint:  96 / 30960
Adding constraint:  97 / 30960
Adding constraint:  98 / 30960
Adding constraint:  99 / 30960
Adding constraint:  100 / 30960
Adding constraint:  101 / 30960
Adding constraint:  102 / 30960
Adding constraint:  103 / 30960
Adding constraint:  104 / 30960
Adding constraint:  105 / 30960
Adding constraint:  106 / 30960
Adding constraint:  107 / 30960
Adding constraint:  108 / 30960
Adding constraint:  109 / 30960
Adding constraint:  110 / 30960
Adding constraint:  111 / 30960
Adding constraint:  112 / 30960
Adding constraint:  113 / 30960
Adding constraint:  114 / 30960
Adding constraint:  115 / 30960
Adding constraint:  116 / 30960
Adding constraint:  117 / 30960
Adding constraint:  118 / 30960
Adding constraint:  119 / 30960
Adding constraint:  120 / 30960
Adding constraint:  121 / 30960
Adding constraint:  122 / 30960
Adding constraint:  123 / 30960
Adding constraint:  124 / 30960
Adding constraint:  125 / 30960
Adding constraint:  126 / 30960
Adding constraint:  127 / 30960
Adding constraint:  128 / 30960
Adding constraint:  129 / 30960
Adding constraint:  130 / 30960
Adding constraint:  131 / 30960
Adding constraint:  132 / 30960
Adding constraint:  133 / 30960
Adding constraint:  134 / 30960
Adding constraint:  135 / 30960
Adding constraint:  136 / 30960
Adding constraint:  137 / 30960
Adding constraint:  138 / 30960
Adding constraint:  139 / 30960
Adding constraint:  140 / 30960
Adding constraint:  141 / 30960
Adding constraint:  142 / 30960
Adding constraint:  143 / 30960
Adding constraint:  144 / 30960
Adding constraint:  145 / 30960
Adding constraint:  146 / 30960
Adding constraint:  147 / 30960
Adding constraint:  148 / 30960
Adding constraint:  149 / 30960
Adding constraint:  150 / 30960
Adding constraint:  151 / 30960
Adding constraint:  152 / 30960
Adding constraint:  153 / 30960
Adding constraint:  154 / 30960
Adding constraint:  155 / 30960
Adding constraint:  156 / 30960
Adding constraint:  157 / 30960
Adding constraint:  158 / 30960
Adding constraint:  159 / 30960
Adding constraint:  160 / 30960
Adding constraint:  161 / 30960
Adding constraint:  162 / 30960
Adding constraint:  163 / 30960
Adding constraint:  164 / 30960
Adding constraint:  165 / 30960
Adding constraint:  166 / 30960
Adding constraint:  167 / 30960
Adding constraint:  168 / 30960
Adding constraint:  169 / 30960
Adding constraint:  170 / 30960
Adding constraint:  171 / 30960
Adding constraint:  172 / 30960
Adding constraint:  173 / 30960
Adding constraint:  174 / 30960
Adding constraint:  175 / 30960
Adding constraint:  176 / 30960
Adding constraint:  177 / 30960
Adding constraint:  178 / 30960
Adding constraint:  179 / 30960
Adding constraint:  180 / 30960
Adding constraint:  181 / 30960
Adding constraint:  182 / 30960
Adding constraint:  183 / 30960
Adding constraint:  184 / 30960
Adding constraint:  185 / 30960
Adding constraint:  186 / 30960
Adding constraint:  187 / 30960
Adding constraint:  188 / 30960
Adding constraint:  189 / 30960
Adding constraint:  190 / 30960
Adding constraint:  191 / 30960
Adding constraint:  192 / 30960
Adding constraint:  193 / 30960
Adding constraint:  194 / 30960
Adding constraint:  195 / 30960
Adding constraint:  196 / 30960
Adding constraint:  197 / 30960
Adding constraint:  198 / 30960
Adding constraint:  199 / 30960
Adding constraint:  200 / 30960
Adding constraint:  201 / 30960
Adding constraint:  202 / 30960
Adding constraint:  203 / 30960
Adding constraint:  204 / 30960
Adding constraint:  205 / 30960
Adding constraint:  206 / 30960
Adding constraint:  207 / 30960
Adding constraint:  208 / 30960
Adding constraint:  209 / 30960
Adding constraint:  210 / 30960
Adding constraint:  211 / 30960
Adding constraint:  212 / 30960
Adding constraint:  213 / 30960
Adding constraint:  214 / 30960
Adding constraint:  215 / 30960
Adding constraint:  216 / 30960
Adding constraint:  217 / 30960
Adding constraint:  218 / 30960
Adding constraint:  219 / 30960
Adding constraint:  220 / 30960
Adding constraint:  221 / 30960
Adding constraint:  222 / 30960
Adding constraint:  223 / 30960
Adding constraint:  224 / 30960
Adding constraint:  225 / 30960
Adding constraint:  226 / 30960
Adding constraint:  227 / 30960
Adding constraint:  228 / 30960
Adding constraint:  229 / 30960
Adding constraint:  230 / 30960
Adding constraint:  231 / 30960
Adding constraint:  232 / 30960
Adding constraint:  233 / 30960
Adding constraint:  234 / 30960
Adding constraint:  235 / 30960
Adding constraint:  236 / 30960
Adding constraint:  237 / 30960
Adding constraint:  238 / 30960
Adding constraint:  239 / 30960
Adding constraint:  240 / 30960
Adding constraint:  241 / 30960
Adding constraint:  242 / 30960
Adding constraint:  243 / 30960
Adding constraint:  244 / 30960
Adding constraint:  245 / 30960
Adding constraint:  246 / 30960
Adding constraint:  247 / 30960
Adding constraint:  248 / 30960
Adding constraint:  249 / 30960
Adding constraint:  250 / 30960
Adding constraint:  251 / 30960
Adding constraint:  252 / 30960
Adding constraint:  253 / 30960
Adding constraint:  254 / 30960
Adding constraint:  255 / 30960
Adding constraint:  256 / 30960
Adding constraint:  257 / 30960
Adding constraint:  258 / 30960
Adding constraint:  259 / 30960
Adding constraint:  260 / 30960
Adding constraint:  261 / 30960
Adding constraint:  262 / 30960
Adding constraint:  263 / 30960
Adding constraint:  264 / 30960
Adding constraint:  265 / 30960
Adding constraint:  266 / 30960
Adding constraint:  267 / 30960
Adding constraint:  268 / 30960
Adding constraint:  269 / 30960
Adding constraint:  270 / 30960
Adding constraint:  271 / 30960
Adding constraint:  272 / 30960
Adding constraint:  273 / 30960
Adding constraint:  274 / 30960
Adding constraint:  275 / 30960
Adding constraint:  276 / 30960
Adding constraint:  277 / 30960
Adding constraint:  278 / 30960
Adding constraint:  279 / 30960
Adding constraint:  280 / 30960
Adding constraint:  281 / 30960
Adding constraint:  282 / 30960
Adding constraint:  283 / 30960
Adding constraint:  284 / 30960
Adding constraint:  285 / 30960
Adding constraint:  286 / 30960
Adding constraint:  287 / 30960
Adding constraint:  288 / 30960
Adding constraint:  289 / 30960
Adding constraint:  290 / 30960
Adding constraint:  291 / 30960
Adding constraint:  292 / 30960
Adding constraint:  293 / 30960
Adding constraint:  294 / 30960
Adding constraint:  295 / 30960
Adding constraint:  296 / 30960
Adding constraint:  297 / 30960
Adding constraint:  298 / 30960
Adding constraint:  299 / 30960
Adding constraint:  300 / 30960
Adding constraint:  301 / 30960
Adding constraint:  302 / 30960
Adding constraint:  303 / 30960
Adding constraint:  304 / 30960
Adding constraint:  305 / 30960
Adding constraint:  306 / 30960
Adding constraint:  307 / 30960
Adding constraint:  308 / 30960
Adding constraint:  309 / 30960
Adding constraint:  310 / 30960
Adding constraint:  311 / 30960
Adding constraint:  312 / 30960
Adding constraint:  313 / 30960
Adding constraint:  314 / 30960
Adding constraint:  315 / 30960
Adding constraint:  316 / 30960
Adding constraint:  317 / 30960
Adding constraint:  318 / 30960
Adding constraint:  319 / 30960
Adding constraint:  320 / 30960
Adding constraint:  321 / 30960
Adding constraint:  322 / 30960
Adding constraint:  323 / 30960
Adding constraint:  324 / 30960
Adding constraint:  325 / 30960
Adding constraint:  326 / 30960
Adding constraint:  327 / 30960
Adding constraint:  328 / 30960
Adding constraint:  329 / 30960
Adding constraint:  330 / 30960
Adding constraint:  331 / 30960
Adding constraint:  332 / 30960
Adding constraint:  333 / 30960
Adding constraint:  334 / 30960
Adding constraint:  335 / 30960
Adding constraint:  336 / 30960
Adding constraint:  337 / 30960
Adding constraint:  338 / 30960
Adding constraint:  339 / 30960
Adding constraint:  340 / 30960
Adding constraint:  341 / 30960
Adding constraint:  342 / 30960
Adding constraint:  343 / 30960
Adding constraint:  344 / 30960
Adding constraint:  345 / 30960
Adding constraint:  346 / 30960
Adding constraint:  347 / 30960
Adding constraint:  348 / 30960
Adding constraint:  349 / 30960
Adding constraint:  350 / 30960
Adding constraint:  351 / 30960
Adding constraint:  352 / 30960
Adding constraint:  353 / 30960
Adding constraint:  354 / 30960
Adding constraint:  355 / 30960
Adding constraint:  356 / 30960
Adding constraint:  357 / 30960
Adding constraint:  358 / 30960
Adding constraint:  359 / 30960
Adding constraint:  360 / 30960
Adding constraint:  361 / 30960
Adding constraint:  362 / 30960
Adding constraint:  363 / 30960
Adding constraint:  364 / 30960
Adding constraint:  365 / 30960
Adding constraint:  366 / 30960
Adding constraint:  367 / 30960
Adding constraint:  368 / 30960
Adding constraint:  369 / 30960
Adding constraint:  370 / 30960
Adding constraint:  371 / 30960
Adding constraint:  372 / 30960
Adding constraint:  373 / 30960
Adding constraint:  374 / 30960
Adding constraint:  375 / 30960
Adding constraint:  376 / 30960
Adding constraint:  377 / 30960
Adding constraint:  378 / 30960
Adding constraint:  379 / 30960
Adding constraint:  380 / 30960
Adding constraint:  381 / 30960
Adding constraint:  382 / 30960
Adding constraint:  383 / 30960
Adding constraint:  384 / 30960
Adding constraint:  385 / 30960
Adding constraint:  386 / 30960
Adding constraint:  387 / 30960
Adding constraint:  388 / 30960
Adding constraint:  389 / 30960
Adding constraint:  390 / 30960
Adding constraint:  391 / 30960
Adding constraint:  392 / 30960
Adding constraint:  393 / 30960
Adding constraint:  394 / 30960
Adding constraint:  395 / 30960
Adding constraint:  396 / 30960
Adding constraint:  397 / 30960
Adding constraint:  398 / 30960
Adding constraint:  399 / 30960
Adding constraint:  400 / 30960
Adding constraint:  401 / 30960
Adding constraint:  402 / 30960
Adding constraint:  403 / 30960
Adding constraint:  404 / 30960
Adding constraint:  405 / 30960
Adding constraint:  406 / 30960
Adding constraint:  407 / 30960
Adding constraint:  408 / 30960
Adding constraint:  409 / 30960
Adding constraint:  410 / 30960
Adding constraint:  411 / 30960
Adding constraint:  412 / 30960
Adding constraint:  413 / 30960
Adding constraint:  414 / 30960
Adding constraint:  415 / 30960
Adding constraint:  416 / 30960
Adding constraint:  417 / 30960
Adding constraint:  418 / 30960
Adding constraint:  419 / 30960
Adding constraint:  420 / 30960
Adding constraint:  421 / 30960
Adding constraint:  422 / 30960
Adding constraint:  423 / 30960
Adding constraint:  424 / 30960
Adding constraint:  425 / 30960
Adding constraint:  426 / 30960
Adding constraint:  427 / 30960
Adding constraint:  428 / 30960
Adding constraint:  429 / 30960
Adding constraint:  430 / 30960
Adding constraint:  431 / 30960
Adding constraint:  432 / 30960
Adding constraint:  433 / 30960
Adding constraint:  434 / 30960
Adding constraint:  435 / 30960
Adding constraint:  436 / 30960
Adding constraint:  437 / 30960
Adding constraint:  438 / 30960
Adding constraint:  439 / 30960
Adding constraint:  440 / 30960
Adding constraint:  441 / 30960
Adding constraint:  442 / 30960
Adding constraint:  443 / 30960
Adding constraint:  444 / 30960
Adding constraint:  445 / 30960
Adding constraint:  446 / 30960
Adding constraint:  447 / 30960
Adding constraint:  448 / 30960
Adding constraint:  449 / 30960
Adding constraint:  450 / 30960
Adding constraint:  451 / 30960
Adding constraint:  452 / 30960
Adding constraint:  453 / 30960
Adding constraint:  454 / 30960
Adding constraint:  455 / 30960
Adding constraint:  456 / 30960
Adding constraint:  457 / 30960
Adding constraint:  458 / 30960
Adding constraint:  459 / 30960
Adding constraint:  460 / 30960
Adding constraint:  461 / 30960
Adding constraint:  462 / 30960
Adding constraint:  463 / 30960
Adding constraint:  464 / 30960
Adding constraint:  465 / 30960
Adding constraint:  466 / 30960
Adding constraint:  467 / 30960
Adding constraint:  468 / 30960
Adding constraint:  469 / 30960
Adding constraint:  470 / 30960
Adding constraint:  471 / 30960
Adding constraint:  472 / 30960
Adding constraint:  473 / 30960
Adding constraint:  474 / 30960
Adding constraint:  475 / 30960
Adding constraint:  476 / 30960
Adding constraint:  477 / 30960
Adding constraint:  478 / 30960
Adding constraint:  479 / 30960
Adding constraint:  480 / 30960
Adding constraint:  481 / 30960
Adding constraint:  482 / 30960
Adding constraint:  483 / 30960
Adding constraint:  484 / 30960
Adding constraint:  485 / 30960
Adding constraint:  486 / 30960
Adding constraint:  487 / 30960
Adding constraint:  488 / 30960
Adding constraint:  489 / 30960
Adding constraint:  490 / 30960
Adding constraint:  491 / 30960
Adding constraint:  492 / 30960
Adding constraint:  493 / 30960
Adding constraint:  494 / 30960
Adding constraint:  495 / 30960
Adding constraint:  496 / 30960
Adding constraint:  497 / 30960
Adding constraint:  498 / 30960
Adding constraint:  499 / 30960
Adding constraint:  500 / 30960
Adding constraint:  501 / 30960
Adding constraint:  502 / 30960
Adding constraint:  503 / 30960
Adding constraint:  504 / 30960
Adding constraint:  505 / 30960
Adding constraint:  506 / 30960
Adding constraint:  507 / 30960
Adding constraint:  508 / 30960
Adding constraint:  509 / 30960
Adding constraint:  510 / 30960
Adding constraint:  511 / 30960
Adding constraint:  512 / 30960
Adding constraint:  513 / 30960
Adding constraint:  514 / 30960
Adding constraint:  515 / 30960
Adding constraint:  516 / 30960
Adding constraint:  517 / 30960
Adding constraint:  518 / 30960
Adding constraint:  519 / 30960
Adding constraint:  520 / 30960
Adding constraint:  521 / 30960
Adding constraint:  522 / 30960
Adding constraint:  523 / 30960
Adding constraint:  524 / 30960
Adding constraint:  525 / 30960
Adding constraint:  526 / 30960
Adding constraint:  527 / 30960
Adding constraint:  528 / 30960
Adding constraint:  529 / 30960
Adding constraint:  530 / 30960
Adding constraint:  531 / 30960
Adding constraint:  532 / 30960
Adding constraint:  533 / 30960
Adding constraint:  534 / 30960
Adding constraint:  535 / 30960
Adding constraint:  536 / 30960
Adding constraint:  537 / 30960
Adding constraint:  538 / 30960
Adding constraint:  539 / 30960
Adding constraint:  540 / 30960
Adding constraint:  541 / 30960
Adding constraint:  542 / 30960
Adding constraint:  543 / 30960
Adding constraint:  544 / 30960
Adding constraint:  545 / 30960
Adding constraint:  546 / 30960
Adding constraint:  547 / 30960
Adding constraint:  548 / 30960
Adding constraint:  549 / 30960
Adding constraint:  550 / 30960
Adding constraint:  551 / 30960
Adding constraint:  552 / 30960
Adding constraint:  553 / 30960
Adding constraint:  554 / 30960
Adding constraint:  555 / 30960
Adding constraint:  556 / 30960
Adding constraint:  557 / 30960
Adding constraint:  558 / 30960
Adding constraint:  559 / 30960
Adding constraint:  560 / 30960
Adding constraint:  561 / 30960
Adding constraint:  562 / 30960
Adding constraint:  563 / 30960
Adding constraint:  564 / 30960
Adding constraint:  565 / 30960
Adding constraint:  566 / 30960
Adding constraint:  567 / 30960
Adding constraint:  568 / 30960
Adding constraint:  569 / 30960
Adding constraint:  570 / 30960
Adding constraint:  571 / 30960
Adding constraint:  572 / 30960
Adding constraint:  573 / 30960
Adding constraint:  574 / 30960
Adding constraint:  575 / 30960
Adding constraint:  576 / 30960
Adding constraint:  577 / 30960
Adding constraint:  578 / 30960
Adding constraint:  579 / 30960
Adding constraint:  580 / 30960
Adding constraint:  581 / 30960
Adding constraint:  582 / 30960
Adding constraint:  583 / 30960
Adding constraint:  584 / 30960
Adding constraint:  585 / 30960
Adding constraint:  586 / 30960
Adding constraint:  587 / 30960
Adding constraint:  588 / 30960
Adding constraint:  589 / 30960
Adding constraint:  590 / 30960
Adding constraint:  591 / 30960
Adding constraint:  592 / 30960
Adding constraint:  593 / 30960
Adding constraint:  594 / 30960
Adding constraint:  595 / 30960
Adding constraint:  596 / 30960
Adding constraint:  597 / 30960
Adding constraint:  598 / 30960
Adding constraint:  599 / 30960
Adding constraint:  600 / 30960
Adding constraint:  601 / 30960
Adding constraint:  602 / 30960
Adding constraint:  603 / 30960
Adding constraint:  604 / 30960
Adding constraint:  605 / 30960
Adding constraint:  606 / 30960
Adding constraint:  607 / 30960
Adding constraint:  608 / 30960
Adding constraint:  609 / 30960
Adding constraint:  610 / 30960
Adding constraint:  611 / 30960
Adding constraint:  612 / 30960
Adding constraint:  613 / 30960
Adding constraint:  614 / 30960
Adding constraint:  615 / 30960
Adding constraint:  616 / 30960
Adding constraint:  617 / 30960
Adding constraint:  618 / 30960
Adding constraint:  619 / 30960
Adding constraint:  620 / 30960
Adding constraint:  621 / 30960
Adding constraint:  622 / 30960
Adding constraint:  623 / 30960
Adding constraint:  624 / 30960
Adding constraint:  625 / 30960
Adding constraint:  626 / 30960
Adding constraint:  627 / 30960

KeyboardInterrupt:

In [ ]:
len(passenger_constraints)

In [ ]:
len(pnr_list)

In [ ]:
print("Total number of variables", n_one_one + n_one_multi + n_forced_one + n_multi_one + n_multi_multi)

# Now we optimize !

In [ ]:
# This one supports up to 1M variables!

#solver = "dwave_hybrid"
#solver = "simulated_annealing"
solver = "classical"

# Import solver ! 
#import neal
#solver=neal.SimulatedAnnealingSampler()

In [ ]:
time_in = time.time()

In [ ]:
result = Reaccommodation.optimize(solver="classical")
if solver == "classical":
    result = Reaccommodation.optimize(solver=solver)
else:
    result = Reaccommodation.optimize(solver= solver, num_solutions = 10, 
                                  time_limit= 60*5, dwave_api_token = DWAVE_API_TOKEN
                                  )

In [ ]:
time_out = time.time()
print("Minutes taken to optimize: ", (time_out - time_in) / 60)

with open("time_taken_DWAVE.txt", "w") as f:
    f.write(str((time_in - time_out)/60) )

In [ ]:
print("Best solution: ")
print("Objective value: ", result.objective_value)
BestResults = result.values
BestResults

# Nowe we create a dictionary where to save the results

In [ ]:
ReaccommodationResults = {}

for idx in range(len(pnr_list)):
    parts = pnr_list[idx].trip_id
    parts = parts.split("_")

    new_key = f"{parts[0]}_{parts[2]}"

    # Now we save the new keys
    ReaccommodationResults[new_key] = []

In [ ]:
#ReaccommodationResults

# Now we save the results

In [ ]:
import re
import ast

# Updated regex pattern to handle nested tuples
pattern = r"\('(\d+)_(\d+)_([^']+)',\s*(\(.+\)|'[^']+')\)"

In [ ]:
for key, value in BestResults.items():

    # We skip this option if it is not correct ! 
    if value != 1:
        continue
    # We obtain the name of the variable
    item = key.name
    
    # We check the match
    match = re.match(pattern, item)
    
    if match:
        pnr_recloc, trip_number, flight_dep_key, flight_reaccommodations = match.groups()
        #print("pnr_recloc:", pnr_recloc, "flight_dep_key:", flight_dep_key, "flight_reaccommodations:", flight_reaccommodations)

        new_key = f"{pnr_recloc}_{flight_dep_key}"

        # We save the results ! 
        ReaccommodationResults[new_key].append( ast.literal_eval(flight_reaccommodations) )

    else:
        print("No match for:", item)
    



    #ancilla_str = str(key).split(",")[0][2:-1].split("_")
    #recloc_nr, flight_nr = ancilla_str[0], ancilla_str[2]

In [ ]:
list(ReaccommodationResults.values())[0]

# Now we obtain the reaccommodation results

In [ ]:
n_reaccommodated = 0

for reaccommodation in ReaccommodationResults.values():
    if reaccommodation != []:
        n_reaccommodated = n_reaccommodated + 1

print("Percentage of reaccommodation: ",  n_reaccommodated / len(pnr_list) * 100)

with open("Reaccommodation_percentage.txt", "w") as f:
    f.write(str( n_reaccommodated / len(pnr_list) * 100)  )

In [ ]:
print(ReaccommodationResults)

# Now we save the results in the desired format

In [ ]:
RECLOC = []
CABIN_CD = []
COS_CD = []
OPER_OD_ORIG_CD = []
OPER_OD_DEST_CD = []
DEP_KEY = []
DEP_DT = []
ORIG_CD = []
DEST_CD = []
FLT_NUM = []
DEP_DTML = []
ARR_DTML = []
DEP_DTMZ = []
ARR_DTMZ = []
PREV_OD_BROKEN_IND = []
PAX_CNT = []
CVM = []
PREV_CONN_TIME = []

# New arrays
ALT_CABIN_CD = []
ALT_OPER_OD_ORIG_CD = []
ALT_OPER_OD_DEST_CD = []
ALT_DEP_DT = []
ALT_ORIG_CD = []
ALT_DEST_CD = []
ALT_FLT_NUM = []
ALT_DEP_DTML = []
ALT_ARR_DTML = []
ALT_DEP_DTMZ = []
ALT_ARR_DTMZ = []
ALT_CONN_TIME_MINS = []

In [ ]:
for key, values in ReaccommodationResults.items():
    given_pnr = key.split("_")[0]
    given_dep_key = key.split("_")[1]

    #given_pnr_df = pnr_df[(pnr_df["RECLOC"] == given_pnr) & (pnr_df["DEP_KEY"] == given_dep_key)]
    given_pnr_df = pnr_df[ (pnr_df["RECLOC"] == int(given_pnr)) & (pnr_df["DEP_KEY"] == given_dep_key) ]
    # Now we iterate over the results 

    # NO SOLUTIONS !!!! 
    if values == []:
        print("RECLOC, FLIGHT Has no options: ", given_pnr, ", ", given_dep_key)
        RECLOC.append(given_pnr_df["RECLOC"].values[0])
        CABIN_CD.append(given_pnr_df["CABIN_CD"].values[0])
        COS_CD.append(given_pnr_df["COS_CD"].values[0])
        OPER_OD_ORIG_CD.append(given_pnr_df["OPER_OD_ORIG_CD"].values[0])
        OPER_OD_DEST_CD.append(given_pnr_df["OPER_OD_DEST_CD"].values[0])
        DEP_KEY.append(given_pnr_df["DEP_KEY"].values[0])
        DEP_DT.append(given_pnr_df["DEP_DT"].values[0])
        ORIG_CD.append(given_pnr_df["ORIG_CD"].values[0])
        DEST_CD.append(given_pnr_df["DEST_CD"].values[0])
        FLT_NUM.append(given_pnr_df["FLT_NUM"].values[0])
        DEP_DTML.append(given_pnr_df["DEP_DTML"].values[0])
        ARR_DTML.append(given_pnr_df["ARR_DTML"].values[0])
        DEP_DTMZ.append(given_pnr_df["DEP_DTMZ"].values[0])
        ARR_DTMZ.append(given_pnr_df["ARR_DTMZ"].values[0])
        PREV_OD_BROKEN_IND.append(given_pnr_df["OD_BROKEN_IND"].values[0])
        PAX_CNT.append(given_pnr_df["PAX_CNT"].values[0])
        CVM.append(given_pnr_df["CVM"].values[0])
        PREV_CONN_TIME.append(given_pnr_df["CONN_TIME_MINS"].values[0])

        # Now for the reaaccommodation
        ALT_CABIN_CD.append(None)
        ALT_OPER_OD_ORIG_CD.append(None)
        ALT_OPER_OD_DEST_CD.append(None)
        ALT_DEP_DT.append(None)
        ALT_ORIG_CD.append(None)
        ALT_DEST_CD.append(None)
        ALT_FLT_NUM.append(None)
        ALT_DEP_DTML.append(None)
        ALT_ARR_DTML.append(None)
        ALT_DEP_DTMZ.append(None)
        ALT_ARR_DTMZ.append(None)
        ALT_CONN_TIME_MINS.append(None)


    else: 
        for reaccommodation in values:
            
            # Case where we have a single alternate flight ! 
            if type(reaccommodation) == str:
                given_avail_flight_df = available_flights_df[available_flights_df["DEP_KEY"] == reaccommodation]

                RECLOC.append(given_pnr_df["RECLOC"].values[0])
                CABIN_CD.append(given_pnr_df["CABIN_CD"].values[0])
                COS_CD.append(given_pnr_df["COS_CD"].values[0])
                OPER_OD_ORIG_CD.append(given_pnr_df["OPER_OD_ORIG_CD"].values[0])
                OPER_OD_DEST_CD.append(given_pnr_df["OPER_OD_DEST_CD"].values[0])
                DEP_KEY.append(given_pnr_df["DEP_KEY"].values[0])
                DEP_DT.append(given_pnr_df["DEP_DT"].values[0])
                ORIG_CD.append(given_pnr_df["ORIG_CD"].values[0])
                DEST_CD.append(given_pnr_df["DEST_CD"].values[0])
                FLT_NUM.append(given_pnr_df["FLT_NUM"].values[0])
                DEP_DTML.append(given_pnr_df["DEP_DTML"].values[0])
                ARR_DTML.append(given_pnr_df["ARR_DTML"].values[0])
                DEP_DTMZ.append(given_pnr_df["DEP_DTMZ"].values[0])
                ARR_DTMZ.append(given_pnr_df["ARR_DTMZ"].values[0])
                PREV_OD_BROKEN_IND.append(given_pnr_df["OD_BROKEN_IND"].values[0])
                PAX_CNT.append(given_pnr_df["PAX_CNT"].values[0])
                CVM.append(given_pnr_df["CVM"].values[0])
                PREV_CONN_TIME.append(given_pnr_df["CONN_TIME_MINS"].values[0])

                # Now for the reaaccommodation
                ALT_CABIN_CD.append("Either")
                ALT_OPER_OD_ORIG_CD.append(given_avail_flight_df["ORIG_CD"].values[0])
                ALT_OPER_OD_DEST_CD.append(given_avail_flight_df["DEST_CD"].values[0])
                ALT_DEP_DT.append(given_avail_flight_df["DEP_DT"].values[0])
                ALT_ORIG_CD.append(given_avail_flight_df["ORIG_CD"].values[0])
                ALT_DEST_CD.append(given_avail_flight_df["DEST_CD"].values[0])
                ALT_FLT_NUM.append(given_avail_flight_df["FLT_NUM"].values[0])
                ALT_DEP_DTML.append(given_avail_flight_df["DEP_DTML"].values[0])
                ALT_ARR_DTML.append(given_avail_flight_df["ARR_DTML"].values[0])
                ALT_DEP_DTMZ.append(given_avail_flight_df["DEP_DTMZ"].values[0])
                ALT_ARR_DTMZ.append(given_avail_flight_df["ARR_DTMZ"].values[0])
                ALT_CONN_TIME_MINS.append( None )
            
            # Two reaccommodations ! 
            elif type(reaccommodation) == tuple:
                for leg in reaccommodation:
                    leg_df = available_flights_df[available_flights_df["DEP_KEY"] == leg]

                    RECLOC.append(given_pnr_df["RECLOC"].values[0])
                    CABIN_CD.append(given_pnr_df["CABIN_CD"].values[0])
                    COS_CD.append(given_pnr_df["COS_CD"].values[0])
                    OPER_OD_ORIG_CD.append(given_pnr_df["OPER_OD_ORIG_CD"].values[0])
                    OPER_OD_DEST_CD.append(given_pnr_df["OPER_OD_DEST_CD"].values[0])
                    DEP_KEY.append(given_pnr_df["DEP_KEY"].values[0])
                    DEP_DT.append(given_pnr_df["DEP_DT"].values[0])
                    ORIG_CD.append(given_pnr_df["ORIG_CD"].values[0])
                    DEST_CD.append(given_pnr_df["DEST_CD"].values[0])
                    FLT_NUM.append(given_pnr_df["FLT_NUM"].values[0])
                    DEP_DTML.append(given_pnr_df["DEP_DTML"].values[0])
                    ARR_DTML.append(given_pnr_df["ARR_DTML"].values[0])
                    DEP_DTMZ.append(given_pnr_df["DEP_DTMZ"].values[0])
                    ARR_DTMZ.append(given_pnr_df["ARR_DTMZ"].values[0])
                    PREV_OD_BROKEN_IND.append(given_pnr_df["OD_BROKEN_IND"].values[0])
                    PAX_CNT.append(given_pnr_df["PAX_CNT"].values[0])
                    CVM.append(given_pnr_df["CVM"].values[0])
                    PREV_CONN_TIME.append(given_pnr_df["CONN_TIME_MINS"].values[0])

                    # Now for the reaaccommodation
                    ALT_CABIN_CD.append("Either")
                    ALT_OPER_OD_ORIG_CD.append(leg_df["ORIG_CD"].values[0])
                    ALT_OPER_OD_DEST_CD.append(leg_df["DEST_CD"].values[0])
                    ALT_DEP_DT.append(leg_df["DEP_DT"].values[0])
                    ALT_ORIG_CD.append(leg_df["ORIG_CD"].values[0])
                    ALT_DEST_CD.append(leg_df["DEST_CD"].values[0])
                    ALT_FLT_NUM.append(leg_df["FLT_NUM"].values[0])
                    ALT_DEP_DTML.append(leg_df["DEP_DTML"].values[0])
                    ALT_ARR_DTML.append(leg_df["ARR_DTML"].values[0])
                    ALT_DEP_DTMZ.append(leg_df["DEP_DTMZ"].values[0])
                    ALT_ARR_DTMZ.append(leg_df["ARR_DTMZ"].values[0])
                
                
                # Now we change the connection time
                leg1, leg2 = reaccommodation[0], reaccommodation[1]
                leg1_df = available_flights_df[available_flights_df["DEP_KEY"] == leg1]
                leg2_df = available_flights_df[available_flights_df["DEP_KEY"] == leg1]
                
                ALT_CONN_TIME_MINS.append( None )

                first_time = pd.to_datetime(leg1_df["ARR_DTML"].values[0], errors="coerce", infer_datetime_format=True)
                second_time = pd.to_datetime(leg2_df["DEP_DTML"].values[0], errors="coerce", infer_datetime_format=True)
                delta_t = (first_time - second_time).total_seconds() / 60

                ALT_CONN_TIME_MINS.append(delta_t)

# Now we save the results into a dictionary

In [ ]:
Results_dict = {}

Results_dict["RECLOC"] = RECLOC
Results_dict["CABIN_CD"] = CABIN_CD
Results_dict["COS_CD"] = COS_CD
Results_dict["OPER_OD_ORIG_CD"] = OPER_OD_ORIG_CD
Results_dict["OPER_OD_DEST_CD"] = OPER_OD_DEST_CD
Results_dict["DEP_KEY"] = DEP_KEY
Results_dict["DEP_DT"] = DEP_DT
Results_dict["ORIG_CD"] = ORIG_CD
Results_dict["DEST_CD"] = DEST_CD
Results_dict["FLT_NUM"] = FLT_NUM
Results_dict["DEP_DTML"] = DEP_DTML
Results_dict["ARR_DTML"] = ARR_DTML
Results_dict["DEP_DTMZ"] = DEP_DTMZ
Results_dict["ARR_DTMZ"] = ARR_DTMZ
Results_dict["PREV_OD_BROKEN_IND"] = PREV_OD_BROKEN_IND
Results_dict["PAX_CNT"] = PAX_CNT
Results_dict["CVM"] = CVM
Results_dict["PREV_CONN_TIME"] = PREV_CONN_TIME

Results_dict["ALT_CABIN_CD"] = ALT_CABIN_CD
Results_dict["ALT_OPER_OD_ORIG_CD"] = ALT_OPER_OD_ORIG_CD
Results_dict["ALT_OPER_OD_DEST_CD"] = ALT_OPER_OD_DEST_CD
Results_dict["ALT_DEP_DT"] = ALT_DEP_DT
Results_dict["ALT_ORIG_CD"] = ALT_ORIG_CD
Results_dict["ALT_DEST_CD"] = ALT_DEST_CD
Results_dict["ALT_FLT_NUM"] = ALT_FLT_NUM
Results_dict["ALT_DEP_DTML"] = ALT_DEP_DTML
Results_dict["ALT_ARR_DTML"] = ALT_ARR_DTML
Results_dict["ALT_DEP_DTMZ"] = ALT_DEP_DTMZ
Results_dict["ALT_ARR_DTMZ"] = ALT_ARR_DTMZ
Results_dict["ALT_CONN_TIME_MINS"] = ALT_CONN_TIME_MINS

In [ ]:
Results_df = pd.DataFrame(Results_dict)
Results_df

# Save the results into a csv

In [ ]:
Results_df.to_csv("Results_DWAVE.csv", index = False)